# Data Extraction and Web Scraping

We will use a real-world example to demonstrate the concepts of data extraction via REST API and GraphQL. The APIs we will be using are the [GitHub REST API](https://docs.github.com/en/rest) and [GitHub GraphQL API](https://docs.github.com/en/graphql).

They are both APIs provided by GitHub to access data on their platform. The GraphQL API is a newer API. You can access data such as user profiles, repositories, issues, pull requests, releases etc. from GitHub.

We will use the following libraries for this lesson:

- `requests` for making HTTP requests
- `json` for parsing JSON responses
- `pandas` and `numpy` for data manipulation
- `sqlalchemy` for writing data to database (DuckDB)
- `beautifulsoup4` for web scraping

## REST API

Usually, before we can make a request to an API, we need to register for an API key. This is for the API provider to track usage, prevent abuse and to authenticate users. For more information on how to authenticate with GitHub API, refer to the [GitHub API docs](https://docs.github.com/en/rest/overview/resources-in-the-rest-api?apiVersion=2022-11-28#authentication). 

For this lesson, you will need to a personal access token (API key). If you do not have an API key, you can create a new one by folllowing the instructions in the official GitHub documentation [here](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens#creating-a-fine-grained-personal-access-token).

We will be retrieving data from some popular repositories on GitHub.

### Setting up Github API

After getting Github API key, please create a file called `.env` at the root folder of this repository. Alternatively, you can run the following code **ONCE** to create the env file.

In [1]:
import os

# Cell: Create the .env Template File
# -----------------------------------
template_content = """# .env file for GitHub Access
# 1. REPLACE the placeholder value <YOUR-GITHUB-ACCESS-TOKEN> below with the actual
#    GitHub access token. e.g., ghp_XXXXX
# 2. Save the file.

GITHUB_TOKEN='<YOUR-GITHUB-ACCESS-TOKEN>'
"""

# Check if env file already there
env_file_path = '../.env'
if os.path.exists(env_file_path):
    print(f"Warning: The file '{env_file_path}' already exists.")
    print("Please check the file and update the values if necessary.")
    print("Please open the '../.env' file and replace the '<YOUR-GITHUB-ACCESS-TOKEN>' placeholders with your actual token.")
    exit(1)
else:
    # Use mode 'w' to overwrite the file cleanly
    try:
        with open('../.env', 'w') as f:
            f.write(template_content)

        print("Template file created: ../.env")
        print("Please open the '../.env' file and replace the '<YOUR-GITHUB-ACCESS-TOKEN>' placeholders with your actual token.")
    except Exception as e:
        print(f"Error creating file: {e}")

Template file created: ../.env
Please open the '../.env' file and replace the '<YOUR-GITHUB-ACCESS-TOKEN>' placeholders with your actual token.


Next, open the `.env` file and replace your Github token with the placeholder:

```text
GITHUB_TOKEN='<YOUR-GITHUB-ACCESS-TOKEN>'
```

Save and close the file when done.

> Please note that when you sync your work to Github, this file will not be synced. Please keep a copy of `.env` safe elsewhere.

In [2]:
import requests
import os
from dotenv import load_dotenv

load_dotenv()
access_token = os.getenv('GITHUB_TOKEN')

Github API endpoints are in the format 
```
https://api.github.com/repos/{owner}/{repo}
```
and appended with the resource you want to access.

For example, to access the `issues` resource, the endpoint is
```
https://api.github.com/repos/{owner}/{repo}/issues
```

---

Here are some common endpoints:

| Resource | Endpoint |
| --- | --- |
| Issues | `/issues` |
| Pull Requests | `/pulls` |
| Commits | `/commits` |
| Contributors | `/contributors` |
| Languages | `/languages` |
| Releases | `/releases` |
| Tags | `/tags` |
| Branches | `/branches` |
| Forks | `/forks` |
| Stargazers | `/stargazers` |
| Subscribers | `/subscribers` |
| Subscription | `/subscription` |

Here are the HTTP verbs for the Github API:

| Verb | Description |
| --- | --- |
| GET | Used for retrieving resources. |
| POST | Used for creating resources. |
| PATCH | Used for updating resources with partial JSON data. For instance, an Issue resource has title and body attributes. A PATCH request may accept one or more of the attributes to update the resource. |
| PUT | Used for replacing resources or collections. For PUT requests with no body attribute, be sure to set the Content-Length header to zero. |
| DELETE | Used for deleting resources. |

We will only be using the GET verb for this project,

`Pandas` is an open-source library, its code repository is hosted on GitHub. You can access the repository at [https://github.com/pandas-dev/pandas](https://github.com/pandas-dev/pandas).

Let's try to extract the past `releases` (library versions) from the the repository. The API endpoint is `https://api.github.com/repos/pandas-dev/pandas/releases`.

The access token needs to be passed in the `Authorization` header. The token is a personal access token (PAT) which you can generate on GitHub. The token is used to authenticate you as a user and to authorize you to access the repository.

It is also recommended to pass in the following headers:

- `Accept: application/vnd.github+json` - to specify the preferred format of the response
- `X-GitHub-Api-Version:2022-11-28` - to specify the version of the API to use

---

If we use a `GET` request to access the endpoint, we will get a list of releases in JSON format (default limit of _30 results_ per page). More info on the `releases` resource [here](https://docs.github.com/en/rest/releases/releases?apiVersion=2022-11-28).

In [3]:
response = requests.get("https://api.github.com/repos/pandas-dev/pandas/releases", 
                        headers={"Accept": "application/vnd.github+json", "Authorization": f"Bearer {access_token}"})

We can check if the response is successful by checking the status code of the response. If the status code is 200, then the response is successful.

In [4]:
response.status_code

200

> **Troubleshooting**:
> **What if we have status code in the range of 400?**
>
> refer to https://developer.mozilla.org/en-US/docs/Web/HTTP/Reference/Status for details.
> - Check your token in dotenv if it is in order
> - Print variable `access_token` to see if the token is same as your token in dotenv file
> - Restart your kernel may solved the issue.
> - Check if your token has expired
> - Setup a new token from Github

Use the `.json()` method to return the JSON format of the response object.

In [5]:
releases_page_1 = response.json()

In [6]:
type(releases_page_1)

list

In [7]:
len(releases_page_1)

30

In [8]:
releases_page_1[0]

{'url': 'https://api.github.com/repos/pandas-dev/pandas/releases/320615205',
 'assets_url': 'https://api.github.com/repos/pandas-dev/pandas/releases/320615205/assets',
 'upload_url': 'https://uploads.github.com/repos/pandas-dev/pandas/releases/320615205/assets{?name,label}',
 'html_url': 'https://github.com/pandas-dev/pandas/releases/tag/v3.0.3',
 'id': 320615205,
 'author': {'login': 'jorisvandenbossche',
  'id': 1020496,
  'node_id': 'MDQ6VXNlcjEwMjA0OTY=',
  'avatar_url': 'https://avatars.githubusercontent.com/u/1020496?v=4',
  'gravatar_id': '',
  'url': 'https://api.github.com/users/jorisvandenbossche',
  'html_url': 'https://github.com/jorisvandenbossche',
  'followers_url': 'https://api.github.com/users/jorisvandenbossche/followers',
  'following_url': 'https://api.github.com/users/jorisvandenbossche/following{/other_user}',
  'gists_url': 'https://api.github.com/users/jorisvandenbossche/gists{/gist_id}',
  'starred_url': 'https://api.github.com/users/jorisvandenbossche/starred{/owner}{/repo}',
  'subscriptions_url': 'https://api.github.com/users/jorisvandenbossche/subscriptions',
  'organizations_url': 'https://api.github.com/users/jorisvandenbossche/orgs',
  'repos_url': 'https://api.github.com/users/jorisvandenbossche/repos',
  'events_url': 'https://api.github.com/users/jorisvandenbossche/events{/privacy}',
  'received_events_url': 'https://api.github.com/users/jorisvandenbossche/received_events',
  'type': 'User',
  'user_view_type': 'public',
  'site_admin': False},
 'node_id': 'RE_kwDOAA0YD84THDMl',
 'tag_name': 'v3.0.3',
 'target_commitish': '3.0.x',
 'name': 'pandas 3.0.3',
 'draft': False,
 'immutable': False,
 'prerelease': False,
 'created_at': '2026-05-11T16:19:45Z',
 'updated_at': '2026-05-11T19:16:31Z',
 'published_at': '2026-05-11T18:23:29Z',
 'assets': [{'url': 'https://api.github.com/repos/pandas-dev/pandas/releases/assets/417700027',
   'id': 417700027,
   'node_id': 'RA_kwDOAA0YD84Y5Zi7',
   'name': 'pandas-3.0.3.tar.gz',
   'label': None,
   'uploader': {'login': 'jorisvandenbossche',
    'id': 1020496,
    'node_id': 'MDQ6VXNlcjEwMjA0OTY=',
    'avatar_url': 'https://avatars.githubusercontent.com/u/1020496?v=4',
    'gravatar_id': '',
    'url': 'https://api.github.com/users/jorisvandenbossche',
    'html_url': 'https://github.com/jorisvandenbossche',
    'followers_url': 'https://api.github.com/users/jorisvandenbossche/followers',
    'following_url': 'https://api.github.com/users/jorisvandenbossche/following{/other_user}',
    'gists_url': 'https://api.github.com/users/jorisvandenbossche/gists{/gist_id}',
    'starred_url': 'https://api.github.com/users/jorisvandenbossche/starred{/owner}{/repo}',
    'subscriptions_url': 'https://api.github.com/users/jorisvandenbossche/subscriptions',
    'organizations_url': 'https://api.github.com/users/jorisvandenbossche/orgs',
    'repos_url': 'https://api.github.com/users/jorisvandenbossche/repos',
    'events_url': 'https://api.github.com/users/jorisvandenbossche/events{/privacy}',
    'received_events_url': 'https://api.github.com/users/jorisvandenbossche/received_events',
    'type': 'User',
    'user_view_type': 'public',
    'site_admin': False},
   'content_type': 'application/gzip',
   'state': 'uploaded',
   'size': 4651414,
   'digest': 'sha256:696a4a00a2a2a35d4e5deb3fc946641b96c944f02230e4f76137fe35d806c4fc',
   'download_count': 205,
   'created_at': '2026-05-11T19:16:29Z',
   'updated_at': '2026-05-11T19:16:31Z',
   'browser_download_url': 'https://github.com/pandas-dev/pandas/releases/download/v3.0.3/pandas-3.0.3.tar.gz'}],
 'tarball_url': 'https://api.github.com/repos/pandas-dev/pandas/tarball/v3.0.3',
 'zipball_url': 'https://api.github.com/repos/pandas-dev/pandas/zipball/v3.0.3',
 'body': 'We are pleased to announce the release of pandas 3.0.3.\r\nThis is a patch release in the 3.0.x series and includes some regression fixes and bug fixes. We recommend that all users of the 3.0.x series upgrade to this version.\r\n\r\nSee the [full whatsnew](https://pandas.pydata.org/docs/whatsnew/v3.0.3.html) for a list of all the changes.\r\n\r\nPandas 3.0 supports Python 3.11 and higher. \r\nThe release can be installed from PyPI:\r\n\r\n    python -m pip install --upgrade pandas==3.0.*\r\n\r\nOr from conda-forge\r\n\r\n    conda install -c conda-forge pandas=3.0\r\n\r\nPlease report any issues with the release on the [pandas issue tracker](https://github.com/pandas-dev/pandas/issues).\r\n\r\nThanks to all the contributors who made this release possible.',
 'reactions': {'url': 'https://api.github.com/repos/pandas-dev/pandas/releases/320615205/reactions',
  'total_count': 21,
  '+1': 2,
  '-1': 0,
  'laugh': 0,
  'hooray': 11,
  'confused': 0,
  'heart': 5,
  'rocket': 3,
  'eyes': 0}}

In [9]:
releases_page_1[0]['name']

'pandas 3.0.3'

In [10]:
releases_page_1[0]['published_at']

'2026-05-11T18:23:29Z'

The latest version of `pandas` is the one shown above. Hence, the list is sorted from most recent to oldest.

While the last release on the list is:

In [11]:
releases_page_1[-1]['name']

'Pandas 1.5.2'

In [12]:
releases_page_1[-1]['published_at']

'2022-11-22T07:07:41Z'

Remember the default results per page is `30`. You can increase the number of results per page to a maximum of `100` by using the `per_page` query parameter.

In [13]:
response = requests.get("https://api.github.com/repos/pandas-dev/pandas/releases?per_page=100", 
                        headers={"Accept": "application/vnd.github+json", "Authorization": f"Bearer {access_token}"})

In [14]:
releases_page_1_100 = response.json()

In [15]:
len(releases_page_1_100)

100

In [15]:
releases_page_1_100[-1]

{'url': 'https://api.github.com/repos/pandas-dev/pandas/releases/2776482',
 'assets_url': 'https://api.github.com/repos/pandas-dev/pandas/releases/2776482/assets',
 'upload_url': 'https://uploads.github.com/repos/pandas-dev/pandas/releases/2776482/assets{?name,label}',
 'html_url': 'https://github.com/pandas-dev/pandas/releases/tag/v0.18.0rc2',
 'id': 2776482,
 'author': {'login': 'jreback',
  'id': 953992,
  'node_id': 'MDQ6VXNlcjk1Mzk5Mg==',
  'avatar_url': 'https://avatars.githubusercontent.com/u/953992?v=4',
  'gravatar_id': '',
  'url': 'https://api.github.com/users/jreback',
  'html_url': 'https://github.com/jreback',
  'followers_url': 'https://api.github.com/users/jreback/followers',
  'following_url': 'https://api.github.com/users/jreback/following{/other_user}',
  'gists_url': 'https://api.github.com/users/jreback/gists{/gist_id}',
  'starred_url': 'https://api.github.com/users/jreback/starred{/owner}{/repo}',
  'subscriptions_url': 'https://api.github.com/users/jreback/subscriptions',
  'organizations_url': 'https://api.github.com/users/jreback/orgs',
  'repos_url': 'https://api.github.com/users/jreback/repos',
  'events_url': 'https://api.github.com/users/jreback/events{/privacy}',
  'received_events_url': 'https://api.github.com/users/jreback/received_events',
  'type': 'User',
  'user_view_type': 'public',
  'site_admin': False},
 'node_id': 'MDc6UmVsZWFzZTI3NzY0ODI=',
 'tag_name': 'v0.18.0rc2',
 'target_commitish': 'master',
 'name': 'v0.18.0rc2',
 'draft': False,
 'immutable': False,
 'prerelease': True,
 'created_at': '2016-03-09T14:38:21Z',
 'updated_at': '2016-03-09T14:57:40Z',
 'published_at': '2016-03-09T14:47:45Z',
 'assets': [],
 'tarball_url': 'https://api.github.com/repos/pandas-dev/pandas/tarball/v0.18.0rc2',
 'zipball_url': 'https://api.github.com/repos/pandas-dev/pandas/zipball/v0.18.0rc2',
 'body': '**RELEASE CANDIDATE 2**\n\nTHIS IS NOT A PRODUCTION RELEASE\n\nCompared to RC1, this includes the update to `read_sas` as well as fixes for float indexing.\n\nThis is a major release from 0.17.1 and includes a small number of API changes, several new features,\nenhancements, and performance improvements along with a large number of bug fixes. We recommend that all\nusers upgrade to this version.\n\nHighlights include:\n-  pandas >= 0.18.0 will no longer support compatibility with Python version 2.6 [GH11273](https://github.com/pydata/pandas/issues/11273) and 3.3 [GH7718](https://github.com/pydata/pandas/issues/7718)\n- Moving and expanding window functions are now methods on Series and DataFrame, similar to `.groupby`, see [here](http://pandas-docs.github.io/pandas-docs-travis/whatsnew.html#whatsnew-0180-enhancements-moments).\n- Adding support for a `RangeIndex` as a specialized form of the `Int64Index`\n  for memory savings, see [here](http://pandas-docs.github.io/pandas-docs-travis/whatsnew.html#whatsnew-0180-enhancements-rangeindex).\n- API breaking `.resample` changes to make it more `.groupby` like, see [here](http://pandas-docs.github.io/pandas-docs-travis/whatsnew.html#whatsnew-0180-breaking-resample)\n- Removal of support for positional indexing with floats, which was deprecated since 0.14.0. This will now raise a `TypeError`, see [here](http://pandas-docs.github.io/pandas-docs-travis/whatsnew.html#whatsnew-0180-float-indexers)\n- The `.to_xarray()` function has been added for compatibility with the [xarray package](http://xarray.pydata.org/en/stable/) see [here](http://pandas-docs.github.io/pandas-docs-travis/whatsnew.html#whatsnew-0180-enhancements-xarray).\n- The `read_sas()` function has been enhanced to read `sas7bdat` files, see [here](http://pandas-docs.github.io/pandas-docs-travis/whatsnew.html#whatsnew-0180-enhancements-sas)\n- Addition of the [.str.extractall() method](http://pandas-docs.github.io/pandas-docs-travis/whatsnew.html#whatsnew-0180-enhancements-extractall), and API changes to the the [.str.extract() method](http://pandas-docs.github.io/pandas-docs-travis/whatsnew.html#whatsnew-0180-enhancements-extract), and the[.str.cat() method](http://pandas-docs.github.io/pandas-docs-travis/whatsnew.html#whatsnew-0180-enhancements-strcat)\n- `pd.test()` top-level nose test runner is available [GH4327](https://github.com/pydata/pandas/issues/4327)\n\nSee the [Whatsnew](http://pandas-docs.github.io/pandas-docs-travis/whatsnew.html) for much more information. Please report any issues [here](https://github.com/pydata/pandas/issues/)\n\nbest way to get this is to install via [conda](http://pandas-docs.github.io/pandas-docs-travis/install.html#installing-pandas-with-anaconda) from our development channel. Builds for `osx-64,linux-64,win-64` for `Python 2.7 and Python 3.5` are all available.\n\n`conda install pandas=v0.18.0rc2 -c pandas`\n'}

The default page is `1`, you can get the 2nd page by passing the `page` query parameter.

In [17]:
response = requests.get("https://api.github.com/repos/pandas-dev/pandas/releases?per_page=100&page=2", 
                        headers={"Accept": "application/vnd.github+json", "Authorization": f"Bearer {access_token}"})

In [16]:
releases_page_2_100 = response.json()

In [17]:
len(releases_page_2_100)

100


We're interested in the following fields and want to save them into a dataframe:

- `tag_name`: The version name/number of the release.
- `published_at`: The date and time when the release was published.
- `body`: The release notes.

In [18]:
import pandas as pd

In [19]:
releases_with_essential_fields = [{"version": release["tag_name"], "published_at": release["published_at"], "summary": release["body"]} for release in releases_page_1_100]

In [21]:
pandas_releases = pd.DataFrame(releases_with_essential_fields)

pandas_releases

,version,published_at,summary
0,v3.0.3,2026-05-11T18:23:29Z,We are pleased to announce the release of pand...
1,v3.0.2,2026-03-30T20:14:45Z,We are pleased to announce the release of pand...
2,v3.0.1,2026-02-17T21:56:03Z,We are pleased to announce the release of pand...
3,v3.0.0,2026-01-21T15:23:43Z,We are pleased to announce the release of pand...
4,v3.0.0rc2,2026-01-14T22:17:15Z,
...,...,...,...
95,v0.19.0,2016-10-02T14:17:50Z,This is a major release from 0.18.1 and includ...
96,v0.19.0rc1,2016-09-07T20:50:22Z,**RELEASE CANDIDATE**\n\nThis is a major relea...
97,v0.18.1,2016-05-03T14:48:48Z,This is a minor release from 0.18.0 and includ...
98,v0.18.0,2016-03-12T15:12:32Z,This is a major release from 0.17.1 and includ...
99,v0.18.0rc2,2016-03-09T14:47:45Z,**RELEASE CANDIDATE 2**\n\nTHIS IS NOT A PRODU...

In [27]:
pandas_releases.dtypes

version                      object
published_at    datetime64[ns, UTC]
summary                      object
dtype: object

In [22]:
# convert `published_at` to the correct datetime format
pandas_releases['published_at'] = pd.to_datetime(pandas_releases['published_at'])

> What is the average interval (duration or differences in time) for pandas' releases (in no of days)?
>
> Hint 1: Sort the dataframe by `published_at` in ascending order.
> 
> Hint 2: Use [diff()](https://pandas.pydata.org/docs/reference/api/pandas.Series.diff.html) to calculate the time deltas between each `published_at`.
>
> Refer to [Time deltas](https://pandas.pydata.org/pandas-docs/stable/user_guide/timedeltas.html#time-deltas) for more info.

> Print the `summary` of the first (1.0.0) and second (2.0.0) major releases of pandas.

In [40]:
pandas_releases = pandas_releases.sort_values('published_at')

pandas_releases['time_since_last_relesae'] = pandas_releases['published_at'].diff()
pandas_releases.iloc[0:20]

,version,published_at,summary,time_since_last_relesae
99,v0.18.0rc2,2016-03-09 14:47:45+00:00,**RELEASE CANDIDATE 2**\n\nTHIS IS NOT A PRODU...,NaT
98,v0.18.0,2016-03-12 15:12:32+00:00,This is a major release from 0.17.1 and includ...,3 days 00:24:47
97,v0.18.1,2016-05-03 14:48:48+00:00,This is a minor release from 0.18.0 and includ...,51 days 23:36:16
96,v0.19.0rc1,2016-09-07 20:50:22+00:00,**RELEASE CANDIDATE**\n\nThis is a major relea...,127 days 06:01:34
95,v0.19.0,2016-10-02 14:17:50+00:00,This is a major release from 0.18.1 and includ...,24 days 17:27:28
94,v0.19.1,2016-11-03 15:29:59+00:00,This is a minor bug-fix release from 0.19.0 an...,32 days 01:12:09
93,v0.19.2,2016-12-24 16:47:17+00:00,This is a minor bug-fix release in the 0.19.x ...,51 days 01:17:18
92,v0.20.0rc1,2017-04-22 03:56:17+00:00,**RELEASE CANDIDATE 1**\r\n\r\nThis is a major...,118 days 11:09:00
91,v0.20.0rc2,2017-05-04 15:10:30+00:00,**RELEASE CANDIDATE 2**\r\n\r\nThis is a major...,12 days 11:14:13
90,v0.20.0,2017-05-05 02:37:00+00:00,This is a major release from 0.19.2 and includ...,0 days 11:26:30
89,v0.20.1,2017-05-05 17:16:07+00:00,This is a minor release from 0.20.0 and includ...,0 days 14:39:07
88,v0.20.2,2017-06-04 20:58:57+00:00,This is a minor bug-fix release in the 0.20.x ...,30 days 03:42:50
87,v0.20.3,2017-07-07 17:29:47+00:00,This is a minor bug-fix release in the 0.20.x ...,32 days 20:30:50
86,v0.21.0rc1,2017-10-13 02:34:39+00:00,This is a major release from 0.20.3 and includ...,97 days 09:04:52
85,v0.21.0,2017-10-27 16:09:16+00:00,This is a major release from 0.20.3 and includ...,14 days 13:34:37
84,v0.21.1,2017-12-12 12:43:30+00:00,This is a minor bug-fix release in the 0.21.x ...,45 days 20:34:14
83,v0.22.0,2017-12-30 20:06:10+00:00,This is a major release from 0.21.1 and includ...,18 days 07:22:40
82,v0.23.0rc1,2018-05-02 11:32:47+00:00,*This is the first release candidate for panda...,122 days 15:26:37
81,v0.23.0rc2,2018-05-02 14:50:28+00:00,*This is the first public release candidate fo...,0 days 03:17:41
80,v0.23.0,2018-05-15 20:23:25+00:00,This is a major release from 0.22.0 and includ...,13 days 05:32:57

Let's write the dataframe to a table in DuckDB.

First, we need to import the required libraries and get the absolute path of the project.

In [41]:
import sqlalchemy as sqla
import os 

parent_dir = os.path.abspath(os.path.pardir)

In [42]:
parent_dir

'/home/nainar/5m-data-2.4-data-extraction-scraping'

In [43]:
engine = sqla.create_engine(f'duckdb:///{parent_dir}/output/unit-2-3.db')

In [44]:
try:
    pandas_releases.to_sql("pandas_releases", engine)
    print("DataFrame successfully written to the database.")
except Exception as e:
    print(f"{e}")

DataFrame successfully written to the database.

/tmp/ipykernel_3349/2598590139.py:2: UserWarning: the 'timedelta' type is not supported, and will be written as integer values (ns frequency) to the database.
  pandas_releases.to_sql("pandas_releases", engine)

In [45]:
# Safely dispose of the engine and close all connections
# You can only use dbeaver or dbgate to access this table after engine.dispose().
engine.dispose()

Let's use another resource (endpoint) now. There are many active contributors to the pandas library, and suppose we want to know how many commits each contributor has contributed. We can retrieve the data using the `stats/contributors` endpoint.

More info on the endpoint can be found [here](https://docs.github.com/en/rest/metrics/statistics?apiVersion=2022-11-28).

In [46]:
response = requests.get("https://api.github.com/repos/pandas-dev/pandas/stats/contributors", 
                        headers={"Accept": "application/vnd.github+json", "Authorization": f"Bearer {access_token}"})

In [47]:
response.status_code

200

In [48]:
contributors = response.json()

In [49]:
type(contributors)

list

In [51]:
len(contributors)

100

In [54]:
contributors[0]

{'total': 21,
 'weeks': [{'w': 1248566400, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1249171200, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1249776000, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1250380800, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1250985600, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1251590400, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1252195200, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1252800000, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1253404800, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1254009600, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1254614400, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1255219200, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1255824000, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1256428800, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1257033600, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1257638400, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1258243200, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1258848000, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1259452800, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1260057600, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1260662400, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1261267200, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1261872000, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1262476800, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1263081600, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1263686400, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1264291200, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1264896000, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1265500800, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1266105600, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1266710400, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1267315200, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1267920000, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1268524800, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1269129600, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1269734400, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1270339200, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1270944000, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1271548800, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1272153600, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1272758400, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1273363200, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1273968000, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1274572800, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1275177600, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1275782400, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1276387200, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1276992000, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1277596800, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1278201600, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1278806400, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1279411200, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1280016000, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1280620800, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1281225600, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1281830400, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1282435200, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1283040000, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1283644800, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1284249600, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1284854400, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1285459200, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1286064000, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1286668800, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1287273600, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1287878400, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1288483200, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1289088000, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1289692800, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1290297600, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1290902400, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1291507200, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1292112000, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1292716800, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1293321600, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1293926400, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1294531200, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1295136000, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1295740800, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1296345600, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1296950400, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1297555200, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1298160000, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1298764800, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1299369600, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1299974400, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1300579200, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1301184000, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1301788800, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1302393600, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1302998400, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1303603200, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1304208000, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1304812800, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1305417600, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1306022400, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1306627200, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1307232000, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1307836800, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1308441600, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1309046400, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1309651200, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1310256000, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1310860800, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1311465600, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1312070400, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1312675200, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1313280000, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1313884800, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1314489600, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1315094400, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1315699200, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1316304000, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1316908800, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1317513600, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1318118400, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1318723200, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1319328000, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1319932800, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1320537600, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1321142400, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1321747200, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1322352000, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1322956800, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1323561600, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1324166400, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1324771200, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1325376000, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1325980800, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1326585600, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1327190400, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1327795200, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1328400000, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1329004800, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1329609600, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1330214400, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1330819200, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1331424000, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1332028800, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1332633600, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1333238400, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1333843200, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1334448000, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1335052800, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1335657600, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1336262400, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1336867200, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1337472000, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1338076800, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1338681600, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1339286400, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1339891200, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1340496000, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1341100800, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1341705600, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1342310400, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1342915200, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1343520000, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1344124800, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1344729600, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1345334400, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1345939200, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1346544000, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1347148800, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1347753600, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1348358400, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1348963200, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1349568000, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1350172800, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1350777600, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1351382400, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1351987200, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1352592000, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1353196800, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1353801600, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1354406400, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1355011200, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1355616000, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1356220800, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1356825600, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1357430400, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1358035200, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1358640000, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1359244800, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1359849600, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1360454400, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1361059200, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1361664000, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1362268800, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1362873600, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1363478400, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1364083200, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1364688000, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1365292800, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1365897600, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1366502400, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1367107200, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1367712000, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1368316800, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1368921600, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1369526400, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1370131200, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1370736000, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1371340800, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1371945600, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1372550400, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1373155200, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1373760000, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1374364800, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1374969600, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1375574400, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1376179200, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1376784000, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1377388800, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1377993600, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1378598400, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1379203200, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1379808000, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1380412800, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1381017600, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1381622400, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1382227200, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1382832000, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1383436800, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1384041600, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1384646400, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1385251200, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1385856000, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1386460800, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1387065600, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1387670400, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1388275200, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1388880000, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1389484800, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1390089600, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1390694400, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1391299200, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1391904000, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1392508800, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1393113600, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1393718400, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1394323200, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1394928000, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1395532800, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1396137600, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1396742400, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1397347200, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1397952000, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1398556800, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1399161600, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1399766400, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1400371200, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1400976000, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1401580800, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1402185600, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1402790400, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1403395200, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1404000000, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1404604800, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1405209600, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1405814400, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1406419200, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1407024000, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1407628800, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1408233600, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1408838400, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1409443200, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1410048000, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1410652800, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1411257600, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1411862400, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1412467200, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1413072000, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1413676800, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1414281600, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1414886400, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1415491200, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1416096000, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1416700800, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1417305600, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1417910400, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1418515200, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1419120000, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1419724800, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1420329600, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1420934400, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1421539200, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1422144000, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1422748800, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1423353600, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1423958400, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1424563200, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1425168000, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1425772800, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1426377600, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1426982400, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1427587200, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1428192000, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1428796800, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1429401600, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1430006400, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1430611200, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1431216000, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1431820800, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1432425600, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1433030400, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1433635200, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1434240000, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1434844800, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1435449600, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1436054400, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1436659200, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1437264000, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1437868800, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1438473600, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1439078400, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1439683200, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1440288000, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1440892800, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1441497600, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1442102400, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1442707200, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1443312000, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1443916800, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1444521600, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1445126400, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1445731200, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1446336000, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1446940800, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1447545600, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1448150400, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1448755200, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1449360000, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1449964800, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1450569600, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1451174400, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1451779200, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1452384000, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1452988800, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1453593600, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1454198400, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1454803200, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1455408000, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1456012800, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1456617600, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1457222400, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1457827200, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1458432000, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1459036800, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1459641600, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1460246400, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1460851200, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1461456000, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1462060800, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1462665600, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1463270400, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1463875200, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1464480000, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1465084800, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1465689600, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1466294400, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1466899200, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1467504000, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1468108800, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1468713600, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1469318400, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1469923200, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1470528000, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1471132800, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1471737600, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1472342400, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1472947200, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1473552000, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1474156800, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1474761600, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1475366400, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1475971200, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1476576000, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1477180800, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1477785600, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1478390400, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1478995200, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1479600000, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1480204800, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1480809600, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1481414400, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1482019200, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1482624000, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1483228800, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1483833600, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1484438400, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1485043200, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1485648000, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1486252800, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1486857600, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1487462400, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1488067200, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1488672000, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1489276800, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1489881600, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1490486400, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1491091200, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1491696000, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1492300800, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1492905600, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1493510400, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1494115200, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1494720000, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1495324800, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1495929600, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1496534400, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1497139200, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1497744000, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1498348800, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1498953600, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1499558400, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1500163200, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1500768000, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1501372800, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1501977600, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1502582400, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1503187200, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1503792000, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1504396800, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1505001600, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1505606400, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1506211200, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1506816000, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1507420800, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1508025600, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1508630400, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1509235200, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1509840000, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1510444800, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1511049600, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1511654400, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1512259200, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1512864000, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1513468800, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1514073600, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1514678400, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1515283200, 'a': 0, 'd': 0, 'c': 0},
  {'w': 1515888000, 'a': 0, 'd': 0, 'c': 0},

In [53]:
contributors[0]['weeks']

[{'w': 1248566400, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1249171200, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1249776000, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1250380800, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1250985600, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1251590400, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1252195200, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1252800000, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1253404800, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1254009600, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1254614400, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1255219200, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1255824000, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1256428800, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1257033600, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1257638400, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1258243200, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1258848000, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1259452800, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1260057600, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1260662400, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1261267200, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1261872000, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1262476800, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1263081600, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1263686400, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1264291200, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1264896000, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1265500800, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1266105600, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1266710400, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1267315200, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1267920000, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1268524800, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1269129600, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1269734400, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1270339200, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1270944000, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1271548800, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1272153600, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1272758400, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1273363200, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1273968000, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1274572800, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1275177600, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1275782400, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1276387200, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1276992000, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1277596800, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1278201600, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1278806400, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1279411200, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1280016000, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1280620800, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1281225600, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1281830400, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1282435200, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1283040000, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1283644800, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1284249600, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1284854400, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1285459200, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1286064000, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1286668800, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1287273600, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1287878400, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1288483200, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1289088000, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1289692800, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1290297600, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1290902400, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1291507200, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1292112000, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1292716800, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1293321600, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1293926400, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1294531200, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1295136000, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1295740800, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1296345600, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1296950400, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1297555200, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1298160000, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1298764800, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1299369600, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1299974400, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1300579200, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1301184000, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1301788800, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1302393600, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1302998400, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1303603200, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1304208000, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1304812800, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1305417600, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1306022400, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1306627200, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1307232000, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1307836800, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1308441600, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1309046400, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1309651200, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1310256000, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1310860800, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1311465600, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1312070400, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1312675200, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1313280000, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1313884800, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1314489600, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1315094400, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1315699200, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1316304000, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1316908800, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1317513600, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1318118400, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1318723200, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1319328000, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1319932800, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1320537600, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1321142400, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1321747200, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1322352000, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1322956800, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1323561600, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1324166400, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1324771200, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1325376000, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1325980800, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1326585600, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1327190400, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1327795200, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1328400000, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1329004800, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1329609600, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1330214400, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1330819200, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1331424000, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1332028800, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1332633600, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1333238400, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1333843200, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1334448000, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1335052800, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1335657600, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1336262400, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1336867200, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1337472000, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1338076800, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1338681600, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1339286400, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1339891200, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1340496000, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1341100800, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1341705600, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1342310400, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1342915200, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1343520000, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1344124800, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1344729600, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1345334400, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1345939200, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1346544000, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1347148800, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1347753600, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1348358400, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1348963200, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1349568000, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1350172800, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1350777600, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1351382400, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1351987200, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1352592000, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1353196800, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1353801600, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1354406400, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1355011200, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1355616000, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1356220800, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1356825600, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1357430400, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1358035200, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1358640000, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1359244800, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1359849600, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1360454400, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1361059200, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1361664000, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1362268800, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1362873600, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1363478400, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1364083200, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1364688000, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1365292800, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1365897600, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1366502400, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1367107200, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1367712000, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1368316800, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1368921600, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1369526400, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1370131200, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1370736000, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1371340800, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1371945600, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1372550400, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1373155200, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1373760000, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1374364800, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1374969600, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1375574400, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1376179200, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1376784000, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1377388800, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1377993600, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1378598400, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1379203200, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1379808000, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1380412800, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1381017600, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1381622400, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1382227200, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1382832000, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1383436800, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1384041600, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1384646400, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1385251200, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1385856000, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1386460800, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1387065600, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1387670400, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1388275200, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1388880000, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1389484800, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1390089600, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1390694400, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1391299200, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1391904000, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1392508800, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1393113600, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1393718400, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1394323200, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1394928000, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1395532800, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1396137600, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1396742400, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1397347200, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1397952000, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1398556800, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1399161600, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1399766400, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1400371200, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1400976000, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1401580800, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1402185600, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1402790400, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1403395200, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1404000000, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1404604800, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1405209600, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1405814400, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1406419200, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1407024000, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1407628800, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1408233600, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1408838400, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1409443200, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1410048000, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1410652800, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1411257600, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1411862400, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1412467200, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1413072000, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1413676800, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1414281600, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1414886400, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1415491200, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1416096000, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1416700800, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1417305600, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1417910400, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1418515200, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1419120000, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1419724800, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1420329600, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1420934400, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1421539200, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1422144000, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1422748800, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1423353600, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1423958400, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1424563200, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1425168000, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1425772800, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1426377600, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1426982400, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1427587200, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1428192000, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1428796800, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1429401600, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1430006400, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1430611200, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1431216000, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1431820800, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1432425600, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1433030400, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1433635200, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1434240000, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1434844800, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1435449600, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1436054400, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1436659200, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1437264000, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1437868800, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1438473600, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1439078400, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1439683200, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1440288000, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1440892800, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1441497600, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1442102400, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1442707200, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1443312000, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1443916800, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1444521600, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1445126400, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1445731200, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1446336000, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1446940800, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1447545600, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1448150400, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1448755200, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1449360000, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1449964800, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1450569600, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1451174400, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1451779200, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1452384000, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1452988800, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1453593600, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1454198400, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1454803200, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1455408000, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1456012800, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1456617600, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1457222400, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1457827200, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1458432000, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1459036800, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1459641600, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1460246400, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1460851200, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1461456000, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1462060800, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1462665600, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1463270400, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1463875200, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1464480000, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1465084800, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1465689600, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1466294400, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1466899200, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1467504000, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1468108800, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1468713600, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1469318400, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1469923200, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1470528000, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1471132800, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1471737600, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1472342400, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1472947200, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1473552000, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1474156800, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1474761600, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1475366400, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1475971200, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1476576000, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1477180800, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1477785600, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1478390400, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1478995200, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1479600000, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1480204800, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1480809600, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1481414400, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1482019200, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1482624000, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1483228800, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1483833600, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1484438400, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1485043200, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1485648000, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1486252800, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1486857600, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1487462400, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1488067200, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1488672000, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1489276800, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1489881600, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1490486400, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1491091200, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1491696000, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1492300800, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1492905600, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1493510400, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1494115200, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1494720000, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1495324800, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1495929600, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1496534400, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1497139200, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1497744000, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1498348800, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1498953600, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1499558400, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1500163200, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1500768000, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1501372800, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1501977600, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1502582400, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1503187200, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1503792000, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1504396800, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1505001600, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1505606400, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1506211200, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1506816000, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1507420800, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1508025600, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1508630400, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1509235200, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1509840000, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1510444800, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1511049600, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1511654400, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1512259200, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1512864000, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1513468800, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1514073600, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1514678400, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1515283200, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1515888000, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1516492800, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1517097600, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1517702400, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1518307200, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1518912000, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1519516800, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1520121600, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1520726400, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1521331200, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1521936000, 'a': 0, 'd': 0, 'c': 0},
 {'w': 1522540800, 'a': 0, 'd': 0, 'c': 0},

In [56]:
contributors[0]["total"]

21

> Get the `total` and `login` (under `author`) fields and insert them into a dataframe. Then find out who has the most number of commits.
>
> Then, write the dataframe into a table named `pandas_contributors_commits` in duckdb.

In [ ]:
contributors_with_essential_fields = [{ "login": contributor["author"]["login"], "total": contributor["total"]} for contributor in contributors]
contributors_with_essential_fields

In [60]:
pandas_contributors_commits = pd.DataFrame(contributors_with_essential_fields)
pandas_contributors_commits

                 login  total
0           ryankarlos     21
1             noatamir     21
2                moink     21
3              ganevgv     22
4              minggli     22
..                 ...    ...
95  jorisvandenbossche   1735
96           mroeschke   1951
97                wesm   3129
98             jreback   4794
99        jbrockmendel   5412

[100 rows x 2 columns]

In [61]:
engine = sqla.create_engine(f'duckdb:///{parent_dir}/output/unit-2-3.db')

In [62]:
try:
    pandas_contributors_commits.to_sql("pandas_contributors_commits", engine)
    print("DataFrame successfully written to the database.")
except Exception as e:
    print(f"{e}")

DataFrame successfully written to the database.

In [63]:
engine.dispose()

## GraphQL

Github offers a new way to access its data, which is the GraphQL API. You can read more about it here: https://docs.github.com/graphql

GraphQL is introspetive, which means you can query the schema of the API itself. This is very useful when you are trying to figure out what data you can access. 

In GraphQL, to access the schema you can run the following query:

```graphql
{
  __schema {
    types {
      name
      kind
      description
    }
  }
}
```

Or to get the fields of a specific type (for example `"Release"`), you can run the following query:

```graphql
{
  __type(name: "Release") {
    name
    kind
    description
    fields {
      name
      description
    }
  }
}
```

It should return the following results (in JSON):

```json
{
  "data": {
    "__type": {
      "name": "Release",
      "kind": "OBJECT",
      "description": "A release contains the content for a release.",
      "fields": [
        {
          "name": "author",
          "description": "The author of the release"
        },
        {
          "name": "createdAt",
          "description": "Identifies the date and time when the object was created."
        },
        {
          "name": "databaseId",
          "description": "Identifies the primary key from the database."
        },
        {
          "name": "description",
          "description": "The description of the release."
        },
        {
          "name": "descriptionHTML",
          "description": "The description of this release rendered to HTML."
        },
        {
          "name": "id",
          "description": null
        },
        {
          "name": "isDraft",
          "description": "Whether or not the release is a draft"
        },
        {
          "name": "isLatest",
          "description": "Whether or not the release is the latest releast"
        },
        {
          "name": "isPrerelease",
          "description": "Whether or not the release is a prerelease"
        },
        {
          "name": "mentions",
          "description": "A list of users mentioned in the release description"
        },
        {
          "name": "name",
          "description": "The title of the release."
        },
        {
          "name": "publishedAt",
          "description": "Identifies the date and time when the release was created."
        },
        {
          "name": "reactionGroups",
          "description": "A list of reactions grouped by content left on the subject."
        },
        {
          "name": "reactions",
          "description": "A list of Reactions left on the Issue."
        },
        {
          "name": "releaseAssets",
          "description": "List of releases assets which are dependent on this release."
        },
        {
          "name": "repository",
          "description": "The repository that the release belongs to."
        },
        {
          "name": "resourcePath",
          "description": "The HTTP path for this issue"
        },
        {
          "name": "shortDescriptionHTML",
          "description": "A description of the release, rendered to HTML without any links in it."
        },
        {
          "name": "tag",
          "description": "The Git tag the release points to"
        },
        {
          "name": "tagCommit",
          "description": "The tag commit for this release."
        },
        {
          "name": "tagName",
          "description": "The name of the release's Git tag"
        },
        {
          "name": "updatedAt",
          "description": "Identifies the date and time when the object was last updated."
        },
        {
          "name": "url",
          "description": "The HTTP URL for this issue"
        },
        {
          "name": "viewerCanReact",
          "description": "Can user react to this subject"
        }
      ]
    }
  }
}
```

Follow the guide [here](https://docs.github.com/en/graphql/guides/introduction-to-graphql#discovering-the-graphql-api) for more info.

In [64]:
# Feel free to test the query below - below query is to access the schema
query = """
query {
  __schema {
    types {
      name
      kind
      description
    }
  }
}
"""
            
response = requests.post("https://api.github.com/graphql", 
                        headers={"Authorization": f"Bearer {access_token}"}, json={"query": query})
response.json()

{'data': {'__schema': {'types': [{'name': 'AbortQueuedMigrationsInput',
     'kind': 'INPUT_OBJECT',
     'description': 'Autogenerated input type of AbortQueuedMigrations'},
    {'name': 'AbortQueuedMigrationsPayload',
     'kind': 'OBJECT',
     'description': 'Autogenerated return type of AbortQueuedMigrations.'},
    {'name': 'AbortRepositoryMigrationInput',
     'kind': 'INPUT_OBJECT',
     'description': 'Autogenerated input type of AbortRepositoryMigration'},
    {'name': 'AbortRepositoryMigrationPayload',
     'kind': 'OBJECT',
     'description': 'Autogenerated return type of AbortRepositoryMigration.'},
    {'name': 'AcceptEnterpriseAdministratorInvitationInput',
     'kind': 'INPUT_OBJECT',
     'description': 'Autogenerated input type of AcceptEnterpriseAdministratorInvitation'},
    {'name': 'AcceptEnterpriseAdministratorInvitationPayload',
     'kind': 'OBJECT',
     'description': 'Autogenerated return type of AcceptEnterpriseAdministratorInvitation.'},
    {'name': 'AcceptEnterpriseMemberInvitationInput',
     'kind': 'INPUT_OBJECT',
     'description': 'Autogenerated input type of AcceptEnterpriseMemberInvitation'},
    {'name': 'AcceptEnterpriseMemberInvitationPayload',
     'kind': 'OBJECT',
     'description': 'Autogenerated return type of AcceptEnterpriseMemberInvitation.'},
    {'name': 'AcceptTopicSuggestionInput',
     'kind': 'INPUT_OBJECT',
     'description': 'Autogenerated input type of AcceptTopicSuggestion'},
    {'name': 'AcceptTopicSuggestionPayload',
     'kind': 'OBJECT',
     'description': 'Autogenerated return type of AcceptTopicSuggestion.'},
    {'name': 'AccessUserNamespaceRepositoryInput',
     'kind': 'INPUT_OBJECT',
     'description': 'Autogenerated input type of AccessUserNamespaceRepository'},
    {'name': 'AccessUserNamespaceRepositoryPayload',
     'kind': 'OBJECT',
     'description': 'Autogenerated return type of AccessUserNamespaceRepository.'},
    {'name': 'Actor',
     'kind': 'INTERFACE',
     'description': 'Represents an object which can take actions on GitHub. Typically a User or Bot.'},
    {'name': 'ActorConnection',
     'kind': 'OBJECT',
     'description': 'The connection type for Actor.'},
    {'name': 'ActorEdge',
     'kind': 'OBJECT',
     'description': 'An edge in a connection.'},
    {'name': 'ActorLocation',
     'kind': 'OBJECT',
     'description': 'Location information for an actor'},
    {'name': 'ActorType', 'kind': 'ENUM', 'description': "The actor's type."},
    {'name': 'AddAssigneesToAssignableInput',
     'kind': 'INPUT_OBJECT',
     'description': 'Autogenerated input type of AddAssigneesToAssignable'},
    {'name': 'AddAssigneesToAssignablePayload',
     'kind': 'OBJECT',
     'description': 'Autogenerated return type of AddAssigneesToAssignable.'},
    {'name': 'AddBlockedByInput',
     'kind': 'INPUT_OBJECT',
     'description': 'Autogenerated input type of AddBlockedBy'},
    {'name': 'AddBlockedByPayload',
     'kind': 'OBJECT',
     'description': 'Autogenerated return type of AddBlockedBy.'},
    {'name': 'AddCommentInput',
     'kind': 'INPUT_OBJECT',
     'description': 'Autogenerated input type of AddComment'},
    {'name': 'AddCommentPayload',
     'kind': 'OBJECT',
     'description': 'Autogenerated return type of AddComment.'},
    {'name': 'AddDiscussionCommentInput',
     'kind': 'INPUT_OBJECT',
     'description': 'Autogenerated input type of AddDiscussionComment'},
    {'name': 'AddDiscussionCommentPayload',
     'kind': 'OBJECT',
     'description': 'Autogenerated return type of AddDiscussionComment.'},
    {'name': 'AddDiscussionPollVoteInput',
     'kind': 'INPUT_OBJECT',
     'description': 'Autogenerated input type of AddDiscussionPollVote'},
    {'name': 'AddDiscussionPollVotePayload',
     'kind': 'OBJECT',
     'description': 'Autogenerated return type of AddDiscussionPollVote.'},
    {'name': 'AddEnterpriseOrganizationMemberInput',
     'kind': 'INPUT_OBJECT',
     'description': 'Autogenerated input type of AddEnterpriseOrganizationMember'},
    {'name': 'AddEnterpriseOrganizationMemberPayload',
     'kind': 'OBJECT',
     'description': 'Autogenerated return type of AddEnterpriseOrganizationMember.'},
    {'name': 'AddEnterpriseSupportEntitlementInput',
     'kind': 'INPUT_OBJECT',
     'description': 'Autogenerated input type of AddEnterpriseSupportEntitlement'},
    {'name': 'AddEnterpriseSupportEntitlementPayload',
     'kind': 'OBJECT',
     'description': 'Autogenerated return type of AddEnterpriseSupportEntitlement.'},
    {'name': 'AddLabelsToLabelableInput',
     'kind': 'INPUT_OBJECT',
     'description': 'Autogenerated input type of AddLabelsToLabelable'},
    {'name': 'AddLabelsToLabelablePayload',
     'kind': 'OBJECT',
     'description': 'Autogenerated return type of AddLabelsToLabelable.'},
    {'name': 'AddProjectCardInput',
     'kind': 'INPUT_OBJECT',
     'description': 'Autogenerated input type of AddProjectCard'},
    {'name': 'AddProjectCardPayload',
     'kind': 'OBJECT',
     'description': 'Autogenerated return type of AddProjectCard.'},
    {'name': 'AddProjectColumnInput',
     'kind': 'INPUT_OBJECT',
     'description': 'Autogenerated input type of AddProjectColumn'},
    {'name': 'AddProjectColumnPayload',
     'kind': 'OBJECT',
     'description': 'Autogenerated return type of AddProjectColumn.'},
    {'name': 'AddProjectV2DraftIssueInput',
     'kind': 'INPUT_OBJECT',
     'description': 'Autogenerated input type of AddProjectV2DraftIssue'},
    {'name': 'AddProjectV2DraftIssuePayload',
     'kind': 'OBJECT',
     'description': 'Autogenerated return type of AddProjectV2DraftIssue.'},
    {'name': 'AddProjectV2ItemByIdInput',
     'kind': 'INPUT_OBJECT',
     'description': 'Autogenerated input type of AddProjectV2ItemById'},
    {'name': 'AddProjectV2ItemByIdPayload',
     'kind': 'OBJECT',
     'description': 'Autogenerated return type of AddProjectV2ItemById.'},
    {'name': 'AddPullRequestReviewCommentInput',
     'kind': 'INPUT_OBJECT',
     'description': 'Autogenerated input type of AddPullRequestReviewComment'},
    {'name': 'AddPullRequestReviewCommentPayload',
     'kind': 'OBJECT',
     'description': 'Autogenerated return type of AddPullRequestReviewComment.'},
    {'name': 'AddPullRequestReviewInput',
     'kind': 'INPUT_OBJECT',
     'description': 'Autogenerated input type of AddPullRequestReview'},
    {'name': 'AddPullRequestReviewPayload',
     'kind': 'OBJECT',
     'description': 'Autogenerated return type of AddPullRequestReview.'},
    {'name': 'AddPullRequestReviewThreadInput',
     'kind': 'INPUT_OBJECT',
     'description': 'Autogenerated input type of AddPullRequestReviewThread'},
    {'name': 'AddPullRequestReviewThreadPayload',
     'kind': 'OBJECT',
     'description': 'Autogenerated return type of AddPullRequestReviewThread.'},
    {'name': 'AddPullRequestReviewThreadReplyInput',
     'kind': 'INPUT_OBJECT',
     'description': 'Autogenerated input type of AddPullRequestReviewThreadReply'},
    {'name': 'AddPullRequestReviewThreadReplyPayload',
     'kind': 'OBJECT',
     'description': 'Autogenerated return type of AddPullRequestReviewThreadReply.'},
    {'name': 'AddReactionInput',
     'kind': 'INPUT_OBJECT',
     'description': 'Autogenerated input type of AddReaction'},
    {'name': 'AddReactionPayload',
     'kind': 'OBJECT',
     'description': 'Autogenerated return type of AddReaction.'},
    {'name': 'AddStarInput',
     'kind': 'INPUT_OBJECT',
     'description': 'Autogenerated input type of AddStar'},
    {'name': 'AddStarPayload',
     'kind': 'OBJECT',
     'description': 'Autogenerated return type of AddStar.'},
    {'name': 'AddSubIssueInput',
     'kind': 'INPUT_OBJECT',
     'description': 'Autogenerated input type of AddSubIssue'},
    {'name': 'AddSubIssuePayload',
     'kind': 'OBJECT',
     'description': 'Autogenerated return type of AddSubIssue.'},
    {'name': 'AddUpvoteInput',
     'kind': 'INPUT_OBJECT',
     'description': 'Autogenerated input type of AddUpvote'},
    {'name': 'AddUpvotePayload',
     'kind': 'OBJECT',
     'description': 'Autogenerated return type of AddUpvote.'},
    {'name': 'AddVerifiableDomainInput',
     'kind': 'INPUT_OBJECT',
     'description': 'Autogenerated input type of AddVerifiableDomain'},
    {'name': 'AddVerifiableDomainPayload',
     'kind': 'OBJECT',
     'description': 'Autogenerated return type of AddVerifiableDomain.'},
    {'name': 'AddedToMergeQueueEvent',
     'kind': 'OBJECT',
     'description': "Represents an 'added_to_merge_queue' event on a given pull request."},
    {'name': 'AddedToProjectEvent',
     'kind': 'OBJECT',
     'description': "Represents a 'added_to_project' event on a given issue or pull request."},
    {'name': 'AddedToProjectV2Event',
     'kind': 'OBJECT',
     'description': "Represents a 'added_to_project_v2' event on a given issue or pull request."},
    {'name': 'AgentAssignmentInput',
     'kind': 'INPUT_OBJECT',
     'description': 'Represents configuration for assigning Copilot to an issue (public variant)'},
    {'name': 'Agentic',
     'kind': 'INTERFACE',
     'description': 'Copilot Agentic fields in context of the current viewer.'},
    {'name': 'AnnouncementBanner',
     'kind': 'OBJECT',
     'description': 'An announcement banner for an enterprise or organization.'},
    {'name': 'App', 'kind': 'OBJECT', 'description': 'A GitHub App.'},
    {'name': 'ApproveDeploymentsInput',
     'kind': 'INPUT_OBJECT',
     'description': 'Autogenerated input type of ApproveDeployments'},
    {'name': 'ApproveDeploymentsPayload',
     'kind': 'OBJECT',
     'description': 'Autogenerated return type of ApproveDeployments.'},
    {'name': 'ApproveVerifiableDomainInput',
     'kind': 'INPUT_OBJECT',
     'description': 'Autogenerated input type of ApproveVerifiableDomain'},
    {'name': 'ApproveVerifiableDomainPayload',
     'kind': 'OBJECT',
     'description': 'Autogenerated return type of ApproveVerifiableDomain.'},
    {'name': 'ArchiveProjectV2ItemInput',
     'kind': 'INPUT_OBJECT',
     'description': 'Autogenerated input type of ArchiveProjectV2Item'},
    {'name': 'ArchiveProjectV2ItemPayload',
     'kind': 'OBJECT',
     'description': 'Autogenerated return type of ArchiveProjectV2Item.'},
    {'name': 'ArchivePullRequestInput',
     'kind': 'INPUT_OBJECT',
     'description': 'Autogenerated input type of ArchivePullRequest'},
    {'name': 'ArchivePullRequestPayload',
     'kind': 'OBJECT',
     'description': 'Autogenerated return type of ArchivePullRequest.'},
    {'name': 'ArchiveRepositoryInput',
     'kind': 'INPUT_OBJECT',
     'description': 'Autogenerated input type of ArchiveRepository'},
    {'name': 'ArchiveRepositoryPayload',
     'kind': 'OBJECT',
     'description': 'Autogenerated return type of ArchiveRepository.'},
    {'name': 'Assignable',
     'kind': 'INTERFACE',
     'description': 'An object that can have users assigned to it.'},
    {'name': 'AssignedEvent',
     'kind': 'OBJECT',
     'description': "Represents an 'assigned' event on any assignable object."},
    {'name': 'Assignee',
     'kind': 'UNION',
     'description': 'Types that can be assigned to issues.'},
    {'name': 'AssigneeConnection',
     'kind': 'OBJECT',
     'description': 'The connection type for Assignee.'},
    {'name': 'AssigneeEdge',
     'kind': 'OBJECT',
     'description': 'An edge in a connection.'},
    {'name': 'AuditEntry',
     'kind': 'INTERFACE',
     'description': 'An entry in the audit log.'},
    {'name': 'AuditEntryActor',
     'kind': 'UNION',
     'description': 'Types that can initiate an audit log event.'},
    {'name': 'AuditLogOrder',
     'kind': 'INPUT_OBJECT',
     'description': 'Ordering options for Audit Log connections.'},
    {'name': 'AuditLogOrderField',
     'kind': 'ENUM',
     'description': 'Properties by which Audit Log connections can be ordered.'},
    {'name': 'AutoMergeDisabledEvent',
     'kind': 'OBJECT',
     'description': "Represents a 'auto_merge_disabled' event on a given pull request."},
    {'name': 'AutoMergeEnabledEvent',
     'kind': 'OBJECT',
     'description': "Represents a 'auto_merge_enabled' event on a given pull request."},
    {'name': 'AutoMergeRequest',
     'kind': 'OBJECT',
     'description': 'Represents an auto-merge request for a pull request'},
    {'name': 'AutoRebaseEnabledEvent',
     'kind': 'OBJECT',
     'description': "Represents a 'auto_rebase_enabled' event on a given pull request."},
    {'name': 'AutoSquashEnabledEvent',
     'kind': 'OBJECT',
     'description': "Represents a 'auto_squash_enabled' event on a given pull request."},
    {'name': 'AutomaticBaseChangeFailedEvent',
     'kind': 'OBJECT',
     'description': "Represents a 'automatic_base_change_failed' event on a given pull request."},
    {'name': 'AutomaticBaseChangeSucceededEvent',
     'kind': 'OBJECT',
     'description': "Represents a 'automatic_base_change_succeeded' event on a given pull request."},
    {'name': 'Base64String',
     'kind': 'SCALAR',
     'description': 'A (potentially binary) string encoded using base64.'},
    {'name': 'BaseRefChangedEvent',
     'kind': 'OBJECT',
     'description': "Represents a 'base_ref_changed' event on a given issue or pull request."},
    {'name': 'BaseRefDeletedEvent',
     'kind': 'OBJECT',
     'description': "Represents a 'base_ref_deleted' event on a given pull request."},
    {'name': 'BaseRefForcePushedEvent',
     'kind': 'OBJECT',
     'description': "Represents a 'base_ref_force_pushed' event on a given pull request."},
    {'name': 'BigInt',
     'kind': 'SCALAR',
     'description': "Represents non-fractional signed whole numeric values. Since the value may exceed the size of a 32-bit integer, it's encoded as a string."},
    {'name': 'Blame',
     'kind': 'OBJECT',
     'description': 'Represents a Git blame.'},
    {'name': 'BlameRange',
     'kind': 'OBJECT',
     'description': 'Represents a range of information from a Git blame.'},
    {'name': 'Blob',
     'kind': 'OBJECT',
     'description': 'Represents a Git blob.'},
    {'name': 'BlockedByAddedEvent',
     'kind': 'OBJECT',
     'description': "Represents a 'blocked_by_added' event on a given issue."},
    {'name': 'BlockedByRemovedEvent',
     'kind': 'OBJECT',
     'description': "Represents a 'blocked_by_removed' event on a given issue."},
    {'name': 'BlockingAddedEvent',
     'kind': 'OBJECT',
     'description': "Represents a 'blocking_added' event on a given issue."},
    {'name': 'BlockingRemovedEvent',
     'kind': 'OBJECT',
     'description': "Represents a 'blocking_removed' event on a given issue."},
    {'name': 'Boolean',
     'kind': 'SCALAR',
     'description': 'Represents `true` or `false` values.'},
    {'name': 'Bot',
     'kind': 'OBJECT',
     'description': 'A special type of user which takes actions on behalf of GitHub Apps.'},
    {'name': 'BranchActorAllowanceActor',
     'kind': 'UNION',
     'description': 'Types which can be actors for `BranchActorAllowance` objects.'},
    {'name': 'BranchNamePatternParameters',
     'kind': 'OBJECT',
     'description': 'Parameters to be used for the branch_name_pattern rule'},
    {'name': 'BranchNamePatternParametersInput',
     'kind': 'INPUT_OBJECT',
     'description': 'Parameters to be used for the branch_name_pattern rule'},
    {'name': 'BranchProtectionRule',
     'kind': 'OBJECT',
     'description': 'A branch protection rule.'},
    {'name': 'BranchProtectionRuleConflict',
     'kind': 'OBJECT',
     'description': 'A conflict between two branch protection rules.'},
    {'name': 'BranchProtectionRuleConflictConnection',
     'kind': 'OBJECT',
     'description': 'The connection type for BranchProtectionRuleConflict.'},
    {'name': 'BranchProtectionRuleConflictEdge',
     'kind': 'OBJECT',
     'description': 'An edge in a connection.'},
    {'name': 'BranchProtectionRuleConnection',
     'kind': 'OBJECT',
     'description': 'The connection type for BranchProtectionRule.'},
    {'name': 'BranchProtectionRuleEdge',
     'kind': 'OBJECT',
     'description': 'An edge in a connection.'},
    {'name': 'BulkSponsorship',
     'kind': 'INPUT_OBJECT',
     'description': 'Information about a sponsorship to make for a user or organization with a GitHub Sponsors profile, as part of sponsoring many users or organizations at once.'},
    {'name': 'BypassActor',
     'kind': 'UNION',
     'description': 'Types that can represent a repository ruleset bypass actor.'},
    {'name': 'BypassForcePushAllowance',
     'kind': 'OBJECT',
     'description': 'A user, team, or app who has the ability to bypass a force push requirement on a protected branch.'},
    {'name': 'BypassForcePushAllowanceConnection',
     'kind': 'OBJECT',
     'description': 'The connection type for BypassForcePushAllowance.'},
    {'name': 'BypassForcePushAllowanceEdge',
     'kind': 'OBJECT',
     'description': 'An edge in a connection.'},
    {'name': 'BypassPullRequestAllowance',
     'kind': 'OBJECT',
     'description': 'A user, team, or app who has the ability to bypass a pull request requirement on a protected branch.'},
    {'name': 'BypassPullRequestAllowanceConnection',
     'kind': 'OBJECT',
     'description': 'The connection type for BypassPullRequestAllowance.'},
    {'name': 'BypassPullRequestAllowanceEdge',
     'kind': 'OBJECT',
     'description': 'An edge in a connection.'},
    {'name': 'CVSS',
     'kind': 'OBJECT',
     'description': 'The Common Vulnerability Scoring System'},
    {'name': 'CWE',
     'kind': 'OBJECT',
     'description': 'A common weakness enumeration'},
    {'name': 'CWEConnection',
     'kind': 'OBJECT',
     'description': 'The connection type for CWE.'},
    {'name': 'CWEEdge',
     'kind': 'OBJECT',
     'description': 'An edge in a connection.'},
    {'name': 'CancelEnterpriseAdminInvitationInput',
     'kind': 'INPUT_OBJECT',
     'description': 'Autogenerated input type of CancelEnterpriseAdminInvitation'},
    {'name': 'CancelEnterpriseAdminInvitationPayload',
     'kind': 'OBJECT',
     'description': 'Autogenerated return type of CancelEnterpriseAdminInvitation.'},
    {'name': 'CancelEnterpriseMemberInvitationInput',
     'kind': 'INPUT_OBJECT',
     'description': 'Autogenerated input type of CancelEnterpriseMemberInvitation'},
    {'name': 'CancelEnterpriseMemberInvitationPayload',
     'kind': 'OBJECT',
     'description': 'Autogenerated return type of CancelEnterpriseMemberInvitation.'},
    {'name': 'CancelSponsorshipInput',
     'kind': 'INPUT_OBJECT',
     'description': 'Autogenerated input type of CancelSponsorship'},
    {'name': 'CancelSponsorshipPayload',
     'kind': 'OBJECT',
     'description': 'Autogenerated return type of CancelSponsorship.'},
    {'name': 'ChangeUserStatusInput',
     'kind': 'INPUT_OBJECT',
     'description': 'Autogenerated input type of ChangeUserStatus'},
    {'name': 'ChangeUserStatusPayload',
     'kind': 'OBJECT',
     'description': 'Autogenerated return type of ChangeUserStatus.'},
    {'name': 'CheckAnnotation',
     'kind': 'OBJECT',
     'description': 'A single check annotation.'},
    {'name': 'CheckAnnotationConnection',
     'kind': 'OBJECT',
     'description': 'The connection type for CheckAnnotation.'},
    {'name': 'CheckAnnotationData',
     'kind': 'INPUT_OBJECT',
     'description': 'Information from a check run analysis to specific lines of code.'},
    {'name': 'CheckAnnotationEdge',
     'kind': 'OBJECT',
     'description': 'An edge in a connection.'},
    {'name': 'CheckAnnotationLevel',
     'kind': 'ENUM',
     'description': "Represents an annotation's information level."},
    {'name': 'CheckAnnotationPosition',
     'kind': 'OBJECT',
     'description': 'A character position in a check annotation.'},
    {'name': 'CheckAnnotationRange',
     'kind': 'INPUT_OBJECT',
     'description': 'Information from a check run analysis to specific lines of code.'},
    {'name': 'CheckAnnotationSpan',
     'kind': 'OBJECT',

In [65]:
# Feel free to test the query below - below query is to get the fields of a specific type (for example `"Release"`)
query = """
query {
  __type(name: "Release") {
    name
    kind
    description
    fields {
      name
      description
    }
  }
}
"""
            
response = requests.post("https://api.github.com/graphql", 
                        headers={"Authorization": f"Bearer {access_token}"}, json={"query": query})
response.json()

{'data': {'__type': {'name': 'Release',
   'kind': 'OBJECT',
   'description': 'A release contains the content for a release.',
   'fields': [{'name': 'author', 'description': 'The author of the release'},
    {'name': 'createdAt',
     'description': 'Identifies the date and time when the object was created.'},
    {'name': 'databaseId',
     'description': 'Identifies the primary key from the database.'},
    {'name': 'description', 'description': 'The description of the release.'},
    {'name': 'descriptionHTML',
     'description': 'The description of this release rendered to HTML.'},
    {'name': 'id', 'description': 'The Node ID of the Release object'},
    {'name': 'immutable',
     'description': 'Whether or not the release is immutable'},
    {'name': 'isDraft',
     'description': 'Whether or not the release is a draft'},
    {'name': 'isLatest',
     'description': 'Whether or not the release is the latest releast'},
    {'name': 'isPrerelease',
     'description': 'Whether or not the release is a prerelease'},
    {'name': 'mentions',
     'description': 'A list of users mentioned in the release description'},
    {'name': 'name', 'description': 'The title of the release.'},
    {'name': 'publishedAt',
     'description': 'Identifies the date and time when the release was created.'},
    {'name': 'reactionGroups',
     'description': 'A list of reactions grouped by content left on the subject.'},
    {'name': 'reactions',
     'description': 'A list of Reactions left on the Issue.'},
    {'name': 'releaseAssets',
     'description': 'List of releases assets which are dependent on this release.'},
    {'name': 'repository',
     'description': 'The repository that the release belongs to.'},
    {'name': 'resourcePath', 'description': 'The HTTP path for this issue'},
    {'name': 'shortDescriptionHTML',
     'description': 'A description of the release, rendered to HTML without any links in it.'},
    {'name': 'tag', 'description': 'The Git tag the release points to'},
    {'name': 'tagCommit', 'description': 'The tag commit for this release.'},
    {'name': 'tagName', 'description': "The name of the release's Git tag"},
    {'name': 'updatedAt',
     'description': 'Identifies the date and time when the object was last updated.'},
    {'name': 'url', 'description': 'The HTTP URL for this issue'},
    {'name': 'viewerCanReact',
     'description': 'Can user react to this subject'}]}}}

You can also get the schema via a `GET` request to the endpoint `https://api.github.com/graphql`:

In [66]:
response = requests.get("https://api.github.com/graphql", 
                        headers={"Authorization": f"Bearer {access_token}"})

In [67]:
schemas = response.json()

In [72]:
schemas['data']

{'__schema': {'queryType': {'name': 'Query'},
  'mutationType': {'name': 'Mutation'},
  'subscriptionType': None,
  'types': [{'kind': 'INPUT_OBJECT',
    'name': 'AbortQueuedMigrationsInput',
    'description': 'Autogenerated input type of AbortQueuedMigrations',
    'fields': None,
    'inputFields': [{'name': 'clientMutationId',
      'description': 'A unique identifier for the client performing the mutation.',
      'type': {'kind': 'SCALAR', 'name': 'String', 'ofType': None},
      'defaultValue': None},
     {'name': 'ownerId',
      'description': 'The ID of the organization that is running the migrations.',
      'type': {'kind': 'NON_NULL',
       'name': None,
       'ofType': {'kind': 'SCALAR', 'name': 'ID', 'ofType': None}},
      'defaultValue': None}],
    'interfaces': None,
    'enumValues': None,
    'possibleTypes': None},
   {'kind': 'OBJECT',
    'name': 'AbortQueuedMigrationsPayload',
    'description': 'Autogenerated return type of AbortQueuedMigrations.',
    'fields': [{'name': 'clientMutationId',
      'description': 'A unique identifier for the client performing the mutation.',
      'args': [],
      'type': {'kind': 'SCALAR', 'name': 'String', 'ofType': None},
      'isDeprecated': False,
      'deprecationReason': None},
     {'name': 'success',
      'description': 'Did the operation succeed?',
      'args': [],
      'type': {'kind': 'SCALAR', 'name': 'Boolean', 'ofType': None},
      'isDeprecated': False,
      'deprecationReason': None}],
    'inputFields': None,
    'interfaces': [],
    'enumValues': None,
    'possibleTypes': None},
   {'kind': 'INPUT_OBJECT',
    'name': 'AbortRepositoryMigrationInput',
    'description': 'Autogenerated input type of AbortRepositoryMigration',
    'fields': None,
    'inputFields': [{'name': 'clientMutationId',
      'description': 'A unique identifier for the client performing the mutation.',
      'type': {'kind': 'SCALAR', 'name': 'String', 'ofType': None},
      'defaultValue': None},
     {'name': 'migrationId',
      'description': 'The ID of the migration to be aborted.',
      'type': {'kind': 'NON_NULL',
       'name': None,
       'ofType': {'kind': 'SCALAR', 'name': 'ID', 'ofType': None}},
      'defaultValue': None}],
    'interfaces': None,
    'enumValues': None,
    'possibleTypes': None},
   {'kind': 'OBJECT',
    'name': 'AbortRepositoryMigrationPayload',
    'description': 'Autogenerated return type of AbortRepositoryMigration.',
    'fields': [{'name': 'clientMutationId',
      'description': 'A unique identifier for the client performing the mutation.',
      'args': [],
      'type': {'kind': 'SCALAR', 'name': 'String', 'ofType': None},
      'isDeprecated': False,
      'deprecationReason': None},
     {'name': 'success',
      'description': 'Did the operation succeed?',
      'args': [],
      'type': {'kind': 'SCALAR', 'name': 'Boolean', 'ofType': None},
      'isDeprecated': False,
      'deprecationReason': None}],
    'inputFields': None,
    'interfaces': [],
    'enumValues': None,
    'possibleTypes': None},
   {'kind': 'INPUT_OBJECT',
    'name': 'AcceptEnterpriseAdministratorInvitationInput',
    'description': 'Autogenerated input type of AcceptEnterpriseAdministratorInvitation',
    'fields': None,
    'inputFields': [{'name': 'clientMutationId',
      'description': 'A unique identifier for the client performing the mutation.',
      'type': {'kind': 'SCALAR', 'name': 'String', 'ofType': None},
      'defaultValue': None},
     {'name': 'invitationId',
      'description': 'The id of the invitation being accepted',
      'type': {'kind': 'NON_NULL',
       'name': None,
       'ofType': {'kind': 'SCALAR', 'name': 'ID', 'ofType': None}},
      'defaultValue': None}],
    'interfaces': None,
    'enumValues': None,
    'possibleTypes': None},
   {'kind': 'OBJECT',
    'name': 'AcceptEnterpriseAdministratorInvitationPayload',
    'description': 'Autogenerated return type of AcceptEnterpriseAdministratorInvitation.',
    'fields': [{'name': 'clientMutationId',
      'description': 'A unique identifier for the client performing the mutation.',
      'args': [],
      'type': {'kind': 'SCALAR', 'name': 'String', 'ofType': None},
      'isDeprecated': False,
      'deprecationReason': None},
     {'name': 'invitation',
      'description': 'The invitation that was accepted.',
      'args': [],
      'type': {'kind': 'OBJECT',
       'name': 'EnterpriseAdministratorInvitation',
       'ofType': None},
      'isDeprecated': False,
      'deprecationReason': None},
     {'name': 'message',
      'description': 'A message confirming the result of accepting an administrator invitation.',
      'args': [],
      'type': {'kind': 'SCALAR', 'name': 'String', 'ofType': None},
      'isDeprecated': False,
      'deprecationReason': None}],
    'inputFields': None,
    'interfaces': [],
    'enumValues': None,
    'possibleTypes': None},
   {'kind': 'INPUT_OBJECT',
    'name': 'AcceptEnterpriseMemberInvitationInput',
    'description': 'Autogenerated input type of AcceptEnterpriseMemberInvitation',
    'fields': None,
    'inputFields': [{'name': 'clientMutationId',
      'description': 'A unique identifier for the client performing the mutation.',
      'type': {'kind': 'SCALAR', 'name': 'String', 'ofType': None},
      'defaultValue': None},
     {'name': 'invitationId',
      'description': 'The id of the invitation being accepted',
      'type': {'kind': 'NON_NULL',
       'name': None,
       'ofType': {'kind': 'SCALAR', 'name': 'ID', 'ofType': None}},
      'defaultValue': None}],
    'interfaces': None,
    'enumValues': None,
    'possibleTypes': None},
   {'kind': 'OBJECT',
    'name': 'AcceptEnterpriseMemberInvitationPayload',
    'description': 'Autogenerated return type of AcceptEnterpriseMemberInvitation.',
    'fields': [{'name': 'clientMutationId',
      'description': 'A unique identifier for the client performing the mutation.',
      'args': [],
      'type': {'kind': 'SCALAR', 'name': 'String', 'ofType': None},
      'isDeprecated': False,
      'deprecationReason': None},
     {'name': 'invitation',
      'description': 'The invitation that was accepted.',
      'args': [],
      'type': {'kind': 'OBJECT',
       'name': 'EnterpriseMemberInvitation',
       'ofType': None},
      'isDeprecated': False,
      'deprecationReason': None},
     {'name': 'message',
      'description': 'A message confirming the result of accepting an unaffiliated member invitation.',
      'args': [],
      'type': {'kind': 'SCALAR', 'name': 'String', 'ofType': None},
      'isDeprecated': False,
      'deprecationReason': None}],
    'inputFields': None,
    'interfaces': [],
    'enumValues': None,
    'possibleTypes': None},
   {'kind': 'INPUT_OBJECT',
    'name': 'AcceptTopicSuggestionInput',
    'description': 'Autogenerated input type of AcceptTopicSuggestion',
    'fields': None,
    'inputFields': [{'name': 'clientMutationId',
      'description': 'A unique identifier for the client performing the mutation.',
      'type': {'kind': 'SCALAR', 'name': 'String', 'ofType': None},
      'defaultValue': None},
     {'name': 'repositoryId',
      'description': 'The Node ID of the repository.\n\n**Upcoming Change on 2024-04-01 UTC**\n**Description:** `repositoryId` will be removed.\n**Reason:** Suggested topics are no longer supported\n',
      'type': {'kind': 'SCALAR', 'name': 'ID', 'ofType': None},
      'defaultValue': None},
     {'name': 'name',
      'description': 'The name of the suggested topic.\n\n**Upcoming Change on 2024-04-01 UTC**\n**Description:** `name` will be removed.\n**Reason:** Suggested topics are no longer supported\n',
      'type': {'kind': 'SCALAR', 'name': 'String', 'ofType': None},
      'defaultValue': None}],
    'interfaces': None,
    'enumValues': None,
    'possibleTypes': None},
   {'kind': 'OBJECT',
    'name': 'AcceptTopicSuggestionPayload',
    'description': 'Autogenerated return type of AcceptTopicSuggestion.',
    'fields': [{'name': 'clientMutationId',
      'description': 'A unique identifier for the client performing the mutation.',
      'args': [],
      'type': {'kind': 'SCALAR', 'name': 'String', 'ofType': None},
      'isDeprecated': False,
      'deprecationReason': None},
     {'name': 'topic',
      'description': 'The accepted topic.',
      'args': [],
      'type': {'kind': 'OBJECT', 'name': 'Topic', 'ofType': None},
      'isDeprecated': True,
      'deprecationReason': 'Suggested topics are no longer supported Removal on 2024-04-01 UTC.'}],
    'inputFields': None,
    'interfaces': [],
    'enumValues': None,
    'possibleTypes': None},
   {'kind': 'INPUT_OBJECT',
    'name': 'AccessUserNamespaceRepositoryInput',
    'description': 'Autogenerated input type of AccessUserNamespaceRepository',
    'fields': None,
    'inputFields': [{'name': 'clientMutationId',
      'description': 'A unique identifier for the client performing the mutation.',
      'type': {'kind': 'SCALAR', 'name': 'String', 'ofType': None},
      'defaultValue': None},
     {'name': 'enterpriseId',
      'description': 'The ID of the enterprise owning the user namespace repository.',
      'type': {'kind': 'NON_NULL',
       'name': None,
       'ofType': {'kind': 'SCALAR', 'name': 'ID', 'ofType': None}},
      'defaultValue': None},
     {'name': 'repositoryId',
      'description': 'The ID of the user namespace repository to access.',
      'type': {'kind': 'NON_NULL',
       'name': None,
       'ofType': {'kind': 'SCALAR', 'name': 'ID', 'ofType': None}},
      'defaultValue': None}],
    'interfaces': None,
    'enumValues': None,
    'possibleTypes': None},
   {'kind': 'OBJECT',
    'name': 'AccessUserNamespaceRepositoryPayload',
    'description': 'Autogenerated return type of AccessUserNamespaceRepository.',
    'fields': [{'name': 'clientMutationId',
      'description': 'A unique identifier for the client performing the mutation.',
      'args': [],
      'type': {'kind': 'SCALAR', 'name': 'String', 'ofType': None},
      'isDeprecated': False,
      'deprecationReason': None},
     {'name': 'expiresAt',
      'description': 'The time that repository access expires at',
      'args': [],
      'type': {'kind': 'SCALAR', 'name': 'DateTime', 'ofType': None},
      'isDeprecated': False,
      'deprecationReason': None},
     {'name': 'repository',
      'description': 'The repository that is temporarily accessible.',
      'args': [],
      'type': {'kind': 'OBJECT', 'name': 'Repository', 'ofType': None},
      'isDeprecated': False,
      'deprecationReason': None}],
    'inputFields': None,
    'interfaces': [],
    'enumValues': None,
    'possibleTypes': None},
   {'kind': 'INTERFACE',
    'name': 'Actor',
    'description': 'Represents an object which can take actions on GitHub. Typically a User or Bot.',
    'fields': [{'name': 'avatarUrl',
      'description': "A URL pointing to the actor's public avatar.",
      'args': [{'name': 'size',
        'description': 'The size of the resulting square image.',
        'type': {'kind': 'SCALAR', 'name': 'Int', 'ofType': None},
        'defaultValue': None}],
      'type': {'kind': 'NON_NULL',
       'name': None,
       'ofType': {'kind': 'SCALAR', 'name': 'URI', 'ofType': None}},
      'isDeprecated': False,
      'deprecationReason': None},
     {'name': 'login',
      'description': 'The username of the actor.',
      'args': [],
      'type': {'kind': 'NON_NULL',
       'name': None,
       'ofType': {'kind': 'SCALAR', 'name': 'String', 'ofType': None}},
      'isDeprecated': False,
      'deprecationReason': None},
     {'name': 'resourcePath',
      'description': 'The HTTP path for this actor.',
      'args': [],
      'type': {'kind': 'NON_NULL',
       'name': None,
       'ofType': {'kind': 'SCALAR', 'name': 'URI', 'ofType': None}},
      'isDeprecated': False,
      'deprecationReason': None},
     {'name': 'url',
      'description': 'The HTTP URL for this actor.',
      'args': [],
      'type': {'kind': 'NON_NULL',
       'name': None,
       'ofType': {'kind': 'SCALAR', 'name': 'URI', 'ofType': None}},
      'isDeprecated': False,
      'deprecationReason': None}],
    'inputFields': None,
    'interfaces': [],
    'enumValues': None,
    'possibleTypes': [{'kind': 'OBJECT', 'name': 'Bot', 'ofType': None},
     {'kind': 'OBJECT', 'name': 'EnterpriseUserAccount', 'ofType': None},
     {'kind': 'OBJECT', 'name': 'Mannequin', 'ofType': None},
     {'kind': 'OBJECT', 'name': 'Organization', 'ofType': None},
     {'kind': 'OBJECT', 'name': 'User', 'ofType': None}]},
   {'kind': 'OBJECT',
    'name': 'ActorConnection',
    'description': 'The connection type for Actor.',
    'fields': [{'name': 'edges',
      'description': 'A list of edges.',
      'args': [],
      'type': {'kind': 'LIST',
       'name': None,
       'ofType': {'kind': 'OBJECT', 'name': 'ActorEdge', 'ofType': None}},
      'isDeprecated': False,
      'deprecationReason': None},
     {'name': 'nodes',
      'description': 'A list of nodes.',
      'args': [],
      'type': {'kind': 'LIST',
       'name': None,
       'ofType': {'kind': 'INTERFACE', 'name': 'Actor', 'ofType': None}},
      'isDeprecated': False,
      'deprecationReason': None},
     {'name': 'pageInfo',
      'description': 'Information to aid in pagination.',
      'args': [],
      'type': {'kind': 'NON_NULL',
       'name': None,
       'ofType': {'kind': 'OBJECT', 'name': 'PageInfo', 'ofType': None}},
      'isDeprecated': False,
      'deprecationReason': None},
     {'name': 'totalCount',
      'description': 'Identifies the total count of items in the connection.',
      'args': [],
      'type': {'kind': 'NON_NULL',
       'name': None,
       'ofType': {'kind': 'SCALAR', 'name': 'Int', 'ofType': None}},
      'isDeprecated': False,
      'deprecationReason': None}],
    'inputFields': None,
    'interfaces': [],
    'enumValues': None,
    'possibleTypes': None},
   {'kind': 'OBJECT',
    'name': 'ActorEdge',
    'description': 'An edge in a connection.',
    'fields': [{'name': 'cursor',
      'description': 'A cursor for use in pagination.',
      'args': [],
      'type': {'kind': 'NON_NULL',
       'name': None,
       'ofType': {'kind': 'SCALAR', 'name': 'String', 'ofType': None}},
      'isDeprecated': False,
      'deprecationReason': None},
     {'name': 'node',
      'description': 'The item at the end of the edge.',
      'args': [],
      'type': {'kind': 'INTERFACE', 'name': 'Actor', 'ofType': None},
      'isDeprecated': False,
      'deprecationReason': None}],
    'inputFields': None,
    'interfaces': [],
    'enumValues': None,
    'possibleTypes': None},
   {'kind': 'OBJECT',
    'name': 'ActorLocation',
    'description': 'Location information for an actor',
    'fields': [{'name': 'city',
      'description': 'City',
      'args': [],
      'type': {'kind': 'SCALAR', 'name': 'String', 'ofType': None},
      'isDeprecated': False,
      'deprecationReason': None},
     {'name': 'country',
      'description': 'Country name',
      'args': [],
      'type': {'kind': 'SCALAR', 'name': 'String', 'ofType': None},
      'isDeprecated': False,
      'deprecationReason': None},
     {'name': 'countryCode',
      'description': 'Country code',
      'args': [],
      'type': {'kind': 'SCALAR', 'name': 'String', 'ofType': None},
      'isDeprecated': False,
      'deprecationReason': None},
     {'name': 'region',
      'description': 'Region name',
      'args': [],
      'type': {'kind': 'SCALAR', 'name': 'String', 'ofType': None},
      'isDeprecated': False,
      'deprecationReason': None},
     {'name': 'regionCode',
      'description': 'Region or state code',
      'args': [],
      'type': {'kind': 'SCALAR', 'name': 'String', 'ofType': None},
      'isDeprecated': False,
      'deprecationReason': None}],
    'inputFields': None,
    'interfaces': [],
    'enumValues': None,
    'possibleTypes': None},
   {'kind': 'ENUM',
    'name': 'ActorType',
    'description': "The actor's type.",
    'fields': None,
    'inputFields': None,
    'interfaces': None,
    'enumValues': [{'name': 'USER',
      'description': 'Indicates a user actor.',
      'isDeprecated': False,
      'deprecationReason': None},
     {'name': 'TEAM',
      'description': 'Indicates a team actor.',
      'isDeprecated': False,
      'deprecationReason': None}],
    'possibleTypes': None},
   {'kind': 'INPUT_OBJECT',
    'name': 'AddAssigneesToAssignableInput',
    'description': 'Autogenerated input type of AddAssigneesToAssignable',
    'fields': None,
    'inputFields': [{'name': 'clientMutationId',
      'description': 'A unique identifier for the client performing the mutation.',
      'type': {'kind': 'SCALAR', 'name': 'String', 'ofType': None},
      'defaultValue': None},
     {'name': 'assignableId',
      'description': 'The id of the assignable object to add assignees to.',
      'type': {'kind': 'NON_NULL',
       'name': None,
       'ofType': {'kind': 'SCALAR', 'name': 'ID', 'ofType': None}},
      'defaultValue': None},
     {'name': 'assigneeIds',
      'description': 'The ids of actors (users or bots) to add as assignees.',
      'type': {'kind': 'NON_NULL',
       'name': None,
       'ofType': {'kind': 'LIST',
        'name': None,
        'ofType': {'kind': 'NON_NULL',
         'name': None,
         'ofType': {'kind': 'SCALAR', 'name': 'ID', 'ofType': None}}}},
      'defaultValue': None},
     {'name': 'agentAssignment',
      'description': 'Configuration for assigning Copilot to this issue.',
      'type': {'kind': 'INPUT_OBJECT',
       'name': 'AgentAssignmentInput',
       'ofType': None},
      'defaultValue': None}],
    'interfaces': None,
    'enumValues': None,
    'possibleTypes': None},
   {'kind': 'OBJECT',
    'name': 'AddAssigneesToAssignablePayload',
    'description': 'Autogenerated return type of AddAssigneesToAssignable.',
    'fields': [{'name': 'assignable',
      'description': 'The item that was assigned.',
      'args': [],
      'type': {'kind': 'INTERFACE', 'name': 'Assignable', 'ofType': None},
      'isDeprecated': False,
      'deprecationReason': None},
     {'name': 'clientMutationId',
      'description': 'A unique identifier for the client performing the mutation.',
      'args': [],
      'type': {'kind': 'SCALAR', 'name': 'String', 'ofType': None},
      'isDeprecated': False,
      'deprecationReason': None}],
    'inputFields': None,
    'interfaces': [],
    'enumValues': None,
    'possibleTypes': None},
   {'kind': 'INPUT_OBJECT',
    'name': 'AddBlockedByInput',
    'description': 'Autogenerated input type of AddBlockedBy',
    'fields': None,
    'inputFields': [{'name': 'clientMutationId',
      'description': 'A unique identifier for the client performing the mutation.',
      'type': {'kind': 'SCALAR', 'name': 'String', 'ofType': None},
      'defaultValue': None},
     {'name': 'issueId',
      'description': 'The ID of the issue to be blocked.',
      'type': {'kind': 'NON_NULL',
       'name': None,
       'ofType': {'kind': 'SCALAR', 'name': 'ID', 'ofType': None}},
      'defaultValue': None},
     {'name': 'blockingIssueId',
      'description': 'The ID of the issue that blocks the given issue.',
      'type': {'kind': 'NON_NULL',
       'name': None,
       'ofType': {'kind': 'SCALAR', 'name': 'ID', 'ofType': None}},
      'defaultValue': None}],
    'interfaces': None,
    'enumValues': None,
    'possibleTypes': None},
   {'kind': 'OBJECT',
    'name': 'AddBlockedByPayload',
    'description': 'Autogenerated return type of AddBlockedBy.',
    'fields': [{'name': 'blockingIssue',
      'description': 'The issue that is blocking the given issue.',
      'args': [],
      'type': {'kind': 'OBJECT', 'name': 'Issue', 'ofType': None},
      'isDeprecated': False,
      'deprecationReason': None},
     {'name': 'clientMutationId',
      'description': 'A unique identifier for the client performing the mutation.',
      'args': [],

In [74]:
schemas['data']['__schema'].keys()

dict_keys(['queryType', 'mutationType', 'subscriptionType', 'types', 'directives'])

In [75]:
len(schemas['data']['__schema']['types'])

1756

In [81]:
len(schemas['data']['__schema']['types'][0])

8

In [78]:
for t in schemas['data']['__schema']['types']:
    print(t)

{'kind': 'INPUT_OBJECT', 'name': 'AbortQueuedMigrationsInput', 'description': 'Autogenerated input type of AbortQueuedMigrations', 'fields': None, 'inputFields': [{'name': 'clientMutationId', 'description': 'A unique identifier for the client performing the mutation.', 'type': {'kind': 'SCALAR', 'name': 'String', 'ofType': None}, 'defaultValue': None}, {'name': 'ownerId', 'description': 'The ID of the organization that is running the migrations.', 'type': {'kind': 'NON_NULL', 'name': None, 'ofType': {'kind': 'SCALAR', 'name': 'ID', 'ofType': None}}, 'defaultValue': None}], 'interfaces': None, 'enumValues': None, 'possibleTypes': None}
{'kind': 'OBJECT', 'name': 'AbortQueuedMigrationsPayload', 'description': 'Autogenerated return type of AbortQueuedMigrations.', 'fields': [{'name': 'clientMutationId', 'description': 'A unique identifier for the client performing the mutation.', 'args': [], 'type': {'kind': 'SCALAR', 'name': 'String', 'ofType': None}, 'isDeprecated': False, 'deprecationReason': None}, {'name': 'success', 'description': 'Did the operation succeed?', 'args': [], 'type': {'kind': 'SCALAR', 'name': 'Boolean', 'ofType': None}, 'isDeprecated': False, 'deprecationReason': None}], 'inputFields': None, 'interfaces': [], 'enumValues': None, 'possibleTypes': None}
{'kind': 'INPUT_OBJECT', 'name': 'AbortRepositoryMigrationInput', 'description': 'Autogenerated input type of AbortRepositoryMigration', 'fields': None, 'inputFields': [{'name': 'clientMutationId', 'description': 'A unique identifier for the client performing the mutation.', 'type': {'kind': 'SCALAR', 'name': 'String', 'ofType': None}, 'defaultValue': None}, {'name': 'migrationId', 'description': 'The ID of the migration to be aborted.', 'type': {'kind': 'NON_NULL', 'name': None, 'ofType': {'kind': 'SCALAR', 'name': 'ID', 'ofType': None}}, 'defaultValue': None}], 'interfaces': None, 'enumValues': None, 'possibleTypes': None}
{'kind': 'OBJECT', 'name': 'AbortRepositoryMigrationPayload', 'description': 'Autogenerated return type of AbortRepositoryMigration.', 'fields': [{'name': 'clientMutationId', 'description': 'A unique identifier for the client performing the mutation.', 'args': [], 'type': {'kind': 'SCALAR', 'name': 'String', 'ofType': None}, 'isDeprecated': False, 'deprecationReason': None}, {'name': 'success', 'description': 'Did the operation succeed?', 'args': [], 'type': {'kind': 'SCALAR', 'name': 'Boolean', 'ofType': None}, 'isDeprecated': False, 'deprecationReason': None}], 'inputFields': None, 'interfaces': [], 'enumValues': None, 'possibleTypes': None}
{'kind': 'INPUT_OBJECT', 'name': 'AcceptEnterpriseAdministratorInvitationInput', 'description': 'Autogenerated input type of AcceptEnterpriseAdministratorInvitation', 'fields': None, 'inputFields': [{'name': 'clientMutationId', 'description': 'A unique identifier for the client performing the mutation.', 'type': {'kind': 'SCALAR', 'name': 'String', 'ofType': None}, 'defaultValue': None}, {'name': 'invitationId', 'description': 'The id of the invitation being accepted', 'type': {'kind': 'NON_NULL', 'name': None, 'ofType': {'kind': 'SCALAR', 'name': 'ID', 'ofType': None}}, 'defaultValue': None}], 'interfaces': None, 'enumValues': None, 'possibleTypes': None}
{'kind': 'OBJECT', 'name': 'AcceptEnterpriseAdministratorInvitationPayload', 'description': 'Autogenerated return type of AcceptEnterpriseAdministratorInvitation.', 'fields': [{'name': 'clientMutationId', 'description': 'A unique identifier for the client performing the mutation.', 'args': [], 'type': {'kind': 'SCALAR', 'name': 'String', 'ofType': None}, 'isDeprecated': False, 'deprecationReason': None}, {'name': 'invitation', 'description': 'The invitation that was accepted.', 'args': [], 'type': {'kind': 'OBJECT', 'name': 'EnterpriseAdministratorInvitation', 'ofType': None}, 'isDeprecated': False, 'deprecationReason': None}, {'name': 'message', 'description': 'A message confirming the result of accepting an administrator invitation.', 'args': [], 'type': {'kind': 'SCALAR', 'name': 'String', 'ofType': None}, 'isDeprecated': False, 'deprecationReason': None}], 'inputFields': None, 'interfaces': [], 'enumValues': None, 'possibleTypes': None}
{'kind': 'INPUT_OBJECT', 'name': 'AcceptEnterpriseMemberInvitationInput', 'description': 'Autogenerated input type of AcceptEnterpriseMemberInvitation', 'fields': None, 'inputFields': [{'name': 'clientMutationId', 'description': 'A unique identifier for the client performing the mutation.', 'type': {'kind': 'SCALAR', 'name': 'String', 'ofType': None}, 'defaultValue': None}, {'name': 'invitationId', 'description': 'The id of the invitation being accepted', 'type': {'kind': 'NON_NULL', 'name': None, 'ofType': {'kind': 'SCALAR', 'name': 'ID', 'ofType': None}}, 'defaultValue': None}], 'interfaces': None, 'enumValues': None, 'possibleTypes': None}
{'kind': 'OBJECT', 'name': 'AcceptEnterpriseMemberInvitationPayload', 'description': 'Autogenerated return type of AcceptEnterpriseMemberInvitation.', 'fields': [{'name': 'clientMutationId', 'description': 'A unique identifier for the client performing the mutation.', 'args': [], 'type': {'kind': 'SCALAR', 'name': 'String', 'ofType': None}, 'isDeprecated': False, 'deprecationReason': None}, {'name': 'invitation', 'description': 'The invitation that was accepted.', 'args': [], 'type': {'kind': 'OBJECT', 'name': 'EnterpriseMemberInvitation', 'ofType': None}, 'isDeprecated': False, 'deprecationReason': None}, {'name': 'message', 'description': 'A message confirming the result of accepting an unaffiliated member invitation.', 'args': [], 'type': {'kind': 'SCALAR', 'name': 'String', 'ofType': None}, 'isDeprecated': False, 'deprecationReason': None}], 'inputFields': None, 'interfaces': [], 'enumValues': None, 'possibleTypes': None}
{'kind': 'INPUT_OBJECT', 'name': 'AcceptTopicSuggestionInput', 'description': 'Autogenerated input type of AcceptTopicSuggestion', 'fields': None, 'inputFields': [{'name': 'clientMutationId', 'description': 'A unique identifier for the client performing the mutation.', 'type': {'kind': 'SCALAR', 'name': 'String', 'ofType': None}, 'defaultValue': None}, {'name': 'repositoryId', 'description': 'The Node ID of the repository.\n\n**Upcoming Change on 2024-04-01 UTC**\n**Description:** `repositoryId` will be removed.\n**Reason:** Suggested topics are no longer supported\n', 'type': {'kind': 'SCALAR', 'name': 'ID', 'ofType': None}, 'defaultValue': None}, {'name': 'name', 'description': 'The name of the suggested topic.\n\n**Upcoming Change on 2024-04-01 UTC**\n**Description:** `name` will be removed.\n**Reason:** Suggested topics are no longer supported\n', 'type': {'kind': 'SCALAR', 'name': 'String', 'ofType': None}, 'defaultValue': None}], 'interfaces': None, 'enumValues': None, 'possibleTypes': None}
{'kind': 'OBJECT', 'name': 'AcceptTopicSuggestionPayload', 'description': 'Autogenerated return type of AcceptTopicSuggestion.', 'fields': [{'name': 'clientMutationId', 'description': 'A unique identifier for the client performing the mutation.', 'args': [], 'type': {'kind': 'SCALAR', 'name': 'String', 'ofType': None}, 'isDeprecated': False, 'deprecationReason': None}, {'name': 'topic', 'description': 'The accepted topic.', 'args': [], 'type': {'kind': 'OBJECT', 'name': 'Topic', 'ofType': None}, 'isDeprecated': True, 'deprecationReason': 'Suggested topics are no longer supported Removal on 2024-04-01 UTC.'}], 'inputFields': None, 'interfaces': [], 'enumValues': None, 'possibleTypes': None}
{'kind': 'INPUT_OBJECT', 'name': 'AccessUserNamespaceRepositoryInput', 'description': 'Autogenerated input type of AccessUserNamespaceRepository', 'fields': None, 'inputFields': [{'name': 'clientMutationId', 'description': 'A unique identifier for the client performing the mutation.', 'type': {'kind': 'SCALAR', 'name': 'String', 'ofType': None}, 'defaultValue': None}, {'name': 'enterpriseId', 'description': 'The ID of the enterprise owning the user namespace repository.', 'type': {'kind': 'NON_NULL', 'name': None, 'ofType': {'kind': 'SCALAR', 'name': 'ID', 'ofType': None}}, 'defaultValue': None}, {'name': 'repositoryId', 'description': 'The ID of the user namespace repository to access.', 'type': {'kind': 'NON_NULL', 'name': None, 'ofType': {'kind': 'SCALAR', 'name': 'ID', 'ofType': None}}, 'defaultValue': None}], 'interfaces': None, 'enumValues': None, 'possibleTypes': None}
{'kind': 'OBJECT', 'name': 'AccessUserNamespaceRepositoryPayload', 'description': 'Autogenerated return type of AccessUserNamespaceRepository.', 'fields': [{'name': 'clientMutationId', 'description': 'A unique identifier for the client performing the mutation.', 'args': [], 'type': {'kind': 'SCALAR', 'name': 'String', 'ofType': None}, 'isDeprecated': False, 'deprecationReason': None}, {'name': 'expiresAt', 'description': 'The time that repository access expires at', 'args': [], 'type': {'kind': 'SCALAR', 'name': 'DateTime', 'ofType': None}, 'isDeprecated': False, 'deprecationReason': None}, {'name': 'repository', 'description': 'The repository that is temporarily accessible.', 'args': [], 'type': {'kind': 'OBJECT', 'name': 'Repository', 'ofType': None}, 'isDeprecated': False, 'deprecationReason': None}], 'inputFields': None, 'interfaces': [], 'enumValues': None, 'possibleTypes': None}
{'kind': 'INTERFACE', 'name': 'Actor', 'description': 'Represents an object which can take actions on GitHub. Typically a User or Bot.', 'fields': [{'name': 'avatarUrl', 'description': "A URL pointing to the actor's public avatar.", 'args': [{'name': 'size', 'description': 'The size of the resulting square image.', 'type': {'kind': 'SCALAR', 'name': 'Int', 'ofType': None}, 'defaultValue': None}], 'type': {'kind': 'NON_NULL', 'name': None, 'ofType': {'kind': 'SCALAR', 'name': 'URI', 'ofType': None}}, 'isDeprecated': False, 'deprecationReason': None}, {'name': 'login', 'description': 'The username of the actor.', 'args': [], 'type': {'kind': 'NON_NULL', 'name': None, 'ofType': {'kind': 'SCALAR', 'name': 'String', 'ofType': None}}, 'isDeprecated': False, 'deprecationReason': None}, {'name': 'resourcePath', 'description': 'The HTTP path for this actor.', 'args': [], 'type': {'kind': 'NON_NULL', 'name': None, 'ofType': {'kind': 'SCALAR', 'name': 'URI', 'ofType': None}}, 'isDeprecated': False, 'deprecationReason': None}, {'name': 'url', 'description': 'The HTTP URL for this actor.', 'args': [], 'type': {'kind': 'NON_NULL', 'name': None, 'ofType': {'kind': 'SCALAR', 'name': 'URI', 'ofType': None}}, 'isDeprecated': False, 'deprecationReason': None}], 'inputFields': None, 'interfaces': [], 'enumValues': None, 'possibleTypes': [{'kind': 'OBJECT', 'name': 'Bot', 'ofType': None}, {'kind': 'OBJECT', 'name': 'EnterpriseUserAccount', 'ofType': None}, {'kind': 'OBJECT', 'name': 'Mannequin', 'ofType': None}, {'kind': 'OBJECT', 'name': 'Organization', 'ofType': None}, {'kind': 'OBJECT', 'name': 'User', 'ofType': None}]}
{'kind': 'OBJECT', 'name': 'ActorConnection', 'description': 'The connection type for Actor.', 'fields': [{'name': 'edges', 'description': 'A list of edges.', 'args': [], 'type': {'kind': 'LIST', 'name': None, 'ofType': {'kind': 'OBJECT', 'name': 'ActorEdge', 'ofType': None}}, 'isDeprecated': False, 'deprecationReason': None}, {'name': 'nodes', 'description': 'A list of nodes.', 'args': [], 'type': {'kind': 'LIST', 'name': None, 'ofType': {'kind': 'INTERFACE', 'name': 'Actor', 'ofType': None}}, 'isDeprecated': False, 'deprecationReason': None}, {'name': 'pageInfo', 'description': 'Information to aid in pagination.', 'args': [], 'type': {'kind': 'NON_NULL', 'name': None, 'ofType': {'kind': 'OBJECT', 'name': 'PageInfo', 'ofType': None}}, 'isDeprecated': False, 'deprecationReason': None}, {'name': 'totalCount', 'description': 'Identifies the total count of items in the connection.', 'args': [], 'type': {'kind': 'NON_NULL', 'name': None, 'ofType': {'kind': 'SCALAR', 'name': 'Int', 'ofType': None}}, 'isDeprecated': False, 'deprecationReason': None}], 'inputFields': None, 'interfaces': [], 'enumValues': None, 'possibleTypes': None}
{'kind': 'OBJECT', 'name': 'ActorEdge', 'description': 'An edge in a connection.', 'fields': [{'name': 'cursor', 'description': 'A cursor for use in pagination.', 'args': [], 'type': {'kind': 'NON_NULL', 'name': None, 'ofType': {'kind': 'SCALAR', 'name': 'String', 'ofType': None}}, 'isDeprecated': False, 'deprecationReason': None}, {'name': 'node', 'description': 'The item at the end of the edge.', 'args': [], 'type': {'kind': 'INTERFACE', 'name': 'Actor', 'ofType': None}, 'isDeprecated': False, 'deprecationReason': None}], 'inputFields': None, 'interfaces': [], 'enumValues': None, 'possibleTypes': None}
{'kind': 'OBJECT', 'name': 'ActorLocation', 'description': 'Location information for an actor', 'fields': [{'name': 'city', 'description': 'City', 'args': [], 'type': {'kind': 'SCALAR', 'name': 'String', 'ofType': None}, 'isDeprecated': False, 'deprecationReason': None}, {'name': 'country', 'description': 'Country name', 'args': [], 'type': {'kind': 'SCALAR', 'name': 'String', 'ofType': None}, 'isDeprecated': False, 'deprecationReason': None}, {'name': 'countryCode', 'description': 'Country code', 'args': [], 'type': {'kind': 'SCALAR', 'name': 'String', 'ofType': None}, 'isDeprecated': False, 'deprecationReason': None}, {'name': 'region', 'description': 'Region name', 'args': [], 'type': {'kind': 'SCALAR', 'name': 'String', 'ofType': None}, 'isDeprecated': False, 'deprecationReason': None}, {'name': 'regionCode', 'description': 'Region or state code', 'args': [], 'type': {'kind': 'SCALAR', 'name': 'String', 'ofType': None}, 'isDeprecated': False, 'deprecationReason': None}], 'inputFields': None, 'interfaces': [], 'enumValues': None, 'possibleTypes': None}
{'kind': 'ENUM', 'name': 'ActorType', 'description': "The actor's type.", 'fields': None, 'inputFields': None, 'interfaces': None, 'enumValues': [{'name': 'USER', 'description': 'Indicates a user actor.', 'isDeprecated': False, 'deprecationReason': None}, {'name': 'TEAM', 'description': 'Indicates a team actor.', 'isDeprecated': False, 'deprecationReason': None}], 'possibleTypes': None}
{'kind': 'INPUT_OBJECT', 'name': 'AddAssigneesToAssignableInput', 'description': 'Autogenerated input type of AddAssigneesToAssignable', 'fields': None, 'inputFields': [{'name': 'clientMutationId', 'description': 'A unique identifier for the client performing the mutation.', 'type': {'kind': 'SCALAR', 'name': 'String', 'ofType': None}, 'defaultValue': None}, {'name': 'assignableId', 'description': 'The id of the assignable object to add assignees to.', 'type': {'kind': 'NON_NULL', 'name': None, 'ofType': {'kind': 'SCALAR', 'name': 'ID', 'ofType': None}}, 'defaultValue': None}, {'name': 'assigneeIds', 'description': 'The ids of actors (users or bots) to add as assignees.', 'type': {'kind': 'NON_NULL', 'name': None, 'ofType': {'kind': 'LIST', 'name': None, 'ofType': {'kind': 'NON_NULL', 'name': None, 'ofType': {'kind': 'SCALAR', 'name': 'ID', 'ofType': None}}}}, 'defaultValue': None}, {'name': 'agentAssignment', 'description': 'Configuration for assigning Copilot to this issue.', 'type': {'kind': 'INPUT_OBJECT', 'name': 'AgentAssignmentInput', 'ofType': None}, 'defaultValue': None}], 'interfaces': None, 'enumValues': None, 'possibleTypes': None}
{'kind': 'OBJECT', 'name': 'AddAssigneesToAssignablePayload', 'description': 'Autogenerated return type of AddAssigneesToAssignable.', 'fields': [{'name': 'assignable', 'description': 'The item that was assigned.', 'args': [], 'type': {'kind': 'INTERFACE', 'name': 'Assignable', 'ofType': None}, 'isDeprecated': False, 'deprecationReason': None}, {'name': 'clientMutationId', 'description': 'A unique identifier for the client performing the mutation.', 'args': [], 'type': {'kind': 'SCALAR', 'name': 'String', 'ofType': None}, 'isDeprecated': False, 'deprecationReason': None}], 'inputFields': None, 'interfaces': [], 'enumValues': None, 'possibleTypes': None}
{'kind': 'INPUT_OBJECT', 'name': 'AddBlockedByInput', 'description': 'Autogenerated input type of AddBlockedBy', 'fields': None, 'inputFields': [{'name': 'clientMutationId', 'description': 'A unique identifier for the client performing the mutation.', 'type': {'kind': 'SCALAR', 'name': 'String', 'ofType': None}, 'defaultValue': None}, {'name': 'issueId', 'description': 'The ID of the issue to be blocked.', 'type': {'kind': 'NON_NULL', 'name': None, 'ofType': {'kind': 'SCALAR', 'name': 'ID', 'ofType': None}}, 'defaultValue': None}, {'name': 'blockingIssueId', 'description': 'The ID of the issue that blocks the given issue.', 'type': {'kind': 'NON_NULL', 'name': None, 'ofType': {'kind': 'SCALAR', 'name': 'ID', 'ofType': None}}, 'defaultValue': None}], 'interfaces': None, 'enumValues': None, 'possibleTypes': None}
{'kind': 'OBJECT', 'name': 'AddBlockedByPayload', 'description': 'Autogenerated return type of AddBlockedBy.', 'fields': [{'name': 'blockingIssue', 'description': 'The issue that is blocking the given issue.', 'args': [], 'type': {'kind': 'OBJECT', 'name': 'Issue', 'ofType': None}, 'isDeprecated': False, 'deprecationReason': None}, {'name': 'clientMutationId', 'description': 'A unique identifier for the client performing the mutation.', 'args': [], 'type': {'kind': 'SCALAR', 'name': 'String', 'ofType': None}, 'isDeprecated': False, 'deprecationReason': None}, {'name': 'issue', 'description': 'The issue that is blocked.', 'args': [], 'type': {'kind': 'OBJECT', 'name': 'Issue', 'ofType': None}, 'isDeprecated': False, 'deprecationReason': None}], 'inputFields': None, 'interfaces': [], 'enumValues': None, 'possibleTypes': None}
{'kind': 'INPUT_OBJECT', 'name': 'AddCommentInput', 'description': 'Autogenerated input type of AddComment', 'fields': None, 'inputFields': [{'name': 'clientMutationId', 'description': 'A unique identifier for the client performing the mutation.', 'type': {'kind': 'SCALAR', 'name': 'String', 'ofType': None}, 'defaultValue': None}, {'name': 'subjectId', 'description': 'The Node ID of the subject to modify.', 'type': {'kind': 'NON_NULL', 'name': None, 'ofType': {'kind': 'SCALAR', 'name': 'ID', 'ofType': None}}, 'defaultValue': None}, {'name': 'body', 'description': 'The contents of the comment.', 'type': {'kind': 'NON_NULL', 'name': None, 'ofType': {'kind': 'SCALAR', 'name': 'String', 'ofType': None}}, 'defaultValue': None}], 'interfaces': None, 'enumValues': None, 'possibleTypes': None}
{'kind': 'OBJECT', 'name': 'AddCommentPayload', 'description': 'Autogenerated return type of AddComment.', 'fields': [{'name': 'clientMutationId', 'description': 'A unique identifier for the client performing the mutation.', 'args': [], 'type': {'kind': 'SCALAR', 'name': 'String', 'ofType': None}, 'isDeprecated': False, 'deprecationReason': None}, {'name': 'commentEdge', 'description': "The edge from the subject's comment connection.", 'args': [], 'type': {'kind': 'OBJECT', 'name': 'IssueCommentEdge', 'ofType': None}, 'isDeprecated': False, 'deprecationReason': None}, {'name': 'subject', 'description': 'The subject', 'args': [], 'type': {'kind': 'INTERFACE', 'name': 'Node', 'ofType': None}, 'isDeprecated': False, 'deprecationReason': None}, {'name': 'timelineEdge', 'description': "The edge from the subject's timeline connection.", 'args': [], 'type': {'kind': 'OBJECT', 'name': 'IssueTimelineItemEdge', 'ofType': None}, 'isDeprecated': False, 'deprecationReason': None}], 'inputFields': None, 'interfaces': [], 'enumValues': None, 'possibleTypes': None}

It returns the same result as the `__schema` query above.

The GraphQL API only has a single endpoint:

```
https://api.github.com/graphql
```

In REST, HTTP verbs determine the operation performed. In GraphQL, you'll provide a JSON-encoded body whether you're performing a `query` or a `mutation`, so the HTTP verb is `POST`. The exception is an introspection query, which is a simple `GET` to the endpoint (which we did above).

To query GraphQL via `requests`, make a POST request with a JSON payload. The payload must contain a string called `query`.

GraphQL queries return only the data you specify. To form a query, you must specify fields within fields (also known as nested subfields) until you return only scalars.

For example, let's replicate the REST API exercise above where we extract the `releases`. You can see the resources in GraphQL which you can access [here](https://docs.github.com/en/graphql/reference/objects) - search for `releases`. 

We must specify the fields we want to extract:

In [85]:
query = """
query {
    repository(owner: "pandas-dev", name: "pandas") {
        releases(first: 100) {
            totalCount
            edges {
                node {
                    tagName
                    description
                    publishedAt
                }
            }
        }
    }
}
"""
            

response = requests.post("https://api.github.com/graphql", 
                        headers={"Authorization": f"Bearer {access_token}"}, json={"query": query})

Looking at the composition line by line:

`query {`

Because we want to read data from the server, not modify it, query is the root operation. (If you don't specify an operation, query is also the default.)

`repository(owner:"pandas-dev", name:"pandas") {`

To begin the query, we want to find a repository object. The schema validation indicates this object requires an owner and a name argument.

`releases(first: 100) {`

To account for all releases in the repository, we call the releases object. (We could query a single release on a repository, but that would require us to know the tagName of the release we want to return and provide it as an argument.)

Some details about the releases object:

The docs tell us this object has the type `ReleaseConnection`. Schema validation indicates this object requires a last or first number of results as an argument, so we provide first 100. You can find more information about the `ReleaseConnection` type [here](https://docs.github.com/en/graphql/reference/objects#releaseconnection).

- `totalCount`

    The beauty of GraphQL is that we can retrieve the totalCount of the releases object by simply adding it to the query and it will be returned.

- `edges {`

    We know releases is a connection because it has the ReleaseConnection type. To retrieve data about individual release, we have to access the node via edges.

- `nodes {`

    Here we retrieve the nodes at the end of the edge. The ReleaseConnection docs indicate the nodes at the end of the ReleaseConnection type is a Release object.

    Now that we know we're retrieving a Release object, we can look at the docs and specify the fields we want to return:
    ```
    tagName
    description
    publishedAt
    ```

    Here we specify the tagName, description, and publishedAt as before.

In [86]:
releases = response.json()

In [87]:
type(releases)

dict

In [88]:
releases

{'data': {'repository': {'releases': {'totalCount': 120,
    'edges': [{'node': {'tagName': 'v3.0.3',
       'description': 'We are pleased to announce the release of pandas 3.0.3.\r\nThis is a patch release in the 3.0.x series and includes some regression fixes and bug fixes. We recommend that all users of the 3.0.x series upgrade to this version.\r\n\r\nSee the [full whatsnew](https://pandas.pydata.org/docs/whatsnew/v3.0.3.html) for a list of all the changes.\r\n\r\nPandas 3.0 supports Python 3.11 and higher. \r\nThe release can be installed from PyPI:\r\n\r\n    python -m pip install --upgrade pandas==3.0.*\r\n\r\nOr from conda-forge\r\n\r\n    conda install -c conda-forge pandas=3.0\r\n\r\nPlease report any issues with the release on the [pandas issue tracker](https://github.com/pandas-dev/pandas/issues).\r\n\r\nThanks to all the contributors who made this release possible.',
       'publishedAt': '2026-05-11T18:23:29Z'}},
     {'node': {'tagName': 'v3.0.2',
       'description': 'We are pleased to announce the release of pandas 3.0.2.\r\nThis is a patch release in the 3.0.x series and includes some regression fixes and bug fixes. We recommend that all users of the 3.0.x series upgrade to this version.\r\n\r\nSee the [full whatsnew](https://pandas.pydata.org/docs/dev/whatsnew/v3.0.2.html) for a list of all the changes.\r\n\r\nPandas 3.0 supports Python 3.11 and higher. \r\nThe release can be installed from PyPI:\r\n\r\n    python -m pip install --upgrade pandas==3.0.*\r\n\r\nOr from conda-forge\r\n\r\n    conda install -c conda-forge pandas=3.0\r\n\r\nPlease report any issues with the release on the [pandas issue tracker](https://github.com/pandas-dev/pandas/issues).\r\n\r\nThanks to all the contributors who made this release possible.',
       'publishedAt': '2026-03-30T20:14:45Z'}},
     {'node': {'tagName': 'v3.0.1',
       'description': 'We are pleased to announce the release of pandas 3.0.1.\r\nThis is a patch release in the 3.0.x series and includes some regression fixes and bug fixes. We recommend that all users of the 3.0.x series upgrade to this version.\r\n\r\nSee the [full whatsnew](https://pandas.pydata.org/docs/dev/whatsnew/v3.0.1.html) for a list of all the changes.\r\n\r\nPandas 3.0.0 supports Python 3.11 and higher. \r\nThe release can be installed from PyPI:\r\n\r\n    python -m pip install --upgrade pandas==3.0.*\r\n\r\nOr from conda-forge\r\n\r\n    conda install -c conda-forge pandas=3.0\r\n\r\nPlease report any issues with the release on the [pandas issue tracker](https://github.com/pandas-dev/pandas/issues).\r\n\r\nThanks to all the contributors who made this release possible.',
       'publishedAt': '2026-02-17T21:56:03Z'}},
     {'node': {'tagName': 'v3.0.0',
       'description': 'We are pleased to announce the release of pandas 3.0.0, a major release from the pandas 2.x series. This release includes various new features, bug fixes, and performance improvements, as well as possible breaking changes.  \r\n\r\nThe pandas 3.0 release removed a functionality that was deprecated in previous releases. It is recommended to first upgrade to pandas 2.3 and to ensure your code is working without warnings, before upgrading to pandas 3.0.\r\n\r\nHighlights include:\r\n\r\n- [Dedicated string data type by default](https://pandas.pydata.org/docs/whatsnew/v3.0.0.html#whatsnew-300-enhancements-string-dtype)\r\n- [Consistent copy/view behaviour with Copy-on-Write](https://pandas.pydata.org/docs/whatsnew/v3.0.0.html#whatsnew-300-enhancements-copy_on_write) (CoW) (a.k.a. getting rid of the SettingWithCopyWarning)\r\n- [New default resolution for datetime-like data](https://pandas.pydata.org/docs/whatsnew/v3.0.0.html#whatsnew-300-api-breaking-datetime-resolution-inference)\r\n- [Initial support for the new `pd.col` syntax](https://pandas.pydata.org/docs/whatsnew/v3.0.0.html#whatsnew-300-enhancements-col)\r\n\r\nSee the [announcement blog post](https://pandas.pydata.org/community/blog/pandas-3.0.html) and the [detailed release notes](https://pandas.pydata.org/docs/whatsnew/v3.0.0.html) for a list of all the changes.\r\n\r\nPandas 3.0.0 supports Python 3.11 and higher. \r\nThe release can be installed from PyPI\r\n\r\n    python -m pip install --upgrade pandas==3.0.*\r\n\r\nOr from conda-forge\r\n\r\n    conda install -c conda-forge pandas=3.0\r\n\r\nPlease report any issues with the release on the [pandas issue tracker](https://github.com/pandas-dev/pandas/issues/new/choose).\r\n\r\nThanks to all the contributors who made this release possible.',
       'publishedAt': '2026-01-21T15:23:43Z'}},
     {'node': {'tagName': 'v3.0.0rc2',
       'description': '',
       'publishedAt': '2026-01-14T22:17:15Z'}},
     {'node': {'tagName': 'v3.0.0rc1',
       'description': '',
       'publishedAt': '2025-12-19T21:38:48Z'}},
     {'node': {'tagName': 'v3.0.0rc0',
       'description': "We are pleased to announce a first release candidate for pandas 3.0.0. If all goes well, we'll release pandas 3.0.0 in a few weeks.\r\n\r\nSee the [whatsnew][0] for a list of all the changes.\r\n\r\nThe release is available on conda-forge and PyPI.\r\n\r\nThe release can be installed from PyPI\r\n\r\n    python -m pip install --upgrade --pre pandas==3.0.0rc0\r\n\r\nOr from conda-forge\r\n\r\n    conda install -c conda-forge/label/pandas_rc pandas==3.0.0rc0\r\n\r\nPlease report any issues with the release candidate on the pandas issue tracker.\r\n\r\n[0]: https://pandas.pydata.org/docs/dev/whatsnew/v3.0.0.html",
       'publishedAt': '2025-12-03T17:10:26Z'}},
     {'node': {'tagName': 'v2.3.3',
       'description': 'We are pleased to announce the release of pandas 2.3.3.\r\nThis release includes some improvements and fixes to the future string data type (preview feature for the upcoming pandas 3.0). We recommend that all users upgrade to this version.\r\n\r\nSee the [full whatsnew](https://pandas.pydata.org/pandas-docs/version/2.3/whatsnew/v2.3.3.html) for a list of all the changes.\r\nPandas 2.3.3 supports Python 3.9 and higher, and is the first release to support Python 3.14.\r\n\r\nThe release will be available on the conda-forge channel:\r\n\r\n    conda install pandas --channel conda-forge\r\n\r\nOr via PyPI:\r\n\r\n    python3 -m pip install --upgrade pandas\r\n\r\nPlease report any issues with the release on the [pandas issue tracker](https://github.com/pandas-dev/pandas/issues).\r\n\r\nThanks to all the contributors who made this release possible.',
       'publishedAt': '2025-09-29T22:48:39Z'}},
     {'node': {'tagName': 'v2.3.2',
       'description': 'We are pleased to announce the release of pandas 2.3.2.\r\nThis release includes some improvements and fixes to the future string data type (preview feature for the upcoming pandas 3.0). We recommend that all users upgrade to this version.\r\n\r\nSee the [full whatsnew](https://pandas.pydata.org/pandas-docs/version/2.3/whatsnew/v2.3.2.html) for a list of all the changes.\r\nPandas 2.3.2 supports Python 3.9 and higher.\r\n\r\nThe release will be available on the conda-forge channel:\r\n\r\n    conda install pandas --channel conda-forge\r\n\r\nOr via PyPI:\r\n\r\n    python3 -m pip install --upgrade pandas\r\n\r\nPlease report any issues with the release on the [pandas issue tracker](https://github.com/pandas-dev/pandas/issues).\r\n\r\nThanks to all the contributors who made this release possible.',
       'publishedAt': '2025-08-21T10:22:44Z'}},
     {'node': {'tagName': 'v2.3.1',
       'description': 'We are pleased to announce the release of pandas 2.3.1.\r\nThis release includes some improvements and fixes to the future string data type (preview feature for the upcoming pandas 3.0). We recommend that all users upgrade to this version.\r\n\r\nSee the [full whatsnew](https://pandas.pydata.org/pandas-docs/version/2.3.1/whatsnew/v2.3.1.html) for a list of all the changes.\r\nPandas 2.3.1 supports Python 3.9 and higher.\r\n\r\nThe release will be available on the conda-forge channel:\r\n\r\n    conda install pandas --channel conda-forge\r\n\r\nOr via PyPI:\r\n\r\n    python3 -m pip install --upgrade pandas\r\n\r\nPlease report any issues with the release on the [pandas issue tracker](https://github.com/pandas-dev/pandas/issues).\r\n\r\nThanks to all the contributors who made this release possible.',
       'publishedAt': '2025-07-07T19:12:32Z'}},
     {'node': {'tagName': 'v2.3.0',
       'description': 'We are pleased to announce the release of pandas 2.3.0.\r\nThis release includes some new features, bug fixes, and performance improvements. We recommend that all users upgrade to this version.\r\n\r\nSee the [full whatsnew](https://pandas.pydata.org/pandas-docs/version/2.3.0/whatsnew/v2.3.0.html) for a list of all the changes.\r\nPandas 2.3.0 supports Python 3.10 and higher.\r\n\r\nThe release will be available on the defaults and conda-forge channels:\r\n\r\n    conda install -c conda-forge pandas\r\n\r\nOr via PyPI:\r\n\r\n    python3 -m pip install --upgrade pandas\r\n\r\nPlease report any issues with the release on the [pandas issue tracker](https://github.com/pandas-dev/pandas/issues).\r\n\r\nThanks to all the contributors who made this release possible.',
       'publishedAt': '2025-06-05T03:17:32Z'}},
     {'node': {'tagName': 'v2.2.3',
       'description': 'We are pleased to announce the release of pandas 2.2.3.\r\nThis release includes some new features, bug fixes, and performance improvements. We recommend that all users upgrade to this version.\r\n\r\nSee the [full whatsnew](https://pandas.pydata.org/pandas-docs/version/2.2.3/whatsnew/v2.2.3.html) for a list of all the changes.\r\nPandas 2.2.3 supports Python 3.9 and higher.\r\n\r\nThe release will be available on the defaults and conda-forge channels:\r\n\r\n    conda install pandas\r\n\r\nOr via PyPI:\r\n\r\n    python3 -m pip install --upgrade pandas\r\n\r\nPlease report any issues with the release on the [pandas issue tracker](https://github.com/pandas-dev/pandas/issues).\r\n\r\nThanks to all the contributors who made this release possible.',
       'publishedAt': '2024-09-20T13:10:41Z'}},
     {'node': {'tagName': 'v2.2.2',
       'description': 'We are pleased to announce the release of pandas 2.2.2.\r\nThis release includes some new features, bug fixes, and performance improvements. We recommend that all users upgrade to this version.\r\n\r\nSee the [full whatsnew](https://pandas.pydata.org/pandas-docs/version/2.2.2/whatsnew/v2.2.2.html) for a list of all the changes.\r\nPandas 2.2.2 supports Python 3.9 and higher.\r\n\r\nThe release will be available on the defaults and conda-forge channels:\r\n\r\n    conda install pandas\r\n\r\nOr via PyPI:\r\n\r\n    python3 -m pip install --upgrade pandas\r\n\r\nPlease report any issues with the release on the [pandas issue tracker](https://github.com/pandas-dev/pandas/issues).\r\n\r\nThanks to all the contributors who made this release possible.',
       'publishedAt': '2024-04-10T19:47:02Z'}},
     {'node': {'tagName': 'v2.2.1',
       'description': 'We are pleased to announce the release of pandas 2.2.1.\r\nThis release includes some new features, bug fixes, and performance improvements. We recommend that all users upgrade to this version.\r\n\r\nSee the [full whatsnew](https://pandas.pydata.org/pandas-docs/version/2.2.1/whatsnew/v2.2.1.html) for a list of all the changes.\r\nPandas 2.2.1 supports Python 3.9 and higher.\r\n\r\nThe release will be available on the defaults and conda-forge channels:\r\n\r\n    conda install pandas\r\n\r\nOr via PyPI:\r\n\r\n    python3 -m pip install --upgrade pandas\r\n\r\nPlease report any issues with the release on the [pandas issue tracker](https://github.com/pandas-dev/pandas/issues).\r\n\r\nThanks to all the contributors who made this release possible.',
       'publishedAt': '2024-02-23T15:29:27Z'}},
     {'node': {'tagName': 'v2.2.0',
       'description': 'We are pleased to announce the release of pandas 2.2.0.\r\nThis release includes some new features, bug fixes, and performance improvements. We recommend that all users upgrade to this version.\r\n\r\nSee the [full whatsnew](https://pandas.pydata.org/pandas-docs/version/2.2.0/whatsnew/v2.2.0.html) for a list of all the changes.\r\nPandas 2.2.0 supports Python 3.9 and higher.\r\n\r\nThe release will be available on the defaults and conda-forge channels:\r\n\r\n    conda install pandas\r\n\r\nOr via PyPI:\r\n\r\n    python3 -m pip install --upgrade pandas\r\n\r\nPlease report any issues with the release on the [pandas issue tracker](https://github.com/pandas-dev/pandas/issues).\r\n\r\nThanks to all the contributors who made this release possible.',
       'publishedAt': '2024-01-20T03:33:20Z'}},
     {'node': {'tagName': 'v2.2.0rc0',
       'description': "We are pleased to announce a release candidate for pandas 2.2.0. If all goes well, we'll release pandas 2.2.0 in about two weeks.\r\n\r\nSee the [whatsnew](https://pandas.pydata.org/pandas-docs/version/2.2.0rc0/whatsnew/v2.2.0.html) for a list of all the changes.\r\n\r\nThe release will be available on conda-forge and PyPI.\r\n\r\nThe release can be installed from PyPI\r\n\r\npython -m pip install --upgrade --pre pandas==2.2.0rc0\r\nOr from conda-forge\r\n\r\nconda install -c conda-forge/label/pandas_rc pandas==2.2.0rc0\r\nPlease report any issues with the release candidate on the pandas issue tracker.",
       'publishedAt': '2023-12-22T19:57:46Z'}},
     {'node': {'tagName': 'v2.1.4',
       'description': 'This is a patch release in the 2.1.x series and includes some regression and bug fixes, and a security fix. We recommend that all users upgrade to this version.\r\n\r\nSee the [full whatsnew](https://pandas.pydata.org/pandas-docs/version/2.1.4/whatsnew/v2.1.4.html) for a list of all the changes.\r\n\r\nThe release will be available on the defaults and conda-forge channels:\r\n```\r\nconda install pandas\r\n```\r\nOr via PyPI:\r\n```\r\npython3 -m pip install --upgrade pandas\r\n```\r\nPlease report any issues with the release on the [pandas issue tracker](https://github.com/pandas-dev/pandas/issues).\r\n\r\nThanks to all the contributors who made this release possible.',
       'publishedAt': '2023-12-08T15:39:17Z'}},
     {'node': {'tagName': 'v2.1.3',
       'description': 'This is a patch release in the 2.1.x series and includes some regression and bug fixes, and a security fix. We recommend that all users upgrade to this version.\r\n\r\nSee the [full whatsnew](https://pandas.pydata.org/pandas-docs/version/2.1.3/whatsnew/v2.1.3.html) for a list of all the changes.\r\n\r\nThe release will be available on the defaults and conda-forge channels:\r\n```\r\nconda install pandas\r\n```\r\nOr via PyPI:\r\n```\r\npython3 -m pip install --upgrade pandas\r\n```\r\nPlease report any issues with the release on the [pandas issue tracker](https://github.com/pandas-dev/pandas/issues).\r\n\r\nThanks to all the contributors who made this release possible.',
       'publishedAt': '2023-11-10T19:07:37Z'}},
     {'node': {'tagName': 'v2.1.2',
       'description': 'This is a patch release in the 2.1.x series and includes some regression and bug fixes. We recommend that all users upgrade to this version.\r\n\r\nSee the [full whatsnew](https://pandas.pydata.org/pandas-docs/version/2.1.2/whatsnew/v2.1.2.html) for a list of all the changes.\r\n\r\nThe release will be available on the defaults and conda-forge channels:\r\n```\r\nconda install pandas\r\n```\r\nOr via PyPI:\r\n```\r\npython3 -m pip install --upgrade pandas\r\n```\r\nPlease report any issues with the release on the [pandas issue tracker](https://github.com/pandas-dev/pandas/issues).\r\n\r\nThanks to all the contributors who made this release possible.',
       'publishedAt': '2023-10-26T21:16:59Z'}},
     {'node': {'tagName': 'v2.1.1',
       'description': 'This is a patch release in the 2.1.x series and includes some regression and bug fixes. We recommend that all users upgrade to this version.\r\n\r\nSee the [full whatsnew](https://pandas.pydata.org/pandas-docs/version/2.1.1/whatsnew/v2.1.1.html) for a list of all the changes.\r\n\r\nThe release will be available on the defaults and conda-forge channels:\r\n```\r\nconda install pandas\r\n```\r\nOr via PyPI:\r\n```\r\npython3 -m pip install --upgrade pandas\r\n```\r\nPlease report any issues with the release on the [pandas issue tracker](https://github.com/pandas-dev/pandas/issues).\r\n\r\nThanks to all the contributors who made this release possible.',
       'publishedAt': '2023-09-20T21:02:05Z'}},
     {'node': {'tagName': 'v2.1.0',
       'description': 'We are pleased to announce the release of pandas 2.1.0.\r\nThis release includes some new features, bug fixes, and performance improvements. We recommend that all users upgrade to this version.\r\n\r\nSee the [full whatsnew](https://pandas.pydata.org/pandas-docs/version/2.1.0/whatsnew/v2.1.0.html) for a list of all the changes.\r\nPandas 2.1.0 supports Python 3.9 and higher.\r\n\r\nThe release will be available on the defaults and conda-forge channels:\r\n\r\n    conda install pandas\r\n\r\nOr via PyPI:\r\n\r\n    python3 -m pip install --upgrade pandas\r\n\r\nPlease report any issues with the release on the [pandas issue tracker](https://github.com/pandas-dev/pandas/issues).\r\n\r\nThanks to all the contributors who made this release possible.',
       'publishedAt': '2023-08-30T13:24:32Z'}},
     {'node': {'tagName': 'v2.1.0rc0',
       'description': "We are pleased to announce a release candidate for pandas 2.1.0. If all goes well, we'll release pandas 2.1.0 in about two weeks.\r\n\r\nSee the [whatsnew][0] for a list of all the changes.\r\n\r\nThe release will be available on conda-forge and PyPI.\r\n\r\nThe release can be installed from PyPI\r\n\r\n    python -m pip install --upgrade --pre pandas==2.1.0rc0\r\n\r\nOr from conda-forge\r\n\r\n    conda install -c conda-forge/label/pandas_rc pandas==2.1.0rc0\r\n\r\nPlease report any issues with the release candidate on the pandas issue tracker.\r\n\r\n[0]: https://pandas.pydata.org/pandas-docs/version/2.1.0rc0/whatsnew/v2.1.0.html",
       'publishedAt': '2023-08-11T18:43:29Z'}},
     {'node': {'tagName': 'v2.0.3',
       'description': 'This is a patch release in the 2.0.x series and includes some regression and bug fixes. We recommend that all users upgrade to this version.\r\n\r\nSee the [full whatsnew](https://pandas.pydata.org/pandas-docs/version/2.0.3/whatsnew/v2.0.3.html) for a list of all the changes.\r\n\r\nThe release will be available on the defaults and conda-forge channels:\r\n\r\nconda install pandas\r\nOr via PyPI:\r\n\r\npython3 -m pip install --upgrade pandas\r\nPlease report any issues with the release on the [pandas issue tracker](https://github.com/pandas-dev/pandas/issues).\r\n\r\nThanks to all the contributors who made this release possible.',
       'publishedAt': '2023-06-28T23:24:00Z'}},
     {'node': {'tagName': 'v2.0.2',
       'description': 'This is a patch release in the 2.0.x series and includes some regression and bug fixes. We recommend that all users upgrade to this version.\r\n\r\nSee the [full whatsnew](https://pandas.pydata.org/pandas-docs/version/2.0.2/whatsnew/v2.0.2.html) for a list of all the changes.\r\n\r\nThe release will be available on the defaults and conda-forge channels:\r\n\r\n    conda install pandas\r\n\r\nOr via PyPI:\r\n\r\n    python3 -m pip install --upgrade pandas\r\n\r\nPlease report any issues with the release on the [pandas issue tracker](https://github.com/pandas-dev/pandas/issues).\r\n\r\nThanks to all the contributors who made this release possible.',
       'publishedAt': '2023-05-28T21:06:46Z'}},
     {'node': {'tagName': 'v2.0.1',

In [89]:
releases['data']['repository']['releases']['totalCount']

120

In [ ]:
len(releases['data']['repository']['releases']['edges'])

1

In [94]:
releases['data']['repository']['releases']['edges'][0]['node']

{'tagName': 'v3.0.3',
 'description': 'We are pleased to announce the release of pandas 3.0.3.\r\nThis is a patch release in the 3.0.x series and includes some regression fixes and bug fixes. We recommend that all users of the 3.0.x series upgrade to this version.\r\n\r\nSee the [full whatsnew](https://pandas.pydata.org/docs/whatsnew/v3.0.3.html) for a list of all the changes.\r\n\r\nPandas 3.0 supports Python 3.11 and higher. \r\nThe release can be installed from PyPI:\r\n\r\n    python -m pip install --upgrade pandas==3.0.*\r\n\r\nOr from conda-forge\r\n\r\n    conda install -c conda-forge pandas=3.0\r\n\r\nPlease report any issues with the release on the [pandas issue tracker](https://github.com/pandas-dev/pandas/issues).\r\n\r\nThanks to all the contributors who made this release possible.',
 'publishedAt': '2026-05-11T18:23:29Z'}

In [95]:
releases['data']['repository']['releases']['edges'][-1]['node']

{'tagName': 'v0.18.0rc2',
 'description': '**RELEASE CANDIDATE 2**\n\nTHIS IS NOT A PRODUCTION RELEASE\n\nCompared to RC1, this includes the update to `read_sas` as well as fixes for float indexing.\n\nThis is a major release from 0.17.1 and includes a small number of API changes, several new features,\nenhancements, and performance improvements along with a large number of bug fixes. We recommend that all\nusers upgrade to this version.\n\nHighlights include:\n-  pandas >= 0.18.0 will no longer support compatibility with Python version 2.6 [GH11273](https://github.com/pydata/pandas/issues/11273) and 3.3 [GH7718](https://github.com/pydata/pandas/issues/7718)\n- Moving and expanding window functions are now methods on Series and DataFrame, similar to `.groupby`, see [here](http://pandas-docs.github.io/pandas-docs-travis/whatsnew.html#whatsnew-0180-enhancements-moments).\n- Adding support for a `RangeIndex` as a specialized form of the `Int64Index`\n  for memory savings, see [here](http://pandas-docs.github.io/pandas-docs-travis/whatsnew.html#whatsnew-0180-enhancements-rangeindex).\n- API breaking `.resample` changes to make it more `.groupby` like, see [here](http://pandas-docs.github.io/pandas-docs-travis/whatsnew.html#whatsnew-0180-breaking-resample)\n- Removal of support for positional indexing with floats, which was deprecated since 0.14.0. This will now raise a `TypeError`, see [here](http://pandas-docs.github.io/pandas-docs-travis/whatsnew.html#whatsnew-0180-float-indexers)\n- The `.to_xarray()` function has been added for compatibility with the [xarray package](http://xarray.pydata.org/en/stable/) see [here](http://pandas-docs.github.io/pandas-docs-travis/whatsnew.html#whatsnew-0180-enhancements-xarray).\n- The `read_sas()` function has been enhanced to read `sas7bdat` files, see [here](http://pandas-docs.github.io/pandas-docs-travis/whatsnew.html#whatsnew-0180-enhancements-sas)\n- Addition of the [.str.extractall() method](http://pandas-docs.github.io/pandas-docs-travis/whatsnew.html#whatsnew-0180-enhancements-extractall), and API changes to the the [.str.extract() method](http://pandas-docs.github.io/pandas-docs-travis/whatsnew.html#whatsnew-0180-enhancements-extract), and the[.str.cat() method](http://pandas-docs.github.io/pandas-docs-travis/whatsnew.html#whatsnew-0180-enhancements-strcat)\n- `pd.test()` top-level nose test runner is available [GH4327](https://github.com/pydata/pandas/issues/4327)\n\nSee the [Whatsnew](http://pandas-docs.github.io/pandas-docs-travis/whatsnew.html) for much more information. Please report any issues [here](https://github.com/pydata/pandas/issues/)\n\nbest way to get this is to install via [conda](http://pandas-docs.github.io/pandas-docs-travis/install.html#installing-pandas-with-anaconda) from our development channel. Builds for `osx-64,linux-64,win-64` for `Python 2.7 and Python 3.5` are all available.\n\n`conda install pandas=v0.18.0rc2 -c pandas`\n',
 'publishedAt': '2016-03-09T14:47:45Z'}

> Query the `issues` resource, return the first 50 issues with the fields- `title`, `createdAt` and `author`, under the `author` field, return the `login` field.
>
> Refer to this [link](https://docs.github.com/en/graphql/reference/objects#issue) for more info.

In [121]:
query = """
query {
    repository(owner: "pandas-dev", name: "pandas") {
        issues(first: 100) {
            totalCount
            edges {
                node {
                        id            
                        number        
                        title         
                        body            
                        state           
                        createdAt       
                        updatedAt       
                        closedAt        
    
                        author {
                            login       
                            }
                    }
                }
            }
        }
}

"""
            

response_issues = requests.post("https://api.github.com/graphql", 
                        headers={"Authorization": f"Bearer {access_token}"}, json={"query": query})

In [123]:
 response_issues = response_issues.json()

In [162]:
for r in response_issues['data']['repository']['issues']['edges']:
    node = r['node']
    issue_id = node['id']
    title = node['title']
    state = node['state']
    created = node['createdAt']
    if node['author'] ==None : 
        login = 'Not available'
    else:
        login = node['author']['login']

    print(f"ID: {issue_id} | Title: {title} | State: {state} | Created: {created} | login: {login}")
    # print(f"login: {login}")

ID: MDU6SXNzdWUzMzc3MjE= | Title: Enable element-wise comparison operations in DataMatrix objects | State: CLOSED | Created: 2010-09-29T00:45:31Z | login: wesm
ID: MDU6SXNzdWUzMzc3MjY= | Title: reindex_like function | State: CLOSED | Created: 2010-09-29T00:50:13Z | login: wesm
ID: MDU6SXNzdWUzMzc3Mjg= | Title: Binary operations on int DataMatrix | State: CLOSED | Created: 2010-09-29T00:50:52Z | login: wesm
ID: MDU6SXNzdWUzMzc3MzA= | Title: Plot keyword arguments are unused in DataFrame plot() | State: CLOSED | Created: 2010-09-29T00:51:27Z | login: wesm
ID: MDU6SXNzdWUzMzc3MzY= | Title: Python 2.7 testing | State: CLOSED | Created: 2010-09-29T00:57:00Z | login: wesm
ID: MDU6SXNzdWUzMzc5OTQ= | Title: Fix argument inconsistency in pandas.stats.moments exp-weighted functions | State: CLOSED | Created: 2010-09-29T05:30:56Z | login: wesm
ID: MDU6SXNzdWUzMzg5MDk= | Title: DataMatrix constructor ignores dtype argument if data is a DataMatrix | State: CLOSED | Created: 2010-09-29T15:41:55Z | login: andylei
ID: MDU6SXNzdWUzMzkzNTU= | Title: np.fix doesn't work | State: CLOSED | Created: 2010-09-29T19:45:47Z | login: andylei
ID: MDU6SXNzdWUzNDE1Nzc= | Title: Fix pandas.io.parsers.parseExcel to be more robust / have correct handling of Excel dates | State: CLOSED | Created: 2010-09-30T22:29:36Z | login: wesm
ID: MDU6SXNzdWUzNDE1ODE= | Title: Improvements to pandas.io.pytables / unit testing | State: CLOSED | Created: 2010-09-30T22:33:14Z | login: wesm
ID: MDU6SXNzdWUzNDE1ODM= | Title: Rename {Series, DataFrame, WidePanel}.fill() to something else | State: CLOSED | Created: 2010-09-30T22:34:26Z | login: wesm
ID: MDU6SXNzdWUzNDQ3MjU= | Title: DataFrame and DataMatrix column ordering | State: CLOSED | Created: 2010-10-03T17:20:41Z | login: hector13
ID: MDU6SXNzdWUzNTIzNjk= | Title: Add PyTable Paths to HDFStore | State: CLOSED | Created: 2010-10-07T23:42:34Z | login: surbas
ID: MDU6SXNzdWUzNTYwNjQ= | Title: Make more flexible arithmetic functions in DataFrame/DataMatrix | State: CLOSED | Created: 2010-10-11T03:19:39Z | login: wesm
ID: MDU6SXNzdWUzNTg5NDM= | Title: .apply() API consistency fix | State: CLOSED | Created: 2010-10-12T16:10:48Z | login: wesm
ID: MDU6SXNzdWUzNTg5NDc= | Title: Outlier detection in pandas.stats.moments functions | State: CLOSED | Created: 2010-10-12T16:13:04Z | login: wesm
ID: MDU6SXNzdWUzNTg5NTA= | Title: Better support for mixed-type data | State: CLOSED | Created: 2010-10-12T16:13:55Z | login: wesm
ID: MDU6SXNzdWUzNTg5NTI= | Title: weights option may not be working in pandas.stats.ols.OLS | State: CLOSED | Created: 2010-10-12T16:15:10Z | login: wesm
ID: MDU6SXNzdWUzNzY4OTA= | Title: parseCSV on result of toCSV does not preserve index type | State: CLOSED | Created: 2010-10-22T17:59:31Z | login: wesm
ID: MDU6SXNzdWU0Mjg1NjQ= | Title: Install 0.2beta fail on Debian Lenny / python2.5 | State: CLOSED | Created: 2010-11-19T14:50:11Z | login: mpenning
ID: MDU6SXNzdWU0Mjg5ODE= | Title: Consistent column ordering between DataFrame and DataMatrix | State: CLOSED | Created: 2010-11-19T18:41:36Z | login: wesm
ID: MDU6SXNzdWU0NzQxNjA= | Title: numpy.dtype size changed runtime warning on XP | State: CLOSED | Created: 2010-12-14T16:50:11Z | login: tgefell
ID: MDU6SXNzdWU0ODgwMjY= | Title: numpy traceback during easy_install on Debian Lenny | State: CLOSED | Created: 2010-12-22T10:37:40Z | login: mpenning
ID: MDU6SXNzdWU0OTExODE= | Title: Install problems | State: CLOSED | Created: 2010-12-24T07:27:52Z | login: knm
ID: MDU6SXNzdWU0OTExODU= | Title: Souce compile errors | State: CLOSED | Created: 2010-12-24T07:32:39Z | login: knm
ID: MDU6SXNzdWU1MDM5NDA= | Title: dtype mismatch when calling .median() | State: CLOSED | Created: 2011-01-03T17:15:19Z | login: mpenning
ID: MDU6SXNzdWU1MDQ3MTU= | Title: Incorrect T-Stats in FamaMacBeth.py | State: CLOSED | Created: 2011-01-03T23:29:47Z | login: Liam3851
ID: MDU6SXNzdWU1MTg5NjM= | Title: what is the easiest way to plot a timeseries and dataframe? | State: CLOSED | Created: 2011-01-11T04:14:15Z | login: triplechess
ID: MDU6SXNzdWU1MTk0NzU= | Title: .asfreq() dies when the index values have tzinfo associated with them | State: CLOSED | Created: 2011-01-11T12:15:39Z | login: mpenning
ID: MDU6SXNzdWU1MTk1MTY= | Title: resource hog -> .asfreq(DateOffset(seconds=1),method='pad') | State: CLOSED | Created: 2011-01-11T12:31:34Z | login: mpenning
ID: MDU6SXNzdWU1MjM3NDc= | Title: Is there a single pdf instead of html documentation/help file? | State: CLOSED | Created: 2011-01-13T04:05:11Z | login: triplechess
ID: MDU6SXNzdWU1MzUwMzI= | Title: Does pandas support piecewise/multi-period regression? | State: CLOSED | Created: 2011-01-18T20:28:41Z | login: triplechess
ID: MDU6SXNzdWU1NDQxOTU= | Title: NumPy >= 1.4.0 NaN-handling issues | State: CLOSED | Created: 2011-01-22T20:36:36Z | login: wesm
ID: MDU6SXNzdWU1NDc5Njc= | Title: reindex(method="backfill") and periods within the last date | State: CLOSED | Created: 2011-01-24T20:15:05Z | login: tgefell
ID: MDU6SXNzdWU2Mjc2MjY= | Title: Install problems on Windows 7 | State: CLOSED | Created: 2011-02-25T19:07:03Z | login: tgefell
ID: MDU6SXNzdWU3MzYwNTg= | Title: Adding variable description in DataFrame | State: CLOSED | Created: 2011-04-06T00:15:26Z | login: Not available
ID: MDU6SXNzdWU4MzU3MjQ= | Title: Create generic moving window function | State: CLOSED | Created: 2011-05-01T17:31:45Z | login: wesm
ID: MDU6SXNzdWU4MzU3MzE= | Title: Join methods for WidePanel | State: CLOSED | Created: 2011-05-01T17:32:55Z | login: wesm
ID: MDU6SXNzdWU4MzU3MzY= | Title: Slice DataMatrix-- get a view | State: CLOSED | Created: 2011-05-01T17:33:45Z | login: wesm
ID: MDU6SXNzdWU4MzU3NzE= | Title: HDFStore testing and improvements | State: CLOSED | Created: 2011-05-01T17:58:10Z | login: wesm
ID: MDU6SXNzdWU4NTc4Nzg= | Title: All days instead of business days? | State: CLOSED | Created: 2011-05-06T10:38:14Z | login: Not available
ID: MDU6SXNzdWU5MzQxNDI= | Title: Importing data using HDFStore with pre-epoch dates; "ValueError: timestamp out of range for platform localtime()/gmtime() function" | State: CLOSED | Created: 2011-05-20T22:13:31Z | login: surbas
ID: MDU6SXNzdWU5Nzk3ODI= | Title: Configure pandas like pyzmq so checking in .c files is not necessary | State: CLOSED | Created: 2011-05-31T16:51:22Z | login: wesm
ID: MDU6SXNzdWU5OTcwMzY= | Title: Time zone handling in DateRange, etc. using pytz | State: CLOSED | Created: 2011-06-03T08:53:52Z | login: wesm
ID: MDU6SXNzdWU5OTcxNjU= | Title: "Proper" boolean array with NA handling in DataMatrix | State: CLOSED | Created: 2011-06-03T09:08:28Z | login: wesm
ID: MDU6SXNzdWU5OTcxOTA= | Title: Consistent column ordering in mixed-type DataMatrix | State: CLOSED | Created: 2011-06-03T09:10:29Z | login: wesm
ID: MDU6SXNzdWU5OTgwMTY= | Title: Better implementation of rolling_max and min | State: CLOSED | Created: 2011-06-03T10:50:07Z | login: wesm
ID: MDU6SXNzdWUxMDkxOTky | Title: examples not running, error in documentation | State: CLOSED | Created: 2011-06-21T14:09:06Z | login: columW
ID: MDU6SXNzdWUxMDkyNjQ5 | Title: Improve fancy indexing when selecting cross-sections | State: CLOSED | Created: 2011-06-21T15:49:54Z | login: wesm
ID: MDU6SXNzdWUxMTAyMzY1 | Title: Optimized DataFrame.append for block structure if possible | State: CLOSED | Created: 2011-06-23T04:45:51Z | login: wesm
ID: MDU6SXNzdWUxMTIzODM0 | Title: fillna bug on ordered string data | State: CLOSED | Created: 2011-06-27T17:53:51Z | login: wesm
ID: MDU6SXNzdWUxMTY5NjE4 | Title: Some reverse binary operations fail with dtype=object | State: CLOSED | Created: 2011-07-05T19:50:00Z | login: wesm
ID: MDU6SXNzdWUxMjI0Mjgy | Title: fillna bug | State: CLOSED | Created: 2011-07-14T16:28:06Z | login: jiangs
ID: MDU6SXNzdWUxMjI4NDA2 | Title: setup.py | State: CLOSED | Created: 2011-07-15T04:51:09Z | login: ivanistheone
ID: MDU6SXNzdWUxMjMyNjgy | Title: Use Pdb.runcall() in debug() | State: CLOSED | Created: 2011-07-15T21:18:40Z | login: rkern
ID: MDU6SXNzdWUxMjMzMjQ5 | Title: Easier subclassing | State: CLOSED | Created: 2011-07-15T23:11:41Z | login: yonatanf
ID: MDU6SXNzdWUxMjM5Mzk4 | Title: DataFrame.__ne__ not implemented | State: CLOSED | Created: 2011-07-18T02:15:11Z | login: wesm
ID: MDU6SXNzdWUxMjQyNDE5 | Title: Add na_omit options to aggregation functions | State: CLOSED | Created: 2011-07-18T15:37:26Z | login: wesm
ID: MDU6SXNzdWUxMjQyNDIw | Title: Unit testing / cleanup of pandas.io.sql | State: CLOSED | Created: 2011-07-18T15:37:46Z | login: wesm
ID: MDU6SXNzdWUxMjQyNDM0 | Title: numpy.datetime64 type integration | State: CLOSED | Created: 2011-07-18T15:39:18Z | login: wesm
ID: MDU6SXNzdWUxMjQyNDU5 | Title: Add dot method to DataFrame | State: CLOSED | Created: 2011-07-18T15:43:35Z | login: wesm
ID: MDU6SXNzdWUxMjQyNDcz | Title: Fancy indexing on single column of DataFrame | State: CLOSED | Created: 2011-07-18T15:45:19Z | login: wesm
ID: MDU6SXNzdWUxMjQyNDgz | Title: Reindexing Cython code cleanup | State: CLOSED | Created: 2011-07-18T15:46:39Z | login: wesm
ID: MDU6SXNzdWUxMjQyNDky | Title: Import plyr-like functionality | State: CLOSED | Created: 2011-07-18T15:47:17Z | login: wesm
ID: MDU6SXNzdWUxMjQyNTAx | Title: Fancy indexing on WidePanel and n-dimensional version | State: CLOSED | Created: 2011-07-18T15:48:30Z | login: wesm
ID: MDU6SXNzdWUxMjQyNTEx | Title: Implement DataFrame.insert method | State: CLOSED | Created: 2011-07-18T15:49:35Z | login: wesm
ID: MDU6SXNzdWUxMjQyNTE3 | Title: Enable DataFrame constructor to accept structured/record ndarray | State: CLOSED | Created: 2011-07-18T15:50:10Z | login: wesm
ID: MDU6SXNzdWUxMjQyNTI5 | Title: Enable reindex methods to optionally not copy data when they can | State: CLOSED | Created: 2011-07-18T15:52:21Z | login: wesm
ID: MDU6SXNzdWUxMjQyNTQy | Title: Enable Series objects to optionally have a name associated with them | State: CLOSED | Created: 2011-07-18T15:54:10Z | login: wesm
ID: MDU6SXNzdWUxMjQyNTQ1 | Title: Test coverage for pandas.stats subpackage | State: CLOSED | Created: 2011-07-18T15:54:45Z | login: wesm
ID: MDU6SXNzdWUxMjQyNTk3 | Title: Heterogeneous type handling in LongPanel | State: CLOSED | Created: 2011-07-18T16:02:37Z | login: wesm
ID: MDU6SXNzdWUxMjQ1NTk3 | Title: Sparse cumsum functions do not work | State: CLOSED | Created: 2011-07-18T21:00:39Z | login: wesm
ID: MDU6SXNzdWUxMjY1MzY4 | Title: Build error on OS X 10.7: tseries | State: CLOSED | Created: 2011-07-21T19:32:25Z | login: fonnesbeck
ID: MDU6SXNzdWUxMjc4NTI1 | Title: Create HierarchicalIndex object to implement multi-level indexing | State: CLOSED | Created: 2011-07-24T20:08:48Z | login: wesm
ID: MDU6SXNzdWUxMjg2MDI5 | Title: groupby.pyx | State: CLOSED | Created: 2011-07-26T01:42:29Z | login: datakungfu
ID: MDU6SXNzdWUxMjg5NjM2 | Title: Some test data files don't get copied to site-packages | State: CLOSED | Created: 2011-07-26T15:41:00Z | login: wesm
ID: MDU6SXNzdWUxMjk5NjY1 | Title: bug in DataFrame/DataMatrix toCSV method when index=False | State: CLOSED | Created: 2011-07-27T23:02:15Z | login: changhiskhan
ID: MDU6SXNzdWUxMzAzNDIy | Title: ImportError: No module named tseries | State: CLOSED | Created: 2011-07-28T15:04:34Z | login: tomasholderness
ID: MDU6SXNzdWUxMzEwOTM5 | Title: [suggestion] example for pandas.DataFrame.pivot | State: CLOSED | Created: 2011-07-29T15:53:40Z | login: unpingco
ID: MDU6SXNzdWUxMzExMTQ0 | Title: Create memory-efficient DateIndex | State: CLOSED | Created: 2011-07-29T16:26:50Z | login: wesm
ID: MDU6SXNzdWUxMzEzMTM3 | Title: Enable pandas.core.sparse objects to be stored in HDFStore | State: CLOSED | Created: 2011-07-29T22:19:39Z | login: wesm
ID: MDU6SXNzdWUxMzEzNjg4 | Title: Push some of Series.ix into Series.__getitem__/__setitem__ | State: CLOSED | Created: 2011-07-30T01:01:42Z | login: wesm
ID: MDU6SXNzdWUxMzI1NTA0 | Title: [question] possible to use compound logic in indexing | State: CLOSED | Created: 2011-08-01T20:13:57Z | login: reckoner
ID: MDU6SXNzdWUxMzUxOTc4 | Title: Document panel {sum, mean, ...} methods | State: CLOSED | Created: 2011-08-05T15:46:35Z | login: wesm
ID: MDU6SXNzdWUxMzU5Njc3 | Title: build error on linux: common.pyx | State: CLOSED | Created: 2011-08-07T02:54:27Z | login: xdong
ID: MDU6SXNzdWUxMzYxNTg2 | Title: Change sum/mean/count/std/var/etc. to use bottleneck if available | State: CLOSED | Created: 2011-08-07T19:42:03Z | login: wesm
ID: MDU6SXNzdWUxMzYxODMz | Title: Enable DataFrame to be sorted by multiple columns | State: CLOSED | Created: 2011-08-07T20:57:42Z | login: wesm
ID: MDU6SXNzdWUxMzYxODQ1 | Title: Improve Cython multi-groupby code to do aggregation without having to sort the data | State: CLOSED | Created: 2011-08-07T21:01:30Z | login: wesm
ID: MDU6SXNzdWUxMzYxODYy | Title: Make DataFrame toString formatting use precision set in numpy.set_printoptions | State: CLOSED | Created: 2011-08-07T21:08:46Z | login: wesm
ID: MDU6SXNzdWUxMzY5NzQ3 | Title: Implement GroupBy __len__ to return number of resulting groups | State: CLOSED | Created: 2011-08-09T02:25:36Z | login: bburan
ID: MDU6SXNzdWUxMzczOTM4 | Title: Write Cython function to determine sort order in hierarchical indexes | State: CLOSED | Created: 2011-08-09T17:29:47Z | login: wesm
ID: MDU6SXNzdWUxMzc0MzA5 | Title: Problem with Series.plot | State: CLOSED | Created: 2011-08-09T18:25:40Z | login: dieterv77
ID: MDU6SXNzdWUxMzc1Mzc0 | Title: Calling xs on DataFrame with index but no columns raises Exception | State: CLOSED | Created: 2011-08-09T20:53:42Z | login: wesm
ID: MDU6SXNzdWUxMzc2MTc2 | Title: Bring back .groups attribute for GroupBy | State: CLOSED | Created: 2011-08-09T22:51:30Z | login: wesm
ID: MDU6SXNzdWUxMzc2NzAz | Title: Remove AmbiguousIndexError in fancy indexing | State: CLOSED | Created: 2011-08-10T00:51:55Z | login: wesm
ID: MDU6SXNzdWUxNDA5MTc4 | Title: Enable .drop(...) to work with MultiIndex | State: CLOSED | Created: 2011-08-15T17:36:34Z | login: wesm
ID: MDU6SXNzdWUxNDE3MzY1 | Title: pandas.stats.interface.ols broken in 0.4 from 0.3 | State: CLOSED | Created: 2011-08-16T18:51:21Z | login: jdmarino
ID: MDU6SXNzdWUxNDI1NDk0 | Title: Enable groupby multiple levels (instead of just a single level) | State: CLOSED | Created: 2011-08-17T19:04:13Z | login: wesm
ID: MDU6SXNzdWUxNDM1NjI3 | Title: Implement ndarray.take analog on BlockManager | State: CLOSED | Created: 2011-08-18T21:48:22Z | login: wesm
ID: MDU6SXNzdWUxNDQ1MTM2 | Title: ols should handle a Series (w/ MultiIndex) + LongPanel combo. | State: CLOSED | Created: 2011-08-19T17:04:42Z | login: craustin

## Web Scraping

In [10]:
import requests
from bs4 import BeautifulSoup

In [164]:
r = requests.get("https://www.scrapethissite.com/pages/simple/")

In [165]:
r.status_code

200

In [166]:
type(r.text)

str

In [167]:
print(r.text)

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Countries of the World: A Simple Example | Scrape This Site | A public sandbox for learning web scraping</title>
    <link rel="icon" type="image/png" href="/static/images/scraper-icon.png" />

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="A single page that lists information about all the countries in the world. Good for those just get started with web scraping.">

    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet" integrity="sha256-MfvZlkHCEqatNoGiOXveE8FIwMzZg4W85qfrfIFBfYc= sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" crossorigin="anonymous">
    <link href='https://fonts.googleapis.com/css?family=Lato:400,700' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="/static/css/styles.css">


<meta name="robots" content="noindex">
<link href="https://lipis.github.io/flag-icon-css/css/flag-icon.css" rel="stylesheet">


  </head>

  <body>
    <nav id="site-nav">
            <div class="container">
                <div class="col-md-12">
                    <ul class="nav nav-tabs">
                        <li id="nav-homepage">
                            <a href="/" class="nav-link hidden-sm hidden-xs">
                                <img src="/static/images/scraper-icon.png" id="nav-logo">
                                Scrape This Site
                            </a>
                        </li>
                        <li id="nav-sandbox">
                            <a href="/pages/" class="nav-link">
                                <i class="glyphicon glyphicon-console hidden-sm hidden-xs"></i>
                                Sandbox
                            </a>
                        </li>
                        <li id="nav-lessons">
                            <a href="/lessons/" class="nav-link">
                                <i class="glyphicon glyphicon-education hidden-sm hidden-xs"></i>
                                Lessons
                            </a>
                        </li>
                        <li id="nav-faq">
                            <a href="/faq/" class="nav-link">
                                <i class="glyphicon glyphicon-flag hidden-sm hidden-xs"></i>
                                FAQ
                            </a>
                        </li>

                        <li id="nav-login" class="pull-right">
                            <a href="/login/" class="nav-link">
                                Login
                            </a>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>

        <script type="text/javascript">
            var path = document.location.pathname;
            var tab = undefined;
            if (path === "/"){
                tab = document.querySelector("#nav-homepage");
            } else if (path.indexOf("/faq/") === 0){
                tab = document.querySelector("#nav-faq");
            } else if (path.indexOf("/lessons/") === 0){
                tab = document.querySelector("#nav-lessons");
            } else if (path.indexOf("/pages/") === 0) {
                tab = document.querySelector("#nav-sandbox");
            } else if (path.indexOf("/login/") === 0) {
                tab = document.querySelector("#nav-login");
            }
            tab.classList.add("active")
        </script>



    <div id="page">

        <section id="countries">
            <div class="container">

                <div class="row">
                    <div class="col-md-12">
                        <h1>
                            Countries of the World: A Simple Example
                            <small>250 items</small>
                        </h1>
                        <hr />
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <p class="lead">
                            A single page that lists information about all the countries in the world. Good for those just get started with web scraping.
                            Practice looking for patterns in the HTML that will allow you to extract information about each country. Then, build a simple web scraper that makes a request to this page, parses the HTML and prints out each country&#39;s name.
                        </p>
                        <hr />
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <p>
                            <i class="glyphicon glyphicon-education"></i> There are <a href="/lessons/">4 video lessons</a> that show you how to scrape this page.
                        </p>
                        <hr />
                    </div>
                    <div class="col-md-6 text-right">
                        <p>

                                Data via
                                <a href="http://peric.github.io/GetCountries/" class="data-attribution" target="_blank">http://peric.github.io/GetCountries/</a>

                        </p>
                        <hr />
                    </div>
                </div>

                <div class="row">

                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-ad"></i>
                            Andorra
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Andorra la Vella</span><br>
                            <strong>Population:</strong> <span class="country-population">84000</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">468.0</span><br>
                        </div>
                    </div><!--.col-->



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-ae"></i>
                            United Arab Emirates
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Abu Dhabi</span><br>
                            <strong>Population:</strong> <span class="country-population">4975593</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">82880.0</span><br>
                        </div>
                    </div><!--.col-->



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-af"></i>
                            Afghanistan
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Kabul</span><br>
                            <strong>Population:</strong> <span class="country-population">29121286</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">647500.0</span><br>
                        </div>
                    </div><!--.col-->

                </div><!--.row-->
                <div class="row">



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-ag"></i>
                            Antigua and Barbuda
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">St. John&#39;s</span><br>
                            <strong>Population:</strong> <span class="country-population">86754</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">443.0</span><br>
                        </div>
                    </div><!--.col-->



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-ai"></i>
                            Anguilla
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">The Valley</span><br>
                            <strong>Population:</strong> <span class="country-population">13254</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">102.0</span><br>
                        </div>
                    </div><!--.col-->



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-al"></i>
                            Albania
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Tirana</span><br>
                            <strong>Population:</strong> <span class="country-population">2986952</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">28748.0</span><br>
                        </div>
                    </div><!--.col-->

                </div><!--.row-->
                <div class="row">



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-am"></i>
                            Armenia
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Yerevan</span><br>
                            <strong>Population:</strong> <span class="country-population">2968000</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">29800.0</span><br>
                        </div>
                    </div><!--.col-->



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-ao"></i>
                            Angola
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Luanda</span><br>
                            <strong>Population:</strong> <span class="country-population">13068161</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1246700.0</span><br>
                        </div>
                    </div><!--.col-->



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-aq"></i>
                            Antarctica
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">None</span><br>
                            <strong>Population:</strong> <span class="country-population">0</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1.4E7</span><br>
                        </div>
                    </div><!--.col-->

                </div><!--.row-->
                <div class="row">



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-ar"></i>
                            Argentina
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Buenos Aires</span><br>
                            <strong>Population:</strong> <span class="country-population">41343201</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">2766890.0</span><br>
                        </div>
                    </div><!--.col-->



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-as"></i>
                            American Samoa
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Pago Pago</span><br>
                            <strong>Population:</strong> <span class="country-population">57881</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">199.0</span><br>
                        </div>
                    </div><!--.col-->



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-at"></i>
                            Austria
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Vienna</span><br>
                            <strong>Population:</strong> <span class="country-population">8205000</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">83858.0</span><br>
                        </div>
                    </div><!--.col-->

                </div><!--.row-->
                <div class="row">



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-au"></i>
                            Australia
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Canberra</span><br>
                            <strong>Population:</strong> <span class="country-population">21515754</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">7686850.0</span><br>
                        </div>
                    </div><!--.col-->



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-aw"></i>
                            Aruba
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Oranjestad</span><br>
                            <strong>Population:</strong> <span class="country-population">71566</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">193.0</span><br>
                        </div>
                    </div><!--.col-->



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-ax"></i>
                            Åland
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Mariehamn</span><br>
                            <strong>Population:</strong> <span class="country-population">26711</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1580.0</span><br>
                        </div>
                    </div><!--.col-->

                </div><!--.row-->
                <div class="row">



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-az"></i>
                            Azerbaijan
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Baku</span><br>
                            <strong>Population:</strong> <span class="country-population">8303512</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">86600.0</span><br>
                        </div>
                    </div><!--.col-->



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-ba"></i>
                            Bosnia and Herzegovina
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Sarajevo</span><br>
                            <strong>Population:</strong> <span class="country-population">4590000</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">51129.0</span><br>
                        </div>
                    </div><!--.col-->



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-bb"></i>
                            Barbados
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Bridgetown</span><br>
                            <strong>Population:</strong> <span class="country-population">285653</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">431.0</span><br>
                        </div>
                    </div><!--.col-->

                </div><!--.row-->
                <div class="row">



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-bd"></i>
                            Bangladesh
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Dhaka</span><br>
                            <strong>Population:</strong> <span class="country-population">156118464</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">144000.0</span><br>
                        </div>
                    </div><!--.col-->



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-be"></i>
                            Belgium
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Brussels</span><br>
                            <strong>Population:</strong> <span class="country-population">10403000</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">30510.0</span><br>
                        </div>
                    </div><!--.col-->



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-bf"></i>
                            Burkina Faso
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Ouagadougou</span><br>

We will use BeautifulSoup to parse the HTML above. There are many parsers available. The default parser is `html.parser`, it does not require any additional installation. However, its performance is not the best. If you want better performance, you can use `lxml` parser. Refer to [here](https://beautiful-soup-4.readthedocs.io/en/latest/index.html?highlight=get#installing-a-parser) for more info.

In [168]:
soup = BeautifulSoup(r.text, "html.parser")

We can look for all paragraphs in the page using the `find_all` method. This returns a list of all the paragraph `Tag`s in the page.

Refer to the [documentation](https://www.crummy.com/software/BeautifulSoup/bs4/doc/#bs4.Tag) for more details.

In [170]:
paragraphs = soup.find_all('p')

In [171]:
len(paragraphs)

3

In [172]:
type(paragraphs[0])

bs4.element.Tag

In [173]:
paragraphs[0]

<p class="lead">
                            A single page that lists information about all the countries in the world. Good for those just get started with web scraping.
                            Practice looking for patterns in the HTML that will allow you to extract information about each country. Then, build a simple web scraper that makes a request to this page, parses the HTML and prints out each country's name.
                        </p>

In [174]:
# get the actual text
paragraphs[0].text

"\n                            A single page that lists information about all the countries in the world. Good for those just get started with web scraping.\n                            Practice looking for patterns in the HTML that will allow you to extract information about each country. Then, build a simple web scraper that makes a request to this page, parses the HTML and prints out each country's name.\n                        "

We can find all the country names in the HTML by specifying the tag and class name. It is always good to be as specific as possible when selecting elements. This is because the more specific you are, the less likely you will select other unintended elements.

In [175]:
country_name_elements = soup.find_all('h3', 'country-name')

or equivalently

`soup.find_all('h3', class_='country-name')`

In [176]:
country_name_elements

[<h3 class="country-name">
 <i class="flag-icon flag-icon-ad"></i>
                             Andorra
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ae"></i>
                             United Arab Emirates
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-af"></i>
                             Afghanistan
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ag"></i>
                             Antigua and Barbuda
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ai"></i>
                             Anguilla
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-al"></i>
                             Albania
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-am"></i>
                             Armenia
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ao"></i>
                             Angola
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-aq"></i>
                             Antarctica
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ar"></i>
                             Argentina
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-as"></i>
                             American Samoa
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-at"></i>
                             Austria
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-au"></i>
                             Australia
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-aw"></i>
                             Aruba
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ax"></i>
                             Åland
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-az"></i>
                             Azerbaijan
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ba"></i>
                             Bosnia and Herzegovina
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bb"></i>
                             Barbados
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bd"></i>
                             Bangladesh
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-be"></i>
                             Belgium
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bf"></i>
                             Burkina Faso
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bg"></i>
                             Bulgaria
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bh"></i>
                             Bahrain
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bi"></i>
                             Burundi
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bj"></i>
                             Benin
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bl"></i>
                             Saint Barthélemy
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bm"></i>
                             Bermuda
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bn"></i>
                             Brunei
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bo"></i>
                             Bolivia
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bq"></i>
                             Bonaire
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-br"></i>
                             Brazil
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bs"></i>
                             Bahamas
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bt"></i>
                             Bhutan
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bv"></i>
                             Bouvet Island
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bw"></i>
                             Botswana
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-by"></i>
                             Belarus
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bz"></i>
                             Belize
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ca"></i>
                             Canada
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-cc"></i>
                             Cocos [Keeling] Islands
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-cd"></i>
                             Democratic Republic of the Congo
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-cf"></i>
                             Central African Republic
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-cg"></i>
                             Republic of the Congo
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ch"></i>
                             Switzerland
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ci"></i>
                             Ivory Coast
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ck"></i>
                             Cook Islands
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-cl"></i>
                             Chile
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-cm"></i>
                             Cameroon
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-cn"></i>
                             China
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-co"></i>
                             Colombia
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-cr"></i>
                             Costa Rica
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-cu"></i>
                             Cuba
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-cv"></i>
                             Cape Verde
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-cw"></i>
                             Curacao
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-cx"></i>
                             Christmas Island
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-cy"></i>
                             Cyprus
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-cz"></i>
                             Czech Republic
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-de"></i>
                             Germany
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-dj"></i>
                             Djibouti
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-dk"></i>
                             Denmark
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-dm"></i>
                             Dominica
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-do"></i>
                             Dominican Republic
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-dz"></i>
                             Algeria
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ec"></i>
                             Ecuador
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ee"></i>
                             Estonia
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-eg"></i>
                             Egypt
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-eh"></i>
                             Western Sahara
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-er"></i>
                             Eritrea
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-es"></i>
                             Spain
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-et"></i>
                             Ethiopia
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-fi"></i>
                             Finland
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-fj"></i>
                             Fiji
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-fk"></i>
                             Falkland Islands
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-fm"></i>
                             Micronesia
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-fo"></i>
                             Faroe Islands
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-fr"></i>
                             France
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ga"></i>
                             Gabon
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-gb"></i>
                             United Kingdom
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-gd"></i>
                             Grenada
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ge"></i>
                             Georgia
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-gf"></i>
                             French Guiana
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-gg"></i>
                             Guernsey
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-gh"></i>
                             Ghana
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-gi"></i>
                             Gibraltar
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-gl"></i>
                             Greenland
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-gm"></i>
                             Gambia
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-gn"></i>
                             Guinea
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-gp"></i>
                             Guadeloupe
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-gq"></i>
                             Equatorial Guinea
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-gr"></i>
                             Greece
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-gs"></i>
                             South Georgia and the South Sandwich Islands
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-gt"></i>
                             Guatemala
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-gu"></i>
                             Guam
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-gw"></i>
                             Guinea-Bissau
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-gy"></i>
                             Guyana
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-hk"></i>
                             Hong Kong
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-hm"></i>
                             Heard Island and McDonald Islands
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-hn"></i>
                             Honduras
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-hr"></i>
                             Croatia
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ht"></i>
                             Haiti
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-hu"></i>
                             Hungary
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-id"></i>
                             Indonesia
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ie"></i>
                             Ireland
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-il"></i>
                             Israel
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-im"></i>
                             Isle of Man
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-in"></i>
                             India
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-io"></i>
                             British Indian Ocean Territory
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-iq"></i>
                             Iraq
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ir"></i>
                             Iran
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-is"></i>
                             Iceland
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-it"></i>
                             Italy
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-je"></i>
                             Jersey
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-jm"></i>
                             Jamaica
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-jo"></i>
                             Jordan
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-jp"></i>
                             Japan
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ke"></i>
                             Kenya
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-kg"></i>
                             Kyrgyzstan
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-kh"></i>
                             Cambodia
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ki"></i>
                             Kiribati
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-km"></i>
                             Comoros
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-kn"></i>
                             Saint Kitts and Nevis
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-kp"></i>
                             North Korea
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-kr"></i>
                             South Korea
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-kw"></i>
                             Kuwait
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ky"></i>
                             Cayman Islands
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-kz"></i>
                             Kazakhstan
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-la"></i>
                             Laos
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-lb"></i>
                             Lebanon
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-lc"></i>
                             Saint Lucia
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-li"></i>
                             Liechtenstein
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-lk"></i>
                             Sri Lanka
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-lr"></i>
                             Liberia
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ls"></i>
                             Lesotho
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-lt"></i>
                             Lithuania
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-lu"></i>
                             Luxembourg
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-lv"></i>
                             Latvia
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ly"></i>
                             Libya
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ma"></i>
                             Morocco
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-mc"></i>
                             Monaco
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-md"></i>
                             Moldova
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-me"></i>
                             Montenegro
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-mf"></i>
                             Saint Martin
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-mg"></i>
                             Madagascar
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-mh"></i>
                             Marshall Islands
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-mk"></i>
                             Macedonia
                         </h3>,
 <h3 class="country-name">

> Extract just the country names string into a new list called `country_names`. Remove all whitespaces.
>
> Your results should be starting with `['Andorra', 'United Arab Emirates', 'Afghanistan', 'Antigua and Barbuda', ...]`

In [184]:
country_name_elements = soup.find_all('h3', 'country-name')

In [185]:
country_name_elements

[<h3 class="country-name">
 <i class="flag-icon flag-icon-ad"></i>
                             Andorra
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ae"></i>
                             United Arab Emirates
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-af"></i>
                             Afghanistan
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ag"></i>
                             Antigua and Barbuda
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ai"></i>
                             Anguilla
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-al"></i>
                             Albania
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-am"></i>
                             Armenia
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ao"></i>
                             Angola
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-aq"></i>
                             Antarctica
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ar"></i>
                             Argentina
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-as"></i>
                             American Samoa
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-at"></i>
                             Austria
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-au"></i>
                             Australia
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-aw"></i>
                             Aruba
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ax"></i>
                             Åland
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-az"></i>
                             Azerbaijan
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ba"></i>
                             Bosnia and Herzegovina
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bb"></i>
                             Barbados
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bd"></i>
                             Bangladesh
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-be"></i>
                             Belgium
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bf"></i>
                             Burkina Faso
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bg"></i>
                             Bulgaria
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bh"></i>
                             Bahrain
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bi"></i>
                             Burundi
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bj"></i>
                             Benin
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bl"></i>
                             Saint Barthélemy
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bm"></i>
                             Bermuda
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bn"></i>
                             Brunei
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bo"></i>
                             Bolivia
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bq"></i>
                             Bonaire
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-br"></i>
                             Brazil
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bs"></i>
                             Bahamas
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bt"></i>
                             Bhutan
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bv"></i>
                             Bouvet Island
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bw"></i>
                             Botswana
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-by"></i>
                             Belarus
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bz"></i>
                             Belize
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ca"></i>
                             Canada
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-cc"></i>
                             Cocos [Keeling] Islands
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-cd"></i>
                             Democratic Republic of the Congo
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-cf"></i>
                             Central African Republic
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-cg"></i>
                             Republic of the Congo
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ch"></i>
                             Switzerland
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ci"></i>
                             Ivory Coast
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ck"></i>
                             Cook Islands
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-cl"></i>
                             Chile
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-cm"></i>
                             Cameroon
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-cn"></i>
                             China
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-co"></i>
                             Colombia
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-cr"></i>
                             Costa Rica
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-cu"></i>
                             Cuba
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-cv"></i>
                             Cape Verde
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-cw"></i>
                             Curacao
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-cx"></i>
                             Christmas Island
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-cy"></i>
                             Cyprus
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-cz"></i>
                             Czech Republic
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-de"></i>
                             Germany
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-dj"></i>
                             Djibouti
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-dk"></i>
                             Denmark
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-dm"></i>
                             Dominica
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-do"></i>
                             Dominican Republic
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-dz"></i>
                             Algeria
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ec"></i>
                             Ecuador
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ee"></i>
                             Estonia
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-eg"></i>
                             Egypt
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-eh"></i>
                             Western Sahara
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-er"></i>
                             Eritrea
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-es"></i>
                             Spain
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-et"></i>
                             Ethiopia
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-fi"></i>
                             Finland
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-fj"></i>
                             Fiji
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-fk"></i>
                             Falkland Islands
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-fm"></i>
                             Micronesia
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-fo"></i>
                             Faroe Islands
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-fr"></i>
                             France
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ga"></i>
                             Gabon
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-gb"></i>
                             United Kingdom
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-gd"></i>
                             Grenada
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ge"></i>
                             Georgia
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-gf"></i>
                             French Guiana
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-gg"></i>
                             Guernsey
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-gh"></i>
                             Ghana
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-gi"></i>
                             Gibraltar
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-gl"></i>
                             Greenland
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-gm"></i>
                             Gambia
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-gn"></i>
                             Guinea
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-gp"></i>
                             Guadeloupe
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-gq"></i>
                             Equatorial Guinea
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-gr"></i>
                             Greece
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-gs"></i>
                             South Georgia and the South Sandwich Islands
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-gt"></i>
                             Guatemala
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-gu"></i>
                             Guam
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-gw"></i>
                             Guinea-Bissau
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-gy"></i>
                             Guyana
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-hk"></i>
                             Hong Kong
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-hm"></i>
                             Heard Island and McDonald Islands
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-hn"></i>
                             Honduras
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-hr"></i>
                             Croatia
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ht"></i>
                             Haiti
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-hu"></i>
                             Hungary
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-id"></i>
                             Indonesia
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ie"></i>
                             Ireland
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-il"></i>
                             Israel
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-im"></i>
                             Isle of Man
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-in"></i>
                             India
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-io"></i>
                             British Indian Ocean Territory
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-iq"></i>
                             Iraq
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ir"></i>
                             Iran
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-is"></i>
                             Iceland
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-it"></i>
                             Italy
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-je"></i>
                             Jersey
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-jm"></i>
                             Jamaica
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-jo"></i>
                             Jordan
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-jp"></i>
                             Japan
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ke"></i>
                             Kenya
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-kg"></i>
                             Kyrgyzstan
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-kh"></i>
                             Cambodia
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ki"></i>
                             Kiribati
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-km"></i>
                             Comoros
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-kn"></i>
                             Saint Kitts and Nevis
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-kp"></i>
                             North Korea
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-kr"></i>
                             South Korea
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-kw"></i>
                             Kuwait
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ky"></i>
                             Cayman Islands
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-kz"></i>
                             Kazakhstan
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-la"></i>
                             Laos
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-lb"></i>
                             Lebanon
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-lc"></i>
                             Saint Lucia
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-li"></i>
                             Liechtenstein
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-lk"></i>
                             Sri Lanka
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-lr"></i>
                             Liberia
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ls"></i>
                             Lesotho
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-lt"></i>
                             Lithuania
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-lu"></i>
                             Luxembourg
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-lv"></i>
                             Latvia
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ly"></i>
                             Libya
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ma"></i>
                             Morocco
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-mc"></i>
                             Monaco
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-md"></i>
                             Moldova
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-me"></i>
                             Montenegro
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-mf"></i>
                             Saint Martin
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-mg"></i>
                             Madagascar
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-mh"></i>
                             Marshall Islands
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-mk"></i>
                             Macedonia
                         </h3>,
 <h3 class="country-name">

In [188]:


country_names = []

# Loop through each h3 element individually
for element in country_name_elements:
    # Find the <i> tag inside this specific <h3>
   
        # Extract the clean text inside the <i> tag
        country_names.append(element.text.strip())
        

print(country_names)

['Andorra', 'United Arab Emirates', 'Afghanistan', 'Antigua and Barbuda', 'Anguilla', 'Albania', 'Armenia', 'Angola', 'Antarctica', 'Argentina', 'American Samoa', 'Austria', 'Australia', 'Aruba', 'Åland', 'Azerbaijan', 'Bosnia and Herzegovina', 'Barbados', 'Bangladesh', 'Belgium', 'Burkina Faso', 'Bulgaria', 'Bahrain', 'Burundi', 'Benin', 'Saint Barthélemy', 'Bermuda', 'Brunei', 'Bolivia', 'Bonaire', 'Brazil', 'Bahamas', 'Bhutan', 'Bouvet Island', 'Botswana', 'Belarus', 'Belize', 'Canada', 'Cocos [Keeling] Islands', 'Democratic Republic of the Congo', 'Central African Republic', 'Republic of the Congo', 'Switzerland', 'Ivory Coast', 'Cook Islands', 'Chile', 'Cameroon', 'China', 'Colombia', 'Costa Rica', 'Cuba', 'Cape Verde', 'Curacao', 'Christmas Island', 'Cyprus', 'Czech Republic', 'Germany', 'Djibouti', 'Denmark', 'Dominica', 'Dominican Republic', 'Algeria', 'Ecuador', 'Estonia', 'Egypt', 'Western Sahara', 'Eritrea', 'Spain', 'Ethiopia', 'Finland', 'Fiji', 'Falkland Islands', 'Micronesia', 'Faroe Islands', 'France', 'Gabon', 'United Kingdom', 'Grenada', 'Georgia', 'French Guiana', 'Guernsey', 'Ghana', 'Gibraltar', 'Greenland', 'Gambia', 'Guinea', 'Guadeloupe', 'Equatorial Guinea', 'Greece', 'South Georgia and the South Sandwich Islands', 'Guatemala', 'Guam', 'Guinea-Bissau', 'Guyana', 'Hong Kong', 'Heard Island and McDonald Islands', 'Honduras', 'Croatia', 'Haiti', 'Hungary', 'Indonesia', 'Ireland', 'Israel', 'Isle of Man', 'India', 'British Indian Ocean Territory', 'Iraq', 'Iran', 'Iceland', 'Italy', 'Jersey', 'Jamaica', 'Jordan', 'Japan', 'Kenya', 'Kyrgyzstan', 'Cambodia', 'Kiribati', 'Comoros', 'Saint Kitts and Nevis', 'North Korea', 'South Korea', 'Kuwait', 'Cayman Islands', 'Kazakhstan', 'Laos', 'Lebanon', 'Saint Lucia', 'Liechtenstein', 'Sri Lanka', 'Liberia', 'Lesotho', 'Lithuania', 'Luxembourg', 'Latvia', 'Libya', 'Morocco', 'Monaco', 'Moldova', 'Montenegro', 'Saint Martin', 'Madagascar', 'Marshall Islands', 'Macedonia', 'Mali', 'Myanmar [Burma]', 'Mongolia', 'Macao', 'Northern Mariana Islands', 'Martinique', 'Mauritania', 'Montserrat', 'Malta', 'Mauritius', 'Maldives', 'Malawi', 'Mexico', 'Malaysia', 'Mozambique', 'Namibia', 'New Caledonia', 'Niger', 'Norfolk Island', 'Nigeria', 'Nicaragua', 'Netherlands', 'Norway', 'Nepal', 'Nauru', 'Niue', 'New Zealand', 'Oman', 'Panama', 'Peru', 'French Polynesia', 'Papua New Guinea', 'Philippines', 'Pakistan', 'Poland', 'Saint Pierre and Miquelon', 'Pitcairn Islands', 'Puerto Rico', 'Palestine', 'Portugal', 'Palau', 'Paraguay', 'Qatar', 'Réunion', 'Romania', 'Serbia', 'Russia', 'Rwanda', 'Saudi Arabia', 'Solomon Islands', 'Seychelles', 'Sudan', 'Sweden', 'Singapore', 'Saint Helena', 'Slovenia', 'Svalbard and Jan Mayen', 'Slovakia', 'Sierra Leone', 'San Marino', 'Senegal', 'Somalia', 'Suriname', 'South Sudan', 'São Tomé and Príncipe', 'El Salvador', 'Sint Maarten', 'Syria', 'Swaziland', 'Turks and Caicos Islands', 'Chad', 'French Southern Territories', 'Togo', 'Thailand', 'Tajikistan', 'Tokelau', 'East Timor', 'Turkmenistan', 'Tunisia', 'Tonga', 'Turkey', 'Trinidad and Tobago', 'Tuvalu', 'Taiwan', 'Tanzania', 'Ukraine', 'Uganda', 'U.S. Minor Outlying Islands', 'United States', 'Uruguay', 'Uzbekistan', 'Vatican City', 'Saint Vincent and the Grenadines', 'Venezuela', 'British Virgin Islands', 'U.S. Virgin Islands', 'Vietnam', 'Vanuatu', 'Wallis and Futuna', 'Samoa', 'Kosovo', 'Yemen', 'Mayotte', 'South Africa', 'Zambia', 'Zimbabwe']

> Extract the capitals into a new list called `capital_names`.

It is common to collect all the required information at one go. For each country element, you can further use the `find` method to extract the child element.

Let's collect the capital, population and area for each country.

In [189]:
countries = []
for country in soup.find_all('div', 'col-md-4 country'):
    country_info = {}
    country_info['name'] = country.find('h3').text.strip()
    country_info['capital'] = country.find('span', 'country-capital').text
    country_info['population'] = country.find('span', 'country-population').text
    country_info['area_km2'] = country.find('span', 'country-area').text
    countries.append(country_info)

In [190]:
countries

[{'name': 'Andorra',
  'capital': 'Andorra la Vella',
  'population': '84000',
  'area_km2': '468.0'},
 {'name': 'United Arab Emirates',
  'capital': 'Abu Dhabi',
  'population': '4975593',
  'area_km2': '82880.0'},
 {'name': 'Afghanistan',
  'capital': 'Kabul',
  'population': '29121286',
  'area_km2': '647500.0'},
 {'name': 'Antigua and Barbuda',
  'capital': "St. John's",
  'population': '86754',
  'area_km2': '443.0'},
 {'name': 'Anguilla',
  'capital': 'The Valley',
  'population': '13254',
  'area_km2': '102.0'},
 {'name': 'Albania',
  'capital': 'Tirana',
  'population': '2986952',
  'area_km2': '28748.0'},
 {'name': 'Armenia',
  'capital': 'Yerevan',
  'population': '2968000',
  'area_km2': '29800.0'},
 {'name': 'Angola',
  'capital': 'Luanda',
  'population': '13068161',
  'area_km2': '1246700.0'},
 {'name': 'Antarctica',
  'capital': 'None',
  'population': '0',
  'area_km2': '1.4E7'},
 {'name': 'Argentina',
  'capital': 'Buenos Aires',
  'population': '41343201',
  'area_km2': '2766890.0'},
 {'name': 'American Samoa',
  'capital': 'Pago Pago',
  'population': '57881',
  'area_km2': '199.0'},
 {'name': 'Austria',
  'capital': 'Vienna',
  'population': '8205000',
  'area_km2': '83858.0'},
 {'name': 'Australia',
  'capital': 'Canberra',
  'population': '21515754',
  'area_km2': '7686850.0'},
 {'name': 'Aruba',
  'capital': 'Oranjestad',
  'population': '71566',
  'area_km2': '193.0'},
 {'name': 'Åland',
  'capital': 'Mariehamn',
  'population': '26711',
  'area_km2': '1580.0'},
 {'name': 'Azerbaijan',
  'capital': 'Baku',
  'population': '8303512',
  'area_km2': '86600.0'},
 {'name': 'Bosnia and Herzegovina',
  'capital': 'Sarajevo',
  'population': '4590000',
  'area_km2': '51129.0'},
 {'name': 'Barbados',
  'capital': 'Bridgetown',
  'population': '285653',
  'area_km2': '431.0'},
 {'name': 'Bangladesh',
  'capital': 'Dhaka',
  'population': '156118464',
  'area_km2': '144000.0'},
 {'name': 'Belgium',
  'capital': 'Brussels',
  'population': '10403000',
  'area_km2': '30510.0'},
 {'name': 'Burkina Faso',
  'capital': 'Ouagadougou',
  'population': '16241811',
  'area_km2': '274200.0'},
 {'name': 'Bulgaria',
  'capital': 'Sofia',
  'population': '7148785',
  'area_km2': '110910.0'},
 {'name': 'Bahrain',
  'capital': 'Manama',
  'population': '738004',
  'area_km2': '665.0'},
 {'name': 'Burundi',
  'capital': 'Bujumbura',
  'population': '9863117',
  'area_km2': '27830.0'},
 {'name': 'Benin',
  'capital': 'Porto-Novo',
  'population': '9056010',
  'area_km2': '112620.0'},
 {'name': 'Saint Barthélemy',
  'capital': 'Gustavia',
  'population': '8450',
  'area_km2': '21.0'},
 {'name': 'Bermuda',
  'capital': 'Hamilton',
  'population': '65365',
  'area_km2': '53.0'},
 {'name': 'Brunei',
  'capital': 'Bandar Seri Begawan',
  'population': '395027',
  'area_km2': '5770.0'},
 {'name': 'Bolivia',
  'capital': 'Sucre',
  'population': '9947418',
  'area_km2': '1098580.0'},
 {'name': 'Bonaire',
  'capital': 'Kralendijk',
  'population': '18012',
  'area_km2': '328.0'},
 {'name': 'Brazil',
  'capital': 'Brasília',
  'population': '201103330',
  'area_km2': '8511965.0'},
 {'name': 'Bahamas',
  'capital': 'Nassau',
  'population': '301790',
  'area_km2': '13940.0'},
 {'name': 'Bhutan',
  'capital': 'Thimphu',
  'population': '699847',
  'area_km2': '47000.0'},
 {'name': 'Bouvet Island',
  'capital': 'None',
  'population': '0',
  'area_km2': '49.0'},
 {'name': 'Botswana',
  'capital': 'Gaborone',
  'population': '2029307',
  'area_km2': '600370.0'},
 {'name': 'Belarus',
  'capital': 'Minsk',
  'population': '9685000',
  'area_km2': '207600.0'},
 {'name': 'Belize',
  'capital': 'Belmopan',
  'population': '314522',
  'area_km2': '22966.0'},
 {'name': 'Canada',
  'capital': 'Ottawa',
  'population': '33679000',
  'area_km2': '9984670.0'},
 {'name': 'Cocos [Keeling] Islands',
  'capital': 'West Island',
  'population': '628',
  'area_km2': '14.0'},
 {'name': 'Democratic Republic of the Congo',
  'capital': 'Kinshasa',
  'population': '70916439',
  'area_km2': '2345410.0'},
 {'name': 'Central African Republic',
  'capital': 'Bangui',
  'population': '4844927',
  'area_km2': '622984.0'},
 {'name': 'Republic of the Congo',
  'capital': 'Brazzaville',
  'population': '3039126',
  'area_km2': '342000.0'},
 {'name': 'Switzerland',
  'capital': 'Bern',
  'population': '7581000',
  'area_km2': '41290.0'},
 {'name': 'Ivory Coast',
  'capital': 'Yamoussoukro',
  'population': '21058798',
  'area_km2': '322460.0'},
 {'name': 'Cook Islands',
  'capital': 'Avarua',
  'population': '21388',
  'area_km2': '240.0'},
 {'name': 'Chile',
  'capital': 'Santiago',
  'population': '16746491',
  'area_km2': '756950.0'},
 {'name': 'Cameroon',
  'capital': 'Yaoundé',
  'population': '19294149',
  'area_km2': '475440.0'},
 {'name': 'China',
  'capital': 'Beijing',
  'population': '1330044000',
  'area_km2': '9596960.0'},
 {'name': 'Colombia',
  'capital': 'Bogotá',
  'population': '47790000',
  'area_km2': '1138910.0'},
 {'name': 'Costa Rica',
  'capital': 'San José',
  'population': '4516220',
  'area_km2': '51100.0'},
 {'name': 'Cuba',
  'capital': 'Havana',
  'population': '11423000',
  'area_km2': '110860.0'},
 {'name': 'Cape Verde',
  'capital': 'Praia',
  'population': '508659',
  'area_km2': '4033.0'},
 {'name': 'Curacao',
  'capital': 'Willemstad',
  'population': '141766',
  'area_km2': '444.0'},
 {'name': 'Christmas Island',
  'capital': 'Flying Fish Cove',
  'population': '1500',
  'area_km2': '135.0'},
 {'name': 'Cyprus',
  'capital': 'Nicosia',
  'population': '1102677',
  'area_km2': '9250.0'},
 {'name': 'Czech Republic',
  'capital': 'Prague',
  'population': '10476000',
  'area_km2': '78866.0'},
 {'name': 'Germany',
  'capital': 'Berlin',
  'population': '81802257',
  'area_km2': '357021.0'},
 {'name': 'Djibouti',
  'capital': 'Djibouti',
  'population': '740528',
  'area_km2': '23000.0'},
 {'name': 'Denmark',
  'capital': 'Copenhagen',
  'population': '5484000',
  'area_km2': '43094.0'},
 {'name': 'Dominica',
  'capital': 'Roseau',
  'population': '72813',
  'area_km2': '754.0'},
 {'name': 'Dominican Republic',
  'capital': 'Santo Domingo',
  'population': '9823821',
  'area_km2': '48730.0'},
 {'name': 'Algeria',
  'capital': 'Algiers',
  'population': '34586184',
  'area_km2': '2381740.0'},
 {'name': 'Ecuador',
  'capital': 'Quito',
  'population': '14790608',
  'area_km2': '283560.0'},
 {'name': 'Estonia',
  'capital': 'Tallinn',
  'population': '1291170',
  'area_km2': '45226.0'},
 {'name': 'Egypt',
  'capital': 'Cairo',
  'population': '80471869',
  'area_km2': '1001450.0'},
 {'name': 'Western Sahara',
  'capital': 'Laâyoune / El Aaiún',
  'population': '273008',
  'area_km2': '266000.0'},
 {'name': 'Eritrea',
  'capital': 'Asmara',
  'population': '5792984',
  'area_km2': '121320.0'},
 {'name': 'Spain',
  'capital': 'Madrid',
  'population': '46505963',
  'area_km2': '504782.0'},
 {'name': 'Ethiopia',
  'capital': 'Addis Ababa',
  'population': '88013491',
  'area_km2': '1127127.0'},
 {'name': 'Finland',
  'capital': 'Helsinki',
  'population': '5244000',
  'area_km2': '337030.0'},
 {'name': 'Fiji',
  'capital': 'Suva',
  'population': '875983',
  'area_km2': '18270.0'},
 {'name': 'Falkland Islands',
  'capital': 'Stanley',
  'population': '2638',
  'area_km2': '12173.0'},
 {'name': 'Micronesia',
  'capital': 'Palikir',
  'population': '107708',
  'area_km2': '702.0'},
 {'name': 'Faroe Islands',
  'capital': 'Tórshavn',
  'population': '48228',
  'area_km2': '1399.0'},
 {'name': 'France',
  'capital': 'Paris',
  'population': '64768389',
  'area_km2': '547030.0'},
 {'name': 'Gabon',
  'capital': 'Libreville',
  'population': '1545255',
  'area_km2': '267667.0'},
 {'name': 'United Kingdom',
  'capital': 'London',
  'population': '62348447',
  'area_km2': '244820.0'},
 {'name': 'Grenada',
  'capital': "St. George's",
  'population': '107818',
  'area_km2': '344.0'},
 {'name': 'Georgia',
  'capital': 'Tbilisi',
  'population': '4630000',
  'area_km2': '69700.0'},
 {'name': 'French Guiana',
  'capital': 'Cayenne',
  'population': '195506',
  'area_km2': '91000.0'},
 {'name': 'Guernsey',
  'capital': 'St Peter Port',
  'population': '65228',
  'area_km2': '78.0'},
 {'name': 'Ghana',
  'capital': 'Accra',
  'population': '24339838',
  'area_km2': '239460.0'},
 {'name': 'Gibraltar',
  'capital': 'Gibraltar',
  'population': '27884',
  'area_km2': '6.5'},
 {'name': 'Greenland',
  'capital': 'Nuuk',
  'population': '56375',
  'area_km2': '2166086.0'},
 {'name': 'Gambia',
  'capital': 'Bathurst',
  'population': '1593256',
  'area_km2': '11300.0'},
 {'name': 'Guinea',
  'capital': 'Conakry',
  'population': '10324025',
  'area_km2': '245857.0'},
 {'name': 'Guadeloupe',
  'capital': 'Basse-Terre',
  'population': '443000',
  'area_km2': '1780.0'},
 {'name': 'Equatorial Guinea',
  'capital': 'Malabo',
  'population': '1014999',
  'area_km2': '28051.0'},
 {'name': 'Greece',
  'capital': 'Athens',
  'population': '11000000',
  'area_km2': '131940.0'},
 {'name': 'South Georgia and the South Sandwich Islands',
  'capital': 'Grytviken',
  'population': '30',
  'area_km2': '3903.0'},
 {'name': 'Guatemala',
  'capital': 'Guatemala City',
  'population': '13550440',
  'area_km2': '108890.0'},
 {'name': 'Guam',
  'capital': 'Hagåtña',
  'population': '159358',
  'area_km2': '549.0'},
 {'name': 'Guinea-Bissau',
  'capital': 'Bissau',
  'population': '1565126',
  'area_km2': '36120.0'},
 {'name': 'Guyana',
  'capital': 'Georgetown',
  'population': '748486',
  'area_km2': '214970.0'},
 {'name': 'Hong Kong',
  'capital': 'Hong Kong',
  'population': '6898686',
  'area_km2': '1092.0'},
 {'name': 'Heard Island and McDonald Islands',
  'capital': 'None',
  'population': '0',
  'area_km2': '412.0'},
 {'name': 'Honduras',
  'capital': 'Tegucigalpa',
  'population': '7989415',
  'area_km2': '112090.0'},
 {'name': 'Croatia',
  'capital': 'Zagreb',
  'population': '4491000',
  'area_km2': '56542.0'},
 {'name': 'Haiti',
  'capital': 'Port-au-Prince',
  'population': '9648924',
  'area_km2': '27750.0'},
 {'name': 'Hungary',
  'capital': 'Budapest',
  'population': '9982000',
  'area_km2': '93030.0'},
 {'name': 'Indonesia',
  'capital': 'Jakarta',
  'population': '242968342',
  'area_km2': '1919440.0'},
 {'name': 'Ireland',
  'capital': 'Dublin',
  'population': '4622917',
  'area_km2': '70280.0'},
 {'name': 'Israel',
  'capital': 'None',
  'population': '7353985',
  'area_km2': '20770.0'},
 {'name': 'Isle of Man',
  'capital': 'Douglas',
  'population': '75049',
  'area_km2': '572.0'},
 {'name': 'India',
  'capital': 'New Delhi',
  'population': '1173108018',
  'area_km2': '3287590.0'},
 {'name': 'British Indian Ocean Territory',
  'capital': 'None',
  'population': '4000',
  'area_km2': '60.0'},
 {'name': 'Iraq',
  'capital': 'Baghdad',
  'population': '29671605',
  'area_km2': '437072.0'},
 {'name': 'Iran',
  'capital': 'Tehran',
  'population': '76923300',
  'area_km2': '1648000.0'},
 {'name': 'Iceland',
  'capital': 'Reykjavik',
  'population': '308910',
  'area_km2': '103000.0'},
 {'name': 'Italy',
  'capital': 'Rome',
  'population': '60340328',
  'area_km2': '301230.0'},
 {'name': 'Jersey',
  'capital': 'Saint Helier',
  'population': '90812',
  'area_km2': '116.0'},
 {'name': 'Jamaica',
  'capital': 'Kingston',
  'population': '2847232',
  'area_km2': '10991.0'},
 {'name': 'Jordan',
  'capital': 'Amman',
  'population': '6407085',
  'area_km2': '92300.0'},
 {'name': 'Japan',
  'capital': 'Tokyo',
  'population': '127288000',
  'area_km2': '377835.0'},
 {'name': 'Kenya',
  'capital': 'Nairobi',
  'population': '40046566',
  'area_km2': '582650.0'},
 {'name': 'Kyrgyzstan',
  'capital': 'Bishkek',
  'population': '5776500',
  'area_km2': '198500.0'},
 {'name': 'Cambodia',
  'capital': 'Phnom Penh',
  'population': '14453680',
  'area_km2': '181040.0'},
 {'name': 'Kiribati',
  'capital': 'Tarawa',
  'population': '92533',
  'area_km2': '811.0'},
 {'name': 'Comoros',
  'capital': 'Moroni',
  'population': '773407',
  'area_km2': '2170.0'},
 {'name': 'Saint Kitts and Nevis',
  'capital': 'Basseterre',
  'population': '51134',
  'area_km2': '261.0'},
 {'name': 'North Korea',
  'capital': 'Pyongyang',
  'population': '22912177',
  'area_km2': '120540.0'},
 {'name': 'South Korea',
  'capital': 'Seoul',
  'population': '48422644',
  'area_km2': '98480.0'},
 {'name': 'Kuwait',
  'capital': 'Kuwait City',
  'population': '2789132',
  'area_km2': '17820.0'},
 {'name': 'Cayman Islands',
  'capital': 'George Town',
  'population': '44270',
  'area_km2': '262.0'},
 {'name': 'Kazakhstan',
  'capital': 'Astana',
  'population': '15340000',
  'area_km2': '2717300.0'},
 {'name': 'Laos',
  'capital': 'Vientiane',
  'population': '6368162',
  'area_km2': '236800.0'},
 {'name': 'Lebanon',
  'capital': 'Beirut',
  'population': '4125247',
  'area_km2': '10400.0'},
 {'name': 'Saint Lucia',
  'capital': 'Castries',
  'population': '160922',
  'area_km2': '616.0'},
 {'name': 'Liechtenstein',
  'capital': 'Vaduz',
  'population': '35000',
  'area_km2': '160.0'},
 {'name': 'Sri Lanka',
  'capital': 'Colombo',
  'population': '21513990',
  'area_km2': '65610.0'},
 {'name': 'Liberia',
  'capital': 'Monrovia',
  'population': '3685076',
  'area_km2': '111370.0'},
 {'name': 'Lesotho',
  'capital': 'Maseru',
  'population': '1919552',
  'area_km2': '30355.0'},
 {'name': 'Lithuania',
  'capital': 'Vilnius',
  'population': '2944459',
  'area_km2': '65200.0'},
 {'name': 'Luxembourg',
  'capital': 'Luxembourg',
  'population': '497538',
  'area_km2': '2586.0'},
 {'name': 'Latvia',
  'capital': 'Riga',
  'population': '2217969',
  'area_km2': '64589.0'},
 {'name': 'Libya',
  'capital': 'Tripoli',
  'population': '6461454',
  'area_km2': '1759540.0'},
 {'name': 'Morocco',
  'capital': 'Rabat',
  'population': '31627428',
  'area_km2': '446550.0'},
 {'name': 'Monaco',
  'capital': 'Monaco',
  'population': '32965',
  'area_km2': '1.95'},
 {'name': 'Moldova',
  'capital': 'Chişinău',
  'population': '4324000',
  'area_km2': '33843.0'},
 {'name': 'Montenegro',
  'capital': 'Podgorica',
  'population': '666730',
  'area_km2': '14026.0'},
 {'name': 'Saint Martin',
  'capital': 'Marigot',
  'population': '35925',
  'area_km2': '53.0'},
 {'name': 'Madagascar',
  'capital': 'Antananarivo',
  'population': '21281844',
  'area_km2': '587040.0'},
 {'name': 'Marshall Islands',
  'capital': 'Majuro',
  'population': '65859',
  'area_km2': '181.3'},
 {'name': 'Macedonia',
  'capital': 'Skopje',
  'population': '2062294',
  'area_km2': '25333.0'},
 {'name': 'Mali',
  'capital': 'Bamako',
  'population': '13796354',
  'area_km2': '1240000.0'},
 {'name': 'Myanmar [Burma]',
  'capital': 'Naypyitaw',
  'population': '53414374',
  'area_km2': '678500.0'},
 {'name': 'Mongolia',
  'capital': 'Ulan Bator',
  'population': '3086918',
  'area_km2': '1565000.0'},
 {'name': 'Macao',
  'capital': 'Macao',
  'population': '449198',
  'area_km2': '254.0'},
 {'name': 'Northern Mariana Islands',
  'capital': 'Saipan',
  'population': '53883',
  'area_km2': '477.0'},
 {'name': 'Martinique',
  'capital': 'Fort-de-France',
  'population': '432900',
  'area_km2': '1100.0'},
 {'name': 'Mauritania',
  'capital': 'Nouakchott',
  'population': '3205060',
  'area_km2': '1030700.0'},
 {'name': 'Montserrat',
  'capital': 'Plymouth',
  'population': '9341',
  'area_km2': '102.0'},
 {'name': 'Malta',
  'capital': 'Valletta',
  'population': '403000',
  'area_km2': '316.0'},
 {'name': 'Mauritius',
  'capital': 'Port Louis',
  'population': '1294104',
  'area_km2': '2040.0'},
 {'name': 'Maldives',
  'capital': 'Malé',
  'population': '395650',
  'area_km2': '300.0'},
 {'name': 'Malawi',
  'capital': 'Lilongwe',
  'population': '15447500',
  'area_km2': '118480.0'},
 {'name': 'Mexico',
  'capital': 'Mexico City',
  'population': '112468855',
  'area_km2': '1972550.0'},
 {'name': 'Malaysia',
  'capital': 'Kuala Lumpur',
  'population': '28274729',
  'area_km2': '329750.0'},
 {'name': 'Mozambique',
  'capital': 'Maputo',
  'population': '22061451',
  'area_km2': '801590.0'},
 {'name': 'Namibia',
  'capital': 'Windhoek',
  'population': '2128471',
  'area_km2': '825418.0'},
 {'name': 'New Caledonia',
  'capital': 'Noumea',
  'population': '216494',
  'area_km2': '19060.0'},
 {'name': 'Niger',
  'capital': 'Niamey',
  'population': '15878271',
  'area_km2': '1267000.0'},
 {'name': 'Norfolk Island',
  'capital': 'Kingston',
  'population': '1828',
  'area_km2': '34.6'},
 {'name': 'Nigeria',
  'capital': 'Abuja',
  'population': '154000000',
  'area_km2': '923768.0'},
 {'name': 'Nicaragua',
  'capital': 'Managua',
  'population': '5995928',
  'area_km2': '129494.0'},
 {'name': 'Netherlands',
  'capital': 'Amsterdam',
  'population': '16645000',
  'area_km2': '41526.0'},
 {'name': 'Norway',
  'capital': 'Oslo',
  'population': '5009150',
  'area_km2': '324220.0'},
 {'name': 'Nepal',
  'capital': 'Kathmandu',
  'population': '28951852',
  'area_km2': '140800.0'},
 {'name': 'Nauru',
  'capital': 'Yaren',
  'population': '10065',
  'area_km2': '21.0'},
 {'name': 'Niue',
  'capital': 'Alofi',
  'population': '2166',
  'area_km2': '260.0'},
 {'name': 'New Zealand',
  'capital': 'Wellington',
  'population': '4252277',
  'area_km2': '268680.0'},
 {'name': 'Oman',
  'capital': 'Muscat',
  'population': '2967717',
  'area_km2': '212460.0'},
 {'name': 'Panama',
  'capital': 'Panama City',
  'population': '3410676',
  'area_km2': '78200.0'},
 {'name': 'Peru',
  'capital': 'Lima',
  'population': '29907003',
  'area_km2': '1285220.0'},
 {'name': 'French Polynesia',
  'capital': 'Papeete',
  'population': '270485',
  'area_km2': '4167.0'},
 {'name': 'Papua New Guinea',
  'capital': 'Port Moresby',
  'population': '6064515',
  'area_km2': '462840.0'},
 {'name': 'Philippines',
  'capital': 'Manila',
  'population': '99900177',
  'area_km2': '300000.0'},
 {'name': 'Pakistan',
  'capital': 'Islamabad',
  'population': '184404791',
  'area_km2': '803940.0'},
 {'name': 'Poland',
  'capital': 'Warsaw',
  'population': '38500000',
  'area_km2': '312685.0'},
 {'name': 'Saint Pierre and Miquelon',
  'capital': 'Saint-Pierre',
  'population': '7012',
  'area_km2': '242.0'},
 {'name': 'Pitcairn Islands',
  'capital': 'Adamstown',
  'population': '46',
  'area_km2': '47.0'},
 {'name': 'Puerto Rico',
  'capital': 'San Juan',
  'population': '3916632',
  'area_km2': '9104.0'},
 {'name': 'Palestine',
  'capital': 'None',
  'population': '3800000',
  'area_km2': '5970.0'},
 {'name': 'Portugal',
  'capital': 'Lisbon',
  'population': '10676000',
  'area_km2': '92391.0'},
 {'name': 'Palau',
  'capital': 'Melekeok',
  'population': '19907',
  'area_km2': '458.0'},
 {'name': 'Paraguay',
  'capital': 'Asunción',
  'population': '6375830',
  'area_km2': '406750.0'},
 {'name': 'Qatar',
  'capital': 'Doha',
  'population': '840926',
  'area_km2': '11437.0'},
 {'name': 'Réunion',
  'capital': 'Saint-Denis',
  'population': '776948',
  'area_km2': '2517.0'},
 {'name': 'Romania',
  'capital': 'Bucharest',
  'population': '21959278',
  'area_km2': '237500.0'},
 {'name': 'Serbia',
  'capital': 'Belgrade',
  'population': '7344847',
  'area_km2': '88361.0'},
 {'name': 'Russia',
  'capital': 'Moscow',
  'population': '140702000',
  'area_km2': '1.71E7'},
 {'name': 'Rwanda',
  'capital': 'Kigali',
  'population': '11055976',
  'area_km2': '26338.0'},
 {'name': 'Saudi Arabia',
  'capital': 'Riyadh',
  'population': '25731776',
  'area_km2': '1960582.0'},
 {'name': 'Solomon Islands',
  'capital': 'Honiara',
  'population': '559198',
  'area_km2': '28450.0'},
 {'name': 'Seychelles',
  'capital': 'Victoria',
  'population': '88340',
  'area_km2': '455.0'},
 {'name': 'Sudan',
  'capital': 'Khartoum',
  'population': '35000000',
  'area_km2': '1861484.0'},
 {'name': 'Sweden',
  'capital': 'Stockholm',
  'population': '9828655',
  'area_km2': '449964.0'},
 {'name': 'Singapore',
  'capital': 'Singapore',
  'population': '4701069',
  'area_km2': '692.7'},
 {'name': 'Saint Helena',

Let's scrape a more complex example. This page has a table with pagination. We will scrape the rows in all the pages and store the data in a dataframe.

[https://www.scrapethissite.com/pages/forms/](https://www.scrapethissite.com/pages/forms/)

First, as with any web scraping task, we need to inspect the page to understand the structure of the page.

We'll start by scraping the first page:

In [191]:
r = requests.get("https://www.scrapethissite.com/pages/forms/")

In [192]:
r.status_code

200

In [193]:
soup = BeautifulSoup(r.text, "html.parser")

Let's extract the table header first:

In [198]:
header = soup.find('tr')

In [199]:
header

<tr>
<th>
                            Team Name
                        </th>
<th>
                            Year
                        </th>
<th>
                            Wins
                        </th>
<th>
                            Losses
                        </th>
<th>
                            OT Losses
                        </th>
<th>
                            Win %
                        </th>
<th>
                            Goals For (GF)
                        </th>
<th>
                            Goals Against (GA)
                        </th>
<th>
                            + / -
                        </th>
</tr>

In [202]:
headers = [th.text.strip() for th in header.find_all('th')]

In [203]:
headers

['Team Name',
 'Year',
 'Wins',
 'Losses',
 'OT Losses',
 'Win %',
 'Goals For (GF)',
 'Goals Against (GA)',
 '+ / -']

Let's find all the rows on first page:

In [204]:
teams = soup.find_all('tr', 'team')

In [206]:
teams[0]

<tr class="team">
<td class="name">
                            Boston Bruins
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            44
                        </td>
<td class="losses">
                            24
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-success">
                            0.55
                        </td>
<td class="gf">
                            299
                        </td>
<td class="ga">
                            264
                        </td>
<td class="diff text-success">
                            35
                        </td>
</tr>

In [207]:
for col in teams[0].find_all('td'):
    print(col.text.strip())

Boston Bruins
1990
44
24

0.55
299
264
35

We can combine that with the header:

In [210]:
row_dict = {}
for header, col in zip(headers, teams[0].find_all('td')):
    row_dict[header] = col.text.strip()

In [212]:
row_dict

{'Team Name': 'Boston Bruins',
 'Year': '1990',
 'Wins': '44',
 'Losses': '24',
 'OT Losses': '',
 'Win %': '0.55',
 'Goals For (GF)': '299',
 'Goals Against (GA)': '264',
 '+ / -': '35'}

> Repeat the operation above for all the teams (rows) using a `for` loop, and append each row_dict to a list called `rows`.

In [216]:
teams

[<tr class="team">
 <td class="name">
                             Boston Bruins
                         </td>
 <td class="year">
                             1990
                         </td>
 <td class="wins">
                             44
                         </td>
 <td class="losses">
                             24
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-success">
                             0.55
                         </td>
 <td class="gf">
                             299
                         </td>
 <td class="ga">
                             264
                         </td>
 <td class="diff text-success">
                             35
                         </td>
 </tr>,
 <tr class="team">
 <td class="name">
                             Buffalo Sabres
                         </td>
 <td class="year">
                             1990
                         </td>
 <td class="wins">
                             31
                         </td>
 <td class="losses">
                             30
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.388
                         </td>
 <td class="gf">
                             292
                         </td>
 <td class="ga">
                             278
                         </td>
 <td class="diff text-success">
                             14
                         </td>
 </tr>,
 <tr class="team">
 <td class="name">
                             Calgary Flames
                         </td>
 <td class="year">
                             1990
                         </td>
 <td class="wins">
                             46
                         </td>
 <td class="losses">
                             26
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-success">
                             0.575
                         </td>
 <td class="gf">
                             344
                         </td>
 <td class="ga">
                             263
                         </td>
 <td class="diff text-success">
                             81
                         </td>
 </tr>,
 <tr class="team">
 <td class="name">
                             Chicago Blackhawks
                         </td>
 <td class="year">
                             1990
                         </td>
 <td class="wins">
                             49
                         </td>
 <td class="losses">
                             23
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-success">
                             0.613
                         </td>
 <td class="gf">
                             284
                         </td>
 <td class="ga">
                             211
                         </td>
 <td class="diff text-success">
                             73
                         </td>
 </tr>,
 <tr class="team">
 <td class="name">
                             Detroit Red Wings
                         </td>
 <td class="year">
                             1990
                         </td>
 <td class="wins">
                             34
                         </td>
 <td class="losses">
                             38
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.425
                         </td>
 <td class="gf">
                             273
                         </td>
 <td class="ga">
                             298
                         </td>
 <td class="diff text-danger">
                             -25
                         </td>
 </tr>,
 <tr class="team">
 <td class="name">
                             Edmonton Oilers
                         </td>
 <td class="year">
                             1990
                         </td>
 <td class="wins">
                             37
                         </td>
 <td class="losses">
                             37
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.463
                         </td>
 <td class="gf">
                             272
                         </td>
 <td class="ga">
                             272
                         </td>
 <td class="diff text-success">
                             0
                         </td>
 </tr>,
 <tr class="team">
 <td class="name">
                             Hartford Whalers
                         </td>
 <td class="year">
                             1990
                         </td>
 <td class="wins">
                             31
                         </td>
 <td class="losses">
                             38
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.388
                         </td>
 <td class="gf">
                             238
                         </td>
 <td class="ga">
                             276
                         </td>
 <td class="diff text-danger">
                             -38
                         </td>
 </tr>,
 <tr class="team">
 <td class="name">
                             Los Angeles Kings
                         </td>
 <td class="year">
                             1990
                         </td>
 <td class="wins">
                             46
                         </td>
 <td class="losses">
                             24
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-success">
                             0.575
                         </td>
 <td class="gf">
                             340
                         </td>
 <td class="ga">
                             254
                         </td>
 <td class="diff text-success">
                             86
                         </td>
 </tr>,
 <tr class="team">
 <td class="name">
                             Minnesota North Stars
                         </td>
 <td class="year">
                             1990
                         </td>
 <td class="wins">
                             27
                         </td>
 <td class="losses">
                             39
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.338
                         </td>
 <td class="gf">
                             256
                         </td>
 <td class="ga">
                             266
                         </td>
 <td class="diff text-danger">
                             -10
                         </td>
 </tr>,
 <tr class="team">
 <td class="name">
                             Montreal Canadiens
                         </td>
 <td class="year">
                             1990
                         </td>
 <td class="wins">
                             39
                         </td>
 <td class="losses">
                             30
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.487
                         </td>
 <td class="gf">
                             273
                         </td>
 <td class="ga">
                             249
                         </td>
 <td class="diff text-success">
                             24
                         </td>
 </tr>,
 <tr class="team">
 <td class="name">
                             New Jersey Devils
                         </td>
 <td class="year">
                             1990
                         </td>
 <td class="wins">
                             32
                         </td>
 <td class="losses">
                             33
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.4
                         </td>
 <td class="gf">
                             272
                         </td>
 <td class="ga">
                             264
                         </td>
 <td class="diff text-success">
                             8
                         </td>
 </tr>,
 <tr class="team">
 <td class="name">
                             New York Islanders
                         </td>
 <td class="year">
                             1990
                         </td>
 <td class="wins">
                             25
                         </td>
 <td class="losses">
                             45
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.312
                         </td>
 <td class="gf">
                             223
                         </td>
 <td class="ga">
                             290
                         </td>
 <td class="diff text-danger">
                             -67
                         </td>
 </tr>,
 <tr class="team">
 <td class="name">
                             New York Rangers
                         </td>
 <td class="year">
                             1990
                         </td>
 <td class="wins">
                             36
                         </td>
 <td class="losses">
                             31
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.45
                         </td>
 <td class="gf">
                             297
                         </td>
 <td class="ga">
                             265
                         </td>
 <td class="diff text-success">
                             32
                         </td>
 </tr>,
 <tr class="team">
 <td class="name">
                             Philadelphia Flyers
                         </td>
 <td class="year">
                             1990
                         </td>
 <td class="wins">
                             33
                         </td>
 <td class="losses">
                             37
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.412
                         </td>
 <td class="gf">
                             252
                         </td>
 <td class="ga">
                             267
                         </td>
 <td class="diff text-danger">
                             -15
                         </td>
 </tr>,
 <tr class="team">
 <td class="name">
                             Pittsburgh Penguins
                         </td>
 <td class="year">
                             1990
                         </td>
 <td class="wins">
                             41
                         </td>
 <td class="losses">
                             33
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-success">
                             0.512
                         </td>
 <td class="gf">
                             342
                         </td>
 <td class="ga">
                             305
                         </td>
 <td class="diff text-success">
                             37
                         </td>
 </tr>,
 <tr class="team">
 <td class="name">
                             Quebec Nordiques
                         </td>
 <td class="year">
                             1990
                         </td>
 <td class="wins">
                             16
                         </td>
 <td class="losses">
                             50
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.2
                         </td>
 <td class="gf">
                             236
                         </td>
 <td class="ga">
                             354
                         </td>
 <td class="diff text-danger">
                             -118
                         </td>
 </tr>,
 <tr class="team">
 <td class="name">
                             St. Louis Blues
                         </td>
 <td class="year">
                             1990
                         </td>
 <td class="wins">
                             47
                         </td>
 <td class="losses">
                             22
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-success">
                             0.588
                         </td>
 <td class="gf">
                             310
                         </td>
 <td class="ga">
                             250
                         </td>
 <td class="diff text-success">
                             60
                         </td>
 </tr>,
 <tr class="team">
 <td class="name">
                             Toronto Maple Leafs
                         </td>
 <td class="year">
                             1990
                         </td>
 <td class="wins">
                             23
                         </td>
 <td class="losses">
                             46
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.287
                         </td>
 <td class="gf">
                             241
                         </td>
 <td class="ga">
                             318
                         </td>
 <td class="diff text-danger">
                             -77
                         </td>
 </tr>,
 <tr class="team">
 <td class="name">
                             Vancouver Canucks
                         </td>
 <td class="year">
                             1990
                         </td>
 <td class="wins">
                             28
                         </td>
 <td class="losses">
                             43
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.35
                         </td>
 <td class="gf">
                             243
                         </td>
 <td class="ga">
                             315
                         </td>
 <td class="diff text-danger">
                             -72
                         </td>
 </tr>,
 <tr class="team">
 <td class="name">
                             Washington Capitals
                         </td>
 <td class="year">
                             1990
                         </td>
 <td class="wins">
                             37
                         </td>
 <td class="losses">
                             36
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.463
                         </td>
 <td class="gf">
                             258
                         </td>
 <td class="ga">
                             258
                         </td>
 <td class="diff text-success">
                             0
                         </td>
 </tr>,
 <tr class="team">
 <td class="name">
                             Winnipeg Jets
                         </td>
 <td class="year">
                             1990
                         </td>
 <td class="wins">
                             26
                         </td>
 <td class="losses">
                             43
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.325
                         </td>
 <td class="gf">
                             260
                         </td>
 <td class="ga">
                             288
                         </td>
 <td class="diff text-danger">
                             -28
                         </td>
 </tr>,
 <tr class="team">
 <td class="name">
                             Boston Bruins
                         </td>
 <td class="year">
                             1991
                         </td>
 <td class="wins">
                             36
                         </td>
 <td class="losses">
                             32
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.45
                         </td>
 <td class="gf">
                             270
                         </td>
 <td class="ga">
                             275
                         </td>
 <td class="diff text-danger">
                             -5
                         </td>
 </tr>,
 <tr class="team">
 <td class="name">
                             Buffalo Sabres
                         </td>
 <td class="year">
                             1991
                         </td>
 <td class="wins">
                             31
                         </td>
 <td class="losses">
                             37
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.388
                         </td>
 <td class="gf">
                             289
                         </td>
 <td class="ga">
                             299
                         </td>
 <td class="diff text-danger">
                             -10
                         </td>
 </tr>,
 <tr class="team">
 <td class="name">
                             Calgary Flames
                         </td>
 <td class="year">
                             1991
                         </td>
 <td class="wins">
                             31
                         </td>
 <td class="losses">
                             37
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.388
                         </td>
 <td class="gf">
                             296
                         </td>
 <td class="ga">
                             305
                         </td>
 <td class="diff text-danger">
                             -9
                         </td>
 </tr>,
 <tr class="team">
 <td class="name">
                             Chicago Blackhawks
                         </td>
 <td class="year">
                             1991
                         </td>
 <td class="wins">
                             36
                         </td>
 <td class="losses">
                             29
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.45
                         </td>
 <td class="gf">
                             257
                         </td>
 <td class="ga">
                             236
                         </td>
 <td class="diff text-success">
                             21
                         </td>
 </tr>]

In [217]:
rows_dict = {}
list_rows = []
for team in teams:
    for header, col in zip(headers, team.find_all('td')):
        rows_dict[header] = col.text.strip()
        list_rows.append(rows_dict)

In [218]:
list_rows

[{'Team Name': 'Chicago Blackhawks',
  'Year': '1991',
  'Wins': '36',
  'Losses': '29',
  'OT Losses': '',
  'Win %': '0.45',
  'Goals For (GF)': '257',
  'Goals Against (GA)': '236',
  '+ / -': '21'},
 {'Team Name': 'Chicago Blackhawks',
  'Year': '1991',
  'Wins': '36',
  'Losses': '29',
  'OT Losses': '',
  'Win %': '0.45',
  'Goals For (GF)': '257',
  'Goals Against (GA)': '236',
  '+ / -': '21'},
 {'Team Name': 'Chicago Blackhawks',
  'Year': '1991',
  'Wins': '36',
  'Losses': '29',
  'OT Losses': '',
  'Win %': '0.45',
  'Goals For (GF)': '257',
  'Goals Against (GA)': '236',
  '+ / -': '21'},
 {'Team Name': 'Chicago Blackhawks',
  'Year': '1991',
  'Wins': '36',
  'Losses': '29',
  'OT Losses': '',
  'Win %': '0.45',
  'Goals For (GF)': '257',
  'Goals Against (GA)': '236',
  '+ / -': '21'},
 {'Team Name': 'Chicago Blackhawks',
  'Year': '1991',
  'Wins': '36',
  'Losses': '29',
  'OT Losses': '',
  'Win %': '0.45',
  'Goals For (GF)': '257',
  'Goals Against (GA)': '236',
  '+ / -': '21'},
 {'Team Name': 'Chicago Blackhawks',
  'Year': '1991',
  'Wins': '36',
  'Losses': '29',
  'OT Losses': '',
  'Win %': '0.45',
  'Goals For (GF)': '257',
  'Goals Against (GA)': '236',
  '+ / -': '21'},
 {'Team Name': 'Chicago Blackhawks',
  'Year': '1991',
  'Wins': '36',
  'Losses': '29',
  'OT Losses': '',
  'Win %': '0.45',
  'Goals For (GF)': '257',
  'Goals Against (GA)': '236',
  '+ / -': '21'},
 {'Team Name': 'Chicago Blackhawks',
  'Year': '1991',
  'Wins': '36',
  'Losses': '29',
  'OT Losses': '',
  'Win %': '0.45',
  'Goals For (GF)': '257',
  'Goals Against (GA)': '236',
  '+ / -': '21'},
 {'Team Name': 'Chicago Blackhawks',
  'Year': '1991',
  'Wins': '36',
  'Losses': '29',
  'OT Losses': '',
  'Win %': '0.45',
  'Goals For (GF)': '257',
  'Goals Against (GA)': '236',
  '+ / -': '21'},
 {'Team Name': 'Chicago Blackhawks',
  'Year': '1991',
  'Wins': '36',
  'Losses': '29',
  'OT Losses': '',
  'Win %': '0.45',
  'Goals For (GF)': '257',
  'Goals Against (GA)': '236',
  '+ / -': '21'},
 {'Team Name': 'Chicago Blackhawks',
  'Year': '1991',
  'Wins': '36',
  'Losses': '29',
  'OT Losses': '',
  'Win %': '0.45',
  'Goals For (GF)': '257',
  'Goals Against (GA)': '236',
  '+ / -': '21'},
 {'Team Name': 'Chicago Blackhawks',
  'Year': '1991',
  'Wins': '36',
  'Losses': '29',
  'OT Losses': '',
  'Win %': '0.45',
  'Goals For (GF)': '257',
  'Goals Against (GA)': '236',
  '+ / -': '21'},
 {'Team Name': 'Chicago Blackhawks',
  'Year': '1991',
  'Wins': '36',
  'Losses': '29',
  'OT Losses': '',
  'Win %': '0.45',
  'Goals For (GF)': '257',
  'Goals Against (GA)': '236',
  '+ / -': '21'},
 {'Team Name': 'Chicago Blackhawks',
  'Year': '1991',
  'Wins': '36',
  'Losses': '29',
  'OT Losses': '',
  'Win %': '0.45',
  'Goals For (GF)': '257',
  'Goals Against (GA)': '236',
  '+ / -': '21'},
 {'Team Name': 'Chicago Blackhawks',
  'Year': '1991',
  'Wins': '36',
  'Losses': '29',
  'OT Losses': '',
  'Win %': '0.45',
  'Goals For (GF)': '257',
  'Goals Against (GA)': '236',
  '+ / -': '21'},
 {'Team Name': 'Chicago Blackhawks',
  'Year': '1991',
  'Wins': '36',
  'Losses': '29',
  'OT Losses': '',
  'Win %': '0.45',
  'Goals For (GF)': '257',
  'Goals Against (GA)': '236',
  '+ / -': '21'},
 {'Team Name': 'Chicago Blackhawks',
  'Year': '1991',
  'Wins': '36',
  'Losses': '29',
  'OT Losses': '',
  'Win %': '0.45',
  'Goals For (GF)': '257',
  'Goals Against (GA)': '236',
  '+ / -': '21'},
 {'Team Name': 'Chicago Blackhawks',
  'Year': '1991',
  'Wins': '36',
  'Losses': '29',
  'OT Losses': '',
  'Win %': '0.45',
  'Goals For (GF)': '257',
  'Goals Against (GA)': '236',
  '+ / -': '21'},
 {'Team Name': 'Chicago Blackhawks',
  'Year': '1991',
  'Wins': '36',
  'Losses': '29',
  'OT Losses': '',
  'Win %': '0.45',
  'Goals For (GF)': '257',
  'Goals Against (GA)': '236',
  '+ / -': '21'},
 {'Team Name': 'Chicago Blackhawks',
  'Year': '1991',
  'Wins': '36',
  'Losses': '29',
  'OT Losses': '',
  'Win %': '0.45',
  'Goals For (GF)': '257',
  'Goals Against (GA)': '236',
  '+ / -': '21'},
 {'Team Name': 'Chicago Blackhawks',
  'Year': '1991',
  'Wins': '36',
  'Losses': '29',
  'OT Losses': '',
  'Win %': '0.45',
  'Goals For (GF)': '257',
  'Goals Against (GA)': '236',
  '+ / -': '21'},
 {'Team Name': 'Chicago Blackhawks',
  'Year': '1991',
  'Wins': '36',
  'Losses': '29',
  'OT Losses': '',
  'Win %': '0.45',
  'Goals For (GF)': '257',
  'Goals Against (GA)': '236',
  '+ / -': '21'},
 {'Team Name': 'Chicago Blackhawks',
  'Year': '1991',
  'Wins': '36',
  'Losses': '29',
  'OT Losses': '',
  'Win %': '0.45',
  'Goals For (GF)': '257',
  'Goals Against (GA)': '236',
  '+ / -': '21'},
 {'Team Name': 'Chicago Blackhawks',
  'Year': '1991',
  'Wins': '36',
  'Losses': '29',
  'OT Losses': '',
  'Win %': '0.45',
  'Goals For (GF)': '257',
  'Goals Against (GA)': '236',
  '+ / -': '21'},
 {'Team Name': 'Chicago Blackhawks',
  'Year': '1991',
  'Wins': '36',
  'Losses': '29',
  'OT Losses': '',
  'Win %': '0.45',
  'Goals For (GF)': '257',
  'Goals Against (GA)': '236',
  '+ / -': '21'},
 {'Team Name': 'Chicago Blackhawks',
  'Year': '1991',
  'Wins': '36',
  'Losses': '29',
  'OT Losses': '',
  'Win %': '0.45',
  'Goals For (GF)': '257',
  'Goals Against (GA)': '236',
  '+ / -': '21'},
 {'Team Name': 'Chicago Blackhawks',
  'Year': '1991',
  'Wins': '36',
  'Losses': '29',
  'OT Losses': '',
  'Win %': '0.45',
  'Goals For (GF)': '257',
  'Goals Against (GA)': '236',
  '+ / -': '21'},
 {'Team Name': 'Chicago Blackhawks',
  'Year': '1991',
  'Wins': '36',
  'Losses': '29',
  'OT Losses': '',
  'Win %': '0.45',
  'Goals For (GF)': '257',
  'Goals Against (GA)': '236',
  '+ / -': '21'},
 {'Team Name': 'Chicago Blackhawks',
  'Year': '1991',
  'Wins': '36',
  'Losses': '29',
  'OT Losses': '',
  'Win %': '0.45',
  'Goals For (GF)': '257',
  'Goals Against (GA)': '236',
  '+ / -': '21'},
 {'Team Name': 'Chicago Blackhawks',
  'Year': '1991',
  'Wins': '36',
  'Losses': '29',
  'OT Losses': '',
  'Win %': '0.45',
  'Goals For (GF)': '257',
  'Goals Against (GA)': '236',
  '+ / -': '21'},
 {'Team Name': 'Chicago Blackhawks',
  'Year': '1991',
  'Wins': '36',
  'Losses': '29',
  'OT Losses': '',
  'Win %': '0.45',
  'Goals For (GF)': '257',
  'Goals Against (GA)': '236',
  '+ / -': '21'},
 {'Team Name': 'Chicago Blackhawks',
  'Year': '1991',
  'Wins': '36',
  'Losses': '29',
  'OT Losses': '',
  'Win %': '0.45',
  'Goals For (GF)': '257',
  'Goals Against (GA)': '236',
  '+ / -': '21'},
 {'Team Name': 'Chicago Blackhawks',
  'Year': '1991',
  'Wins': '36',
  'Losses': '29',
  'OT Losses': '',
  'Win %': '0.45',
  'Goals For (GF)': '257',
  'Goals Against (GA)': '236',
  '+ / -': '21'},
 {'Team Name': 'Chicago Blackhawks',
  'Year': '1991',
  'Wins': '36',
  'Losses': '29',
  'OT Losses': '',
  'Win %': '0.45',
  'Goals For (GF)': '257',
  'Goals Against (GA)': '236',
  '+ / -': '21'},
 {'Team Name': 'Chicago Blackhawks',
  'Year': '1991',
  'Wins': '36',
  'Losses': '29',
  'OT Losses': '',
  'Win %': '0.45',
  'Goals For (GF)': '257',
  'Goals Against (GA)': '236',
  '+ / -': '21'},
 {'Team Name': 'Chicago Blackhawks',
  'Year': '1991',
  'Wins': '36',
  'Losses': '29',
  'OT Losses': '',
  'Win %': '0.45',
  'Goals For (GF)': '257',
  'Goals Against (GA)': '236',
  '+ / -': '21'},
 {'Team Name': 'Chicago Blackhawks',
  'Year': '1991',
  'Wins': '36',
  'Losses': '29',
  'OT Losses': '',
  'Win %': '0.45',
  'Goals For (GF)': '257',
  'Goals Against (GA)': '236',
  '+ / -': '21'},
 {'Team Name': 'Chicago Blackhawks',
  'Year': '1991',
  'Wins': '36',
  'Losses': '29',
  'OT Losses': '',
  'Win %': '0.45',
  'Goals For (GF)': '257',
  'Goals Against (GA)': '236',
  '+ / -': '21'},
 {'Team Name': 'Chicago Blackhawks',
  'Year': '1991',
  'Wins': '36',
  'Losses': '29',
  'OT Losses': '',
  'Win %': '0.45',
  'Goals For (GF)': '257',
  'Goals Against (GA)': '236',
  '+ / -': '21'},
 {'Team Name': 'Chicago Blackhawks',
  'Year': '1991',
  'Wins': '36',
  'Losses': '29',
  'OT Losses': '',
  'Win %': '0.45',
  'Goals For (GF)': '257',
  'Goals Against (GA)': '236',
  '+ / -': '21'},
 {'Team Name': 'Chicago Blackhawks',
  'Year': '1991',
  'Wins': '36',
  'Losses': '29',
  'OT Losses': '',
  'Win %': '0.45',
  'Goals For (GF)': '257',
  'Goals Against (GA)': '236',
  '+ / -': '21'},
 {'Team Name': 'Chicago Blackhawks',
  'Year': '1991',
  'Wins': '36',
  'Losses': '29',
  'OT Losses': '',
  'Win %': '0.45',
  'Goals For (GF)': '257',
  'Goals Against (GA)': '236',
  '+ / -': '21'},
 {'Team Name': 'Chicago Blackhawks',
  'Year': '1991',
  'Wins': '36',
  'Losses': '29',
  'OT Losses': '',
  'Win %': '0.45',
  'Goals For (GF)': '257',
  'Goals Against (GA)': '236',
  '+ / -': '21'},
 {'Team Name': 'Chicago Blackhawks',
  'Year': '1991',
  'Wins': '36',
  'Losses': '29',
  'OT Losses': '',
  'Win %': '0.45',
  'Goals For (GF)': '257',
  'Goals Against (GA)': '236',
  '+ / -': '21'},
 {'Team Name': 'Chicago Blackhawks',
  'Year': '1991',
  'Wins': '36',
  'Losses': '29',
  'OT Losses': '',
  'Win %': '0.45',
  'Goals For (GF)': '257',
  'Goals Against (GA)': '236',
  '+ / -': '21'},
 {'Team Name': 'Chicago Blackhawks',
  'Year': '1991',
  'Wins': '36',
  'Losses': '29',
  'OT Losses': '',
  'Win %': '0.45',
  'Goals For (GF)': '257',
  'Goals Against (GA)': '236',
  '+ / -': '21'},
 {'Team Name': 'Chicago Blackhawks',
  'Year': '1991',
  'Wins': '36',
  'Losses': '29',
  'OT Losses': '',
  'Win %': '0.45',
  'Goals For (GF)': '257',
  'Goals Against (GA)': '236',
  '+ / -': '21'},
 {'Team Name': 'Chicago Blackhawks',
  'Year': '1991',
  'Wins': '36',
  'Losses': '29',
  'OT Losses': '',
  'Win %': '0.45',
  'Goals For (GF)': '257',
  'Goals Against (GA)': '236',
  '+ / -': '21'},
 {'Team Name': 'Chicago Blackhawks',
  'Year': '1991',
  'Wins': '36',
  'Losses': '29',
  'OT Losses': '',
  'Win %': '0.45',
  'Goals For (GF)': '257',
  'Goals Against (GA)': '236',
  '+ / -': '21'},
 {'Team Name': 'Chicago Blackhawks',
  'Year': '1991',
  'Wins': '36',
  'Losses': '29',
  'OT Losses': '',
  'Win %': '0.45',
  'Goals For (GF)': '257',
  'Goals Against (GA)': '236',
  '+ / -': '21'},
 {'Team Name': 'Chicago Blackhawks',
  'Year': '1991',
  'Wins': '36',
  'Losses': '29',
  'OT Losses': '',
  'Win %': '0.45',
  'Goals For (GF)': '257',
  'Goals Against (GA)': '236',
  '+ / -': '21'},
 {'Team Name': 'Chicago Blackhawks',
  'Year': '1991',
  'Wins': '36',
  'Losses': '29',
  'OT Losses': '',
  'Win %': '0.45',
  'Goals For (GF)': '257',
  'Goals Against (GA)': '236',
  '+ / -': '21'},
 {'Team Name': 'Chicago Blackhawks',
  'Year': '1991',
  'Wins': '36',
  'Losses': '29',
  'OT Losses': '',
  'Win %': '0.45',
  'Goals For (GF)': '257',
  'Goals Against (GA)': '236',
  '+ / -': '21'},
 {'Team Name': 'Chicago Blackhawks',
  'Year': '1991',
  'Wins': '36',
  'Losses': '29',
  'OT Losses': '',
  'Win %': '0.45',
  'Goals For (GF)': '257',
  'Goals Against (GA)': '236',
  '+ / -': '21'},
 {'Team Name': 'Chicago Blackhawks',
  'Year': '1991',
  'Wins': '36',
  'Losses': '29',
  'OT Losses': '',
  'Win %': '0.45',
  'Goals For (GF)': '257',
  'Goals Against (GA)': '236',
  '+ / -': '21'},
 {'Team Name': 'Chicago Blackhawks',
  'Year': '1991',
  'Wins': '36',
  'Losses': '29',
  'OT Losses': '',
  'Win %': '0.45',
  'Goals For (GF)': '257',
  'Goals Against (GA)': '236',
  '+ / -': '21'},
 {'Team Name': 'Chicago Blackhawks',
  'Year': '1991',
  'Wins': '36',
  'Losses': '29',
  'OT Losses': '',
  'Win %': '0.45',
  'Goals For (GF)': '257',
  'Goals Against (GA)': '236',
  '+ / -': '21'},
 {'Team Name': 'Chicago Blackhawks',
  'Year': '1991',
  'Wins': '36',
  'Losses': '29',
  'OT Losses': '',
  'Win %': '0.45',
  'Goals For (GF)': '257',
  'Goals Against (GA)': '236',
  '+ / -': '21'},
 {'Team Name': 'Chicago Blackhawks',
  'Year': '1991',
  'Wins': '36',
  'Losses': '29',
  'OT Losses': '',
  'Win %': '0.45',
  'Goals For (GF)': '257',
  'Goals Against (GA)': '236',
  '+ / -': '21'},
 {'Team Name': 'Chicago Blackhawks',
  'Year': '1991',
  'Wins': '36',
  'Losses': '29',
  'OT Losses': '',
  'Win %': '0.45',
  'Goals For (GF)': '257',
  'Goals Against (GA)': '236',
  '+ / -': '21'},
 {'Team Name': 'Chicago Blackhawks',
  'Year': '1991',
  'Wins': '36',
  'Losses': '29',
  'OT Losses': '',
  'Win %': '0.45',
  'Goals For (GF)': '257',
  'Goals Against (GA)': '236',
  '+ / -': '21'},
 {'Team Name': 'Chicago Blackhawks',
  'Year': '1991',
  'Wins': '36',
  'Losses': '29',
  'OT Losses': '',
  'Win %': '0.45',
  'Goals For (GF)': '257',
  'Goals Against (GA)': '236',
  '+ / -': '21'},
 {'Team Name': 'Chicago Blackhawks',
  'Year': '1991',
  'Wins': '36',
  'Losses': '29',
  'OT Losses': '',
  'Win %': '0.45',
  'Goals For (GF)': '257',
  'Goals Against (GA)': '236',
  '+ / -': '21'},
 {'Team Name': 'Chicago Blackhawks',
  'Year': '1991',
  'Wins': '36',
  'Losses': '29',
  'OT Losses': '',
  'Win %': '0.45',
  'Goals For (GF)': '257',
  'Goals Against (GA)': '236',
  '+ / -': '21'},
 {'Team Name': 'Chicago Blackhawks',
  'Year': '1991',
  'Wins': '36',
  'Losses': '29',
  'OT Losses': '',
  'Win %': '0.45',
  'Goals For (GF)': '257',
  'Goals Against (GA)': '236',
  '+ / -': '21'},
 {'Team Name': 'Chicago Blackhawks',
  'Year': '1991',
  'Wins': '36',
  'Losses': '29',
  'OT Losses': '',
  'Win %': '0.45',
  'Goals For (GF)': '257',
  'Goals Against (GA)': '236',
  '+ / -': '21'},
 {'Team Name': 'Chicago Blackhawks',
  'Year': '1991',
  'Wins': '36',
  'Losses': '29',
  'OT Losses': '',
  'Win %': '0.45',
  'Goals For (GF)': '257',
  'Goals Against (GA)': '236',
  '+ / -': '21'},
 {'Team Name': 'Chicago Blackhawks',
  'Year': '1991',
  'Wins': '36',
  'Losses': '29',
  'OT Losses': '',
  'Win %': '0.45',
  'Goals For (GF)': '257',
  'Goals Against (GA)': '236',
  '+ / -': '21'},
 {'Team Name': 'Chicago Blackhawks',
  'Year': '1991',
  'Wins': '36',
  'Losses': '29',
  'OT Losses': '',
  'Win %': '0.45',
  'Goals For (GF)': '257',
  'Goals Against (GA)': '236',
  '+ / -': '21'},
 {'Team Name': 'Chicago Blackhawks',
  'Year': '1991',
  'Wins': '36',
  'Losses': '29',
  'OT Losses': '',
  'Win %': '0.45',
  'Goals For (GF)': '257',
  'Goals Against (GA)': '236',
  '+ / -': '21'},
 {'Team Name': 'Chicago Blackhawks',
  'Year': '1991',
  'Wins': '36',
  'Losses': '29',
  'OT Losses': '',
  'Win %': '0.45',
  'Goals For (GF)': '257',
  'Goals Against (GA)': '236',
  '+ / -': '21'},
 {'Team Name': 'Chicago Blackhawks',
  'Year': '1991',
  'Wins': '36',
  'Losses': '29',
  'OT Losses': '',
  'Win %': '0.45',
  'Goals For (GF)': '257',
  'Goals Against (GA)': '236',
  '+ / -': '21'},
 {'Team Name': 'Chicago Blackhawks',
  'Year': '1991',
  'Wins': '36',
  'Losses': '29',
  'OT Losses': '',
  'Win %': '0.45',
  'Goals For (GF)': '257',
  'Goals Against (GA)': '236',
  '+ / -': '21'},
 {'Team Name': 'Chicago Blackhawks',
  'Year': '1991',
  'Wins': '36',
  'Losses': '29',
  'OT Losses': '',
  'Win %': '0.45',
  'Goals For (GF)': '257',
  'Goals Against (GA)': '236',
  '+ / -': '21'},
 {'Team Name': 'Chicago Blackhawks',
  'Year': '1991',
  'Wins': '36',
  'Losses': '29',
  'OT Losses': '',
  'Win %': '0.45',
  'Goals For (GF)': '257',
  'Goals Against (GA)': '236',
  '+ / -': '21'},
 {'Team Name': 'Chicago Blackhawks',
  'Year': '1991',
  'Wins': '36',
  'Losses': '29',
  'OT Losses': '',
  'Win %': '0.45',
  'Goals For (GF)': '257',
  'Goals Against (GA)': '236',
  '+ / -': '21'},
 {'Team Name': 'Chicago Blackhawks',
  'Year': '1991',
  'Wins': '36',
  'Losses': '29',
  'OT Losses': '',
  'Win %': '0.45',
  'Goals For (GF)': '257',
  'Goals Against (GA)': '236',
  '+ / -': '21'},
 {'Team Name': 'Chicago Blackhawks',
  'Year': '1991',
  'Wins': '36',
  'Losses': '29',
  'OT Losses': '',
  'Win %': '0.45',
  'Goals For (GF)': '257',
  'Goals Against (GA)': '236',
  '+ / -': '21'},
 {'Team Name': 'Chicago Blackhawks',
  'Year': '1991',
  'Wins': '36',
  'Losses': '29',
  'OT Losses': '',
  'Win %': '0.45',
  'Goals For (GF)': '257',
  'Goals Against (GA)': '236',
  '+ / -': '21'},
 {'Team Name': 'Chicago Blackhawks',
  'Year': '1991',
  'Wins': '36',
  'Losses': '29',
  'OT Losses': '',
  'Win %': '0.45',
  'Goals For (GF)': '257',
  'Goals Against (GA)': '236',
  '+ / -': '21'},
 {'Team Name': 'Chicago Blackhawks',
  'Year': '1991',
  'Wins': '36',
  'Losses': '29',
  'OT Losses': '',
  'Win %': '0.45',
  'Goals For (GF)': '257',
  'Goals Against (GA)': '236',
  '+ / -': '21'},
 {'Team Name': 'Chicago Blackhawks',
  'Year': '1991',
  'Wins': '36',
  'Losses': '29',
  'OT Losses': '',
  'Win %': '0.45',
  'Goals For (GF)': '257',
  'Goals Against (GA)': '236',
  '+ / -': '21'},
 {'Team Name': 'Chicago Blackhawks',
  'Year': '1991',
  'Wins': '36',
  'Losses': '29',
  'OT Losses': '',
  'Win %': '0.45',
  'Goals For (GF)': '257',
  'Goals Against (GA)': '236',
  '+ / -': '21'},
 {'Team Name': 'Chicago Blackhawks',
  'Year': '1991',
  'Wins': '36',
  'Losses': '29',
  'OT Losses': '',
  'Win %': '0.45',
  'Goals For (GF)': '257',
  'Goals Against (GA)': '236',
  '+ / -': '21'},
 {'Team Name': 'Chicago Blackhawks',
  'Year': '1991',
  'Wins': '36',
  'Losses': '29',
  'OT Losses': '',
  'Win %': '0.45',
  'Goals For (GF)': '257',
  'Goals Against (GA)': '236',
  '+ / -': '21'},
 {'Team Name': 'Chicago Blackhawks',
  'Year': '1991',
  'Wins': '36',
  'Losses': '29',
  'OT Losses': '',
  'Win %': '0.45',
  'Goals For (GF)': '257',
  'Goals Against (GA)': '236',
  '+ / -': '21'},
 {'Team Name': 'Chicago Blackhawks',
  'Year': '1991',
  'Wins': '36',
  'Losses': '29',
  'OT Losses': '',
  'Win %': '0.45',
  'Goals For (GF)': '257',
  'Goals Against (GA)': '236',
  '+ / -': '21'},
 {'Team Name': 'Chicago Blackhawks',
  'Year': '1991',
  'Wins': '36',
  'Losses': '29',
  'OT Losses': '',
  'Win %': '0.45',
  'Goals For (GF)': '257',
  'Goals Against (GA)': '236',
  '+ / -': '21'},
 {'Team Name': 'Chicago Blackhawks',
  'Year': '1991',
  'Wins': '36',
  'Losses': '29',
  'OT Losses': '',
  'Win %': '0.45',
  'Goals For (GF)': '257',
  'Goals Against (GA)': '236',
  '+ / -': '21'},
 {'Team Name': 'Chicago Blackhawks',
  'Year': '1991',
  'Wins': '36',
  'Losses': '29',
  'OT Losses': '',
  'Win %': '0.45',
  'Goals For (GF)': '257',
  'Goals Against (GA)': '236',
  '+ / -': '21'},
 {'Team Name': 'Chicago Blackhawks',
  'Year': '1991',
  'Wins': '36',
  'Losses': '29',
  'OT Losses': '',
  'Win %': '0.45',
  'Goals For (GF)': '257',
  'Goals Against (GA)': '236',
  '+ / -': '21'},
 {'Team Name': 'Chicago Blackhawks',
  'Year': '1991',
  'Wins': '36',
  'Losses': '29',
  'OT Losses': '',
  'Win %': '0.45',
  'Goals For (GF)': '257',
  'Goals Against (GA)': '236',
  '+ / -': '21'},
 {'Team Name': 'Chicago Blackhawks',
  'Year': '1991',
  'Wins': '36',
  'Losses': '29',
  'OT Losses': '',
  'Win %': '0.45',
  'Goals For (GF)': '257',
  'Goals Against (GA)': '236',
  '+ / -': '21'},
 {'Team Name': 'Chicago Blackhawks',
  'Year': '1991',
  'Wins': '36',
  'Losses': '29',
  'OT Losses': '',
  'Win %': '0.45',
  'Goals For (GF)': '257',
  'Goals Against (GA)': '236',
  '+ / -': '21'},
 {'Team Name': 'Chicago Blackhawks',
  'Year': '1991',
  'Wins': '36',
  'Losses': '29',
  'OT Losses': '',
  'Win %': '0.45',
  'Goals For (GF)': '257',
  'Goals Against (GA)': '236',
  '+ / -': '21'},
 {'Team Name': 'Chicago Blackhawks',
  'Year': '1991',
  'Wins': '36',
  'Losses': '29',
  'OT Losses': '',
  'Win %': '0.45',
  'Goals For (GF)': '257',
  'Goals Against (GA)': '236',
  '+ / -': '21'},
 {'Team Name': 'Chicago Blackhawks',
  'Year': '1991',
  'Wins': '36',
  'Losses': '29',
  'OT Losses': '',
  'Win %': '0.45',
  'Goals For (GF)': '257',
  'Goals Against (GA)': '236',
  '+ / -': '21'},
 {'Team Name': 'Chicago Blackhawks',
  'Year': '1991',
  'Wins': '36',
  'Losses': '29',
  'OT Losses': '',
  'Win %': '0.45',
  'Goals For (GF)': '257',
  'Goals Against (GA)': '236',
  '+ / -': '21'},
 {'Team Name': 'Chicago Blackhawks',
  'Year': '1991',
  'Wins': '36',
  'Losses': '29',

In [215]:
rows_dict

{'Team Name': 'Chicago Blackhawks',
 'Year': '1991',
 'Wins': '36',
 'Losses': '29',
 'OT Losses': '',
 'Win %': '0.45',
 'Goals For (GF)': '257',
 'Goals Against (GA)': '236',
 '+ / -': '21'}

If you press on any page number (button) in the bottom, you will see the URL change, for example pressing on page 2:

`https://www.scrapethissite.com/pages/forms/?page_num=2`

This is because the page number is a parameter in the URL. We can use this to our advantage to scrape all the pages. We can use a `for loop` to iterate through all the pages and scrape the data from each page.

In [11]:

def parse_and_extract_rows(response_text: str):
    """
    Parse the HTML and extract table rows from the response object's text.
    
    Args:
        response_text (str): The HTML text from the response object.
        
    Returns:
        An iterator of dictionaries with the data from the current page.
    """
    soup = BeautifulSoup(response_text, "html.parser")
    header = soup.find('tr')
    headers = [th.text.strip() for th in header.find_all('th')]
    teams = soup.find_all('tr', 'team')
    for team in teams:
        row_dict = {}
        for header, col in zip(headers, team.find_all('td')):
            row_dict[header] = col.text.strip()
        yield row_dict

As there are 24 pages, we need to iterate through all of them to get all the data we want. We will use a for loop to do this. We will also use the `time.sleep()` function to pause and make sure we don't overload the server with requests.

In [12]:
import time

In [14]:
rows = []
for page in range(1, 2):
    r = requests.get(f"https://www.scrapethissite.com/pages/forms/?page_num={page}")
    for row_dict in parse_and_extract_rows(r.text):
        rows.append(row_dict)
    # pause for 1 second between requests
    time.sleep(1)

In [222]:
len(rows)

582

In [223]:
rows[0]

{'Team Name': 'Boston Bruins',
 'Year': '1990',
 'Wins': '44',
 'Losses': '24',
 'OT Losses': '',
 'Win %': '0.55',
 'Goals For (GF)': '299',
 'Goals Against (GA)': '264',
 '+ / -': '35'}

In [224]:
rows[-1]

{'Team Name': 'Winnipeg Jets',
 'Year': '2011',
 'Wins': '37',
 'Losses': '35',
 'OT Losses': '10',
 'Win %': '0.451',
 'Goals For (GF)': '225',
 'Goals Against (GA)': '246',
 '+ / -': '-21'}

Let's convert the list of dictionaries into a dataframe to perform further analysis.

In [225]:
df = pd.DataFrame(rows)

 Cast the correct dtypes for the columns, we'll use pandas [nullable](https://pandas.pydata.org/pandas-docs/stable/user_guide/basics.html#basics-dtypes) integer (`pd.Int64Dtype`) and float (`pd.Float64Dtype`) type for the numeric columns.

 Below, `int` is an alias for `np.int64`, while `Int64` represents `pd.Int64Dtype`.

In [226]:
df = df.replace('', pd.NA).astype({'Year': int, 'Wins': 'Int64', 'Losses': 'Int64', 'OT Losses': 'Int64', 
                                   'Goals For (GF)': 'Int64', 'Goals Against (GA)': 'Int64', 
                                   '+ / -': 'Int64', 'Win %': float})

In [259]:
df.sort_values(by = 'Wins',ascending=False)

,Team Name,Year,Wins,Losses,OT Losses,Win %,Goals For (GF),Goals Against (GA),+ / -
126,Detroit Red Wings,1995,62,13,<NA>,0.756,325,181,144
382,Detroit Red Wings,2005,58,16,8,0.707,305,209,96
58,Pittsburgh Penguins,1992,56,21,<NA>,0.667,367,268,99
550,Vancouver Canucks,2010,54,19,9,0.659,262,185,77
521,Washington Capitals,2009,54,15,13,0.659,318,233,85
...,...,...,...,...,...,...,...,...,...
82,Ottawa Senators,1993,14,61,<NA>,0.167,201,397,-196
225,Atlanta Thrashers,1999,14,57,4,0.171,170,313,-143
60,San Jose Sharks,1992,11,71,<NA>,0.131,218,414,-196
56,Ottawa Senators,1992,10,70,<NA>,0.119,202,395,-193
108,Ottawa Senators,1994,9,34,<NA>,0.188,117,174,-57

> 1. Find the team that has the most number of Wins for the year.
> 
> 2. Find the team that has the most number of Losses for the year.
> 
> 3. Find the team that has the lowest Win % for the year.
> 
> 4. Find the team that has the most number of Wins for all years.

In [270]:
# 1. Filter data for the specific target year (e.g., 2026)
target_year = 2026
df_year = df[df['Year'] == target_year].copy()

# # 2. Add Win % column for the third question
# df_year['Win_Pct'] = df_year['Wins'] / (df_year['Wins'] + df_year['Losses'])

# 3. Aggregate all-time wins for the fourth question
all_time_wins = df.groupby('Team Name')['Wins'].sum()
wins_by_year = df.groupby(['Team Name','Year'])['Wins'].sum()
losses_by_year = df.groupby(['Team Name','Year'])['Losses'].sum()
# print(all_time_wins.sort_values(ascending=False).head(1))

print(all_time_wins.idxmax())
print(wins_by_year.sort_values(ascending=False).head(5))
print(losses_by_year.idxmax)

# 4. Compile all answers into a dictionary
# results = {
#     f"Most Wins ({target_year})": df.loc[df_year['Wins'].idxmax(), 'Team Name'],
#     f"Most Losses ({target_year})": df.loc[df_year['Losses'].idxmax(), 'Team Name'],
#     f"Lowest Win % ({target_year})": df.loc[df_year['Win_Pct'].idxmin(), 'Team Name'],
#     "Most Wins (All Years)": all_time_wins.idxmax()
# }

# # 5. Print the results clearly
# for question, team in results.items():
#     print(f"{question}: {team}")

Detroit Red Wings
Team Name            Year
Detroit Red Wings    1995    62
                     2005    58
Pittsburgh Penguins  1992    56
Detroit Red Wings    2007    54
Vancouver Canucks    2010    54
Name: Wins, dtype: Int64
<bound method Series.idxmax of Team Name      Year
Anaheim Ducks  2006    20
               2007    27
               2008    33
               2009    32
               2010    30
                       ..
Winnipeg Jets  1992    37
               1993    51
               1994    25
               1995    40
               2011    35
Name: Losses, Length: 582, dtype: Int64>

In [ ]:
top_team = df.loc[df['Losses'].idxmax(), 'Team Name']
top_team

In [234]:
df.dtypes

Team Name              object
Year                    int64
Wins                    Int64
Losses                  Int64
OT Losses               Int64
Win %                 float64
Goals For (GF)          Int64
Goals Against (GA)      Int64
+ / -                   Int64
dtype: object

In [239]:
df.groupby('Team Name').agg({'Wins': 'max', 'Losses': 'max' , 'Win %':'min'})

                         Wins  Losses  Win %
Team Name
Anaheim Ducks              48      36  0.415
Atlanta Thrashers          43      57  0.171
Boston Bruins              53      47  0.293
Buffalo Sabres             53      42  0.329
Calgary Flames             46      41  0.317
Carolina Hurricanes        52      43  0.268
Chicago Blackhawks         52      43  0.244
Colorado Avalanche         52      45  0.366
Columbus Blue Jackets      41      47  0.268
Dallas Stars               53      42  0.317
Detroit Red Wings          62      38  0.425
Edmonton Oilers            41      50  0.298
Florida Panthers           43      44  0.268
Hartford Whalers           34      52  0.310
Los Angeles Kings          46      45  0.293
Mighty Ducks of Anaheim    43      46  0.305
Minnesota North Stars      36      42  0.338
Minnesota Wild             48      39  0.305
Montreal Canadiens         48      40  0.341
Nashville Predators        51      47  0.329
New Jersey Devils          51      39  0.400
New York Islanders         42      51  0.256
New York Rangers           52      43  0.305
Ottawa Senators            52      70  0.119
Philadelphia Flyers        47      48  0.268
Phoenix Coyotes            50      46  0.268
Pittsburgh Penguins        56      47  0.268
Quebec Nordiques           47      50  0.200
San Jose Sharks            53      71  0.131
St. Louis Blues            51      46  0.256
Tampa Bay Lightning        46      55  0.207
Toronto Maple Leafs        45      46  0.287
Vancouver Canucks          54      47  0.280
Washington Capitals        54      46  0.280
Winnipeg Jets              40      51  0.286